using System.Text.Json;
using Bisync.Api.Contracts;
using Bisync.Api.Data;
using Bisync.Api.Models;
using Bisync.Api.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Bisync.Api.Controllers;

[ApiController]
[Route("api/sales-module")]
public class SalesModuleController(
    BisyncDbContext db,
    SalesModuleCalendarSyncService calendarSync,
    SalesModuleImportService importService,
    SalesModuleClientUpdateService clientUpdateService) : ControllerBase
{
    static readonly JsonSerializerOptions JsonOpts = new() { PropertyNamingPolicy = JsonNamingPolicy.CamelCase };

    static readonly HashSet<string> AllowedStatuses = new(StringComparer.OrdinalIgnoreCase)
    {
        "Prospect", "Engaged", "Active", "Inactive", "Closed",
    };

    static readonly HashSet<string> AllowedDiaryStatuses = new(StringComparer.OrdinalIgnoreCase)
    {
        "Prospect", "Proposed", "In Nego", "Sales Order", "Invoiced", "Paid", "Activated", "KIV", "Rejected",
    };

    static readonly HashSet<string> AllowedDiaryContactTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        "Cold Call", "Email Blast", "Follow up Call", "Follow up Visit", "Follow Up email",
        "Sales Meeting", "Demo Meeting", "Follow Up Meeting", "Online Presentation", "Offline Presentation",
        "Training", "Retraining", "Post Meeting", "Regular Catch Up",
    };

    static string NormalizeDiaryActivity(string? raw)
    {
        var s = (raw ?? string.Empty).Trim().Replace(" ", "", StringComparison.Ordinal);
        if (s.Equals("StatusChange", StringComparison.OrdinalIgnoreCase)) return "StatusChange";
        if (s.Equals("SalesCall", StringComparison.OrdinalIgnoreCase)) return "SalesCall";
        return string.Empty;
    }

    static string? ValidateDiaryEntry(CreateSalesModuleDiaryEntryRequest request)
    {
        if (request.SalesTeamMemberId <= 0) return "salesTeamMemberId is required.";
        var activity = NormalizeDiaryActivity(request.ActivityType);
        if (string.IsNullOrEmpty(activity)) return "Activity must be Status Change or Sales Call.";
        if (request.ContactDate == default) return "Date of Contact is required.";
        if (activity == "SalesCall")
        {
            var contactType = (request.ContactType ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(contactType) || !AllowedDiaryContactTypes.Contains(contactType))
                return "Select a valid Type of Contact.";
        }
        return null;
    }

    async Task EnsureSalesDiarySchemaAsync(CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SalesModuleDiaryEntries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SalesModuleDiaryEntries" PRIMARY KEY,
                "SalesTeamMemberId" integer NOT NULL,
                "ActivityType" TEXT NOT NULL DEFAULT '',
                "SalesModuleCompanyId" integer NULL,
                "CompanyName" TEXT NOT NULL DEFAULT '',
                "BrandName" TEXT NOT NULL DEFAULT '',
                "LocationVisited" TEXT NOT NULL DEFAULT '',
                "EmailsSent" integer NULL,
                "StatusesJson" TEXT NOT NULL DEFAULT '[]',
                "ContactType" TEXT NOT NULL DEFAULT '',
                "ContactDate" timestamp with time zone NOT NULL DEFAULT NOW(),
                "ContactsJson" TEXT NOT NULL DEFAULT '[]',
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "CreatedByEmail" TEXT NOT NULL DEFAULT ''
            );
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleDiaryEntries_Member"
            ON "SalesModuleDiaryEntries" ("SalesTeamMemberId");
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleDiaryEntries_ContactDate"
            ON "SalesModuleDiaryEntries" ("ContactDate");
            """, ct);
    }

    static object MapDiaryEntry(SalesModuleDiaryEntry e)
    {
        List<string> statuses;
        List<object> contacts;
        try
        {
            statuses = JsonSerializer.Deserialize<List<string>>(e.StatusesJson, JsonOpts) ?? [];
        }
        catch
        {
            statuses = [];
        }
        try
        {
            contacts = JsonSerializer.Deserialize<List<object>>(e.ContactsJson, JsonOpts) ?? [];
        }
        catch
        {
            contacts = [];
        }

        return new
        {
            e.Id,
            e.SalesTeamMemberId,
            activityType = e.ActivityType,
            activityLabel = e.ActivityType == "StatusChange" ? "Status Change" : "Sales Call",
            salesModuleCompanyId = e.SalesModuleCompanyId,
            companyName = e.CompanyName,
            brandName = e.BrandName,
            locationVisited = e.LocationVisited,
            emailsSent = e.EmailsSent,
            statuses,
            contactType = e.ContactType,
            contactDate = e.ContactDate,
            contacts,
            createdAt = e.CreatedAt,
            createdByEmail = e.CreatedByEmail,
        };
    }

    [HttpGet("customers")]
    public async Task<ActionResult<IEnumerable<object>>> GetCustomers(
        [FromQuery] int? companyId = null,
        [FromQuery] int? salesTeamMemberId = null,
        [FromQuery] int? engagedUserId = null,
        CancellationToken ct = default)
    {
        await EnsureSalesCompanySchemaAsync(ct);

        HashSet<int>? allowedCompanyIds = null;
        if (salesTeamMemberId is > 0)
        {
            var ids = await db.SalesModuleCompanyMembers.AsNoTracking()
                .Where(m => m.SalesTeamMemberId == salesTeamMemberId.Value)
                .Select(m => m.SalesModuleCompanyId)
                .ToListAsync(ct);
            allowedCompanyIds = ids.ToHashSet();
        }

        if (companyId is > 0)
        {
            if (allowedCompanyIds is not null && !allowedCompanyIds.Contains(companyId.Value))
                return Ok(Array.Empty<object>());
            allowedCompanyIds = new HashSet<int> { companyId.Value };
        }

        if (allowedCompanyIds is null)
            return BadRequest(new { message = "companyId or salesTeamMemberId is required." });

        if (allowedCompanyIds.Count == 0)
            return Ok(Array.Empty<object>());

        var q = db.SalesModuleCustomers.AsNoTracking()
            .Where(c => c.Active && allowedCompanyIds.Contains(c.CompanyId));
        if (engagedUserId is > 0)
            q = q.Where(c => c.EngagedUserId == engagedUserId.Value);

        var rows = await q.OrderByDescending(c => c.CreatedAt).ToListAsync(ct);
        return Ok(rows.Select(MapCustomer));
    }

    [HttpPost("customers")]
    public async Task<ActionResult<object>> CreateCustomer([FromBody] UpsertSalesModuleCustomerRequest request, CancellationToken ct)
    {
        var error = ValidateCustomer(request);
        if (error is not null) return BadRequest(new { message = error });

        await EnsureSalesCompanySchemaAsync(ct);
        var salesCompany = await db.SalesModuleCompanies.AsNoTracking()
            .FirstOrDefaultAsync(c => c.Id == request.CompanyId && c.Active, ct);
        if (salesCompany is null)
            return BadRequest(new { message = "Sales company not found. Create and tag a company to a sales team member first." });

        var externalId = string.IsNullOrWhiteSpace(request.ExternalId)
            ? await NextCustomerExternalIdAsync(request.CompanyId, ct)
            : request.ExternalId.Trim();

        if (await db.SalesModuleCustomers.AnyAsync(c => c.ExternalId.ToLower() == externalId.ToLower(), ct))
            return Conflict(new { message = $"Customer id {externalId} already exists." });

        var customer = MapToCustomer(new SalesModuleCustomer(), request, externalId);
        if (string.IsNullOrWhiteSpace(customer.CompanyName))
            customer.CompanyName = salesCompany.Name;
        customer.CreatedAt = DateTime.UtcNow;
        db.SalesModuleCustomers.Add(customer);
        await db.SaveChangesAsync(ct);
        return Ok(MapCustomer(customer));
    }

    [HttpPut("customers/{externalId}")]
    public async Task<ActionResult<object>> UpdateCustomer(
        string externalId,
        [FromBody] UpsertSalesModuleCustomerRequest request,
        CancellationToken ct)
    {
        var error = ValidateCustomer(request);
        if (error is not null) return BadRequest(new { message = error });

        var customer = await db.SalesModuleCustomers.FirstOrDefaultAsync(c => c.ExternalId == externalId, ct);
        if (customer is null) return NotFound();

        MapToCustomer(customer, request, customer.ExternalId);
        await db.SaveChangesAsync(ct);
        return Ok(MapCustomer(customer));
    }

    [HttpGet("appointments")]
    public async Task<ActionResult<IEnumerable<object>>> GetAppointments(
        [FromQuery] int companyId,
        [FromQuery] int? engagedUserId = null,
        [FromQuery] DateTime? from = null,
        [FromQuery] DateTime? to = null,
        CancellationToken ct = default)
    {
        if (companyId <= 0) return BadRequest(new { message = "companyId is required." });

        var rangeStart = from ?? new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, 1, 0, 0, 0, DateTimeKind.Utc);
        var rangeEnd = to ?? rangeStart.AddMonths(2);

        var q = db.SalesModuleAppointments.AsNoTracking()
            .Where(a => a.CompanyId == companyId && a.StartsAt < rangeEnd && a.EndsAt >= rangeStart);
        if (engagedUserId is > 0)
            q = q.Where(a => a.EngagedUserId == engagedUserId.Value);

        var appointments = await q.OrderBy(a => a.StartsAt).ToListAsync(ct);
        var customerIds = appointments.Select(a => a.SalesModuleCustomerId).Distinct().ToList();
        var customers = await db.SalesModuleCustomers.AsNoTracking()
            .Where(c => customerIds.Contains(c.Id))
            .ToDictionaryAsync(c => c.Id, ct);

        return Ok(appointments.Select(a => MapAppointment(a, customers.GetValueOrDefault(a.SalesModuleCustomerId))));
    }

    [HttpPost("appointments")]
    public async Task<ActionResult<object>> CreateAppointment(
        [FromBody] UpsertSalesModuleAppointmentRequest request,
        CancellationToken ct)
    {
        var error = ValidateAppointment(request);
        if (error is not null) return BadRequest(new { message = error });

        await EnsureSalesCompanySchemaAsync(ct);
        if (!await db.SalesModuleCompanies.AsNoTracking().AnyAsync(c => c.Id == request.CompanyId && c.Active, ct))
            return BadRequest(new { message = "Sales company not found." });

        var customer = await db.SalesModuleCustomers.AsNoTracking()
            .FirstOrDefaultAsync(c => c.Id == request.SalesModuleCustomerId && c.CompanyId == request.CompanyId, ct);
        if (customer is null) return BadRequest(new { message = "Sales Module customer not found." });

        SalesModuleTeamMember? teamMember = null;
        if (request.SalesTeamMemberId is > 0)
        {
            teamMember = (await calendarSync.ListTeamAsync(ct))
                .FirstOrDefault(m => m.Id == request.SalesTeamMemberId.Value && m.Active);
            if (teamMember is null)
                return BadRequest(new { message = "Sales team member not found." });
        }

        var engagedEmail = !string.IsNullOrWhiteSpace(request.EngagedUserEmail)
            ? request.EngagedUserEmail.Trim().ToLowerInvariant()
            : teamMember?.Email ?? string.Empty;

        var row = new SalesModuleAppointment
        {
            CompanyId = request.CompanyId,
            SalesModuleCustomerId = request.SalesModuleCustomerId,
            Title = request.Title.Trim(),
            Notes = (request.Notes ?? string.Empty).Trim(),
            StartsAt = DateTime.SpecifyKind(request.StartsAt, DateTimeKind.Utc),
            EndsAt = DateTime.SpecifyKind(request.EndsAt, DateTimeKind.Utc),
            Location = (request.Location ?? string.Empty).Trim(),
            EngagedUserId = request.EngagedUserId,
            EngagedUserEmail = engagedEmail,
            SalesTeamMemberId = teamMember?.Id,
            CreatedAt = DateTime.UtcNow,
        };
        db.SalesModuleAppointments.Add(row);
        await db.SaveChangesAsync(ct);

        await calendarSync.PushCreateAsync(row, customer, ct);

        return Ok(MapAppointment(row, customer));
    }

    [HttpDelete("appointments/{id:int}")]
    public async Task<ActionResult> DeleteAppointment(int id, CancellationToken ct)
    {
        var row = await db.SalesModuleAppointments.FirstOrDefaultAsync(a => a.Id == id, ct);
        if (row is null) return NotFound();

        await calendarSync.PushDeleteAsync(row, ct);

        db.SalesModuleAppointments.Remove(row);
        await db.SaveChangesAsync(ct);
        return NoContent();
    }

    [HttpGet("calendar-sync")]
    public async Task<ActionResult<object>> GetCalendarSync(CancellationToken ct)
    {
        var settings = await calendarSync.GetOrCreateAsync(ct);
        return Ok(calendarSync.ToPublicDto(settings));
    }

    [HttpGet("companies")]
    public async Task<ActionResult<IEnumerable<object>>> GetSalesCompanies(
        [FromQuery] int? salesTeamMemberId = null,
        [FromQuery] bool includeInactive = false,
        CancellationToken ct = default)
    {
        await EnsureSalesCompanySchemaAsync(ct);

        IQueryable<SalesModuleCompany> q = db.SalesModuleCompanies.AsNoTracking();
        if (!includeInactive)
            q = q.Where(c => c.Active);

        if (salesTeamMemberId is > 0)
        {
            var companyIds = await db.SalesModuleCompanyMembers.AsNoTracking()
                .Where(m => m.SalesTeamMemberId == salesTeamMemberId.Value)
                .Select(m => m.SalesModuleCompanyId)
                .ToListAsync(ct);
            q = q.Where(c => companyIds.Contains(c.Id));
        }

        var rows = await q.OrderBy(c => c.Name).ToListAsync(ct);
        var tags = await db.SalesModuleCompanyMembers.AsNoTracking()
            .Where(t => rows.Select(r => r.Id).Contains(t.SalesModuleCompanyId))
            .ToListAsync(ct);
        var members = await calendarSync.ListTeamAsync(ct);
        var memberMap = members.ToDictionary(m => m.Id);

        return Ok(rows.Select(c => MapSalesCompany(c, tags, memberMap)));
    }

    [HttpPost("companies")]
    public async Task<ActionResult<object>> CreateSalesCompany(
        [FromBody] UpsertSalesModuleCompanyRequest request,
        CancellationToken ct)
    {
        await EnsureSalesCompanySchemaAsync(ct);
        var error = ValidateSalesCompany(request);
        if (error is not null) return BadRequest(new { message = error });

        var memberIds = request.SalesTeamMemberIds.Where(id => id > 0).Distinct().ToList();
        var existingMembers = await db.SalesModuleTeamMembers.AsNoTracking()
            .Where(m => memberIds.Contains(m.Id))
            .Select(m => m.Id)
            .ToListAsync(ct);
        if (existingMembers.Count != memberIds.Count)
            return BadRequest(new { message = "One or more sales team members were not found." });

        var name = request.Name.Trim();
        if (await db.SalesModuleCompanies.AnyAsync(c => c.Name.ToLower() == name.ToLower(), ct))
            return Conflict(new { message = $"Company \"{name}\" already exists." });

        var row = new SalesModuleCompany
        {
            Name = name,
            Active = request.Active,
            CreatedAt = DateTime.UtcNow,
            UpdatedAt = DateTime.UtcNow,
        };
        db.SalesModuleCompanies.Add(row);
        await db.SaveChangesAsync(ct);

        foreach (var memberId in memberIds)
        {
            db.SalesModuleCompanyMembers.Add(new SalesModuleCompanyMember
            {
                SalesModuleCompanyId = row.Id,
                SalesTeamMemberId = memberId,
            });
        }
        await db.SaveChangesAsync(ct);

        var tags = await db.SalesModuleCompanyMembers.AsNoTracking()
            .Where(t => t.SalesModuleCompanyId == row.Id)
            .ToListAsync(ct);
        var members = await calendarSync.ListTeamAsync(ct);
        return Ok(MapSalesCompany(row, tags, members.ToDictionary(m => m.Id)));
    }

    [HttpPut("companies/{id:int}")]
    public async Task<ActionResult<object>> UpdateSalesCompany(
        int id,
        [FromBody] UpsertSalesModuleCompanyRequest request,
        CancellationToken ct)
    {
        await EnsureSalesCompanySchemaAsync(ct);
        var error = ValidateSalesCompany(request);
        if (error is not null) return BadRequest(new { message = error });

        var row = await db.SalesModuleCompanies.FirstOrDefaultAsync(c => c.Id == id, ct);
        if (row is null) return NotFound();

        var memberIds = request.SalesTeamMemberIds.Where(mid => mid > 0).Distinct().ToList();
        var existingMembers = await db.SalesModuleTeamMembers.AsNoTracking()
            .Where(m => memberIds.Contains(m.Id))
            .Select(m => m.Id)
            .ToListAsync(ct);
        if (existingMembers.Count != memberIds.Count)
            return BadRequest(new { message = "One or more sales team members were not found." });

        var name = request.Name.Trim();
        if (await db.SalesModuleCompanies.AnyAsync(c => c.Id != id && c.Name.ToLower() == name.ToLower(), ct))
            return Conflict(new { message = $"Company \"{name}\" already exists." });

        row.Name = name;
        row.Active = request.Active;
        row.UpdatedAt = DateTime.UtcNow;

        var existingTags = await db.SalesModuleCompanyMembers
            .Where(t => t.SalesModuleCompanyId == id)
            .ToListAsync(ct);
        db.SalesModuleCompanyMembers.RemoveRange(existingTags);
        foreach (var memberId in memberIds)
        {
            db.SalesModuleCompanyMembers.Add(new SalesModuleCompanyMember
            {
                SalesModuleCompanyId = id,
                SalesTeamMemberId = memberId,
            });
        }
        await db.SaveChangesAsync(ct);

        var tags = await db.SalesModuleCompanyMembers.AsNoTracking()
            .Where(t => t.SalesModuleCompanyId == id)
            .ToListAsync(ct);
        var members = await calendarSync.ListTeamAsync(ct);
        return Ok(MapSalesCompany(row, tags, members.ToDictionary(m => m.Id)));
    }

    [HttpDelete("companies/{id:int}")]
    public async Task<ActionResult> DeleteSalesCompany(int id, CancellationToken ct)
    {
        await EnsureSalesCompanySchemaAsync(ct);
        var row = await db.SalesModuleCompanies.FirstOrDefaultAsync(c => c.Id == id, ct);
        if (row is null) return NotFound();

        if (await db.SalesModuleCustomers.AnyAsync(c => c.CompanyId == id && c.Active, ct))
            return BadRequest(new { message = "Cannot delete a company that still has active customers. Deactivate it instead." });

        var tags = await db.SalesModuleCompanyMembers.Where(t => t.SalesModuleCompanyId == id).ToListAsync(ct);
        db.SalesModuleCompanyMembers.RemoveRange(tags);
        db.SalesModuleCompanies.Remove(row);
        await db.SaveChangesAsync(ct);
        return NoContent();
    }

    /// <summary>
    /// Import companies/pipeline rows from Excel or CSV.
    /// Only rows whose first column (Date Created) equals onlyDate (default 1 January 2026) are imported.
    /// Optional companyName filters to a single company (e.g. Atta).
    /// </summary>
    [HttpPost("import")]
    [RequestSizeLimit(20_000_000)]
    public async Task<ActionResult<object>> ImportCompanies(
        IFormFile file,
        [FromForm] int salesTeamMemberId,
        [FromForm] string? onlyDate = null,
        [FromForm] string? companyName = null,
        CancellationToken ct = default)
    {
        if (file is null || file.Length == 0)
            return BadRequest(new { message = "Upload an Excel (.xlsx) or CSV file." });
        if (salesTeamMemberId <= 0)
            return BadRequest(new { message = "salesTeamMemberId is required." });

        DateOnly? filterDate = null;
        if (!string.IsNullOrWhiteSpace(onlyDate)
            && DateOnly.TryParse(onlyDate, out var parsed))
            filterDate = parsed;

        try
        {
            await using var stream = file.OpenReadStream();
            var result = await importService.ImportAsync(
                stream,
                file.FileName,
                salesTeamMemberId,
                filterDate,
                companyName,
                ct);
            return Ok(result);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = $"Import failed: {ex.Message}" });
        }
    }

    /// <summary>Import Atta dated 1 January 2026 for the selected sales team member.</summary>
    [HttpPost("import/atta")]
    public async Task<ActionResult<object>> ImportAtta(
        [FromQuery] int salesTeamMemberId,
        CancellationToken ct = default)
    {
        if (salesTeamMemberId <= 0)
            return BadRequest(new { message = "salesTeamMemberId is required." });
        try
        {
            var result = await importService.ImportAttaSeedAsync(salesTeamMemberId, ct);
            return Ok(result);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    /// <summary>Available week/month periods for Sales Module Overview filters.</summary>
    [HttpGet("overview/periods")]
    public async Task<ActionResult<object>> GetOverviewPeriods(CancellationToken ct = default)
    {
        var result = await clientUpdateService.GetOverviewPeriodsAsync(ct);
        return Ok(result);
    }

    /// <summary>
    /// Overview summary by Hunter: status changes, interactions (contact), and new leads.
    /// Requires view=week with weekStart, or view=month with year+month.
    /// Optional salesTeamMemberId / companyId filters.
    /// </summary>
    [HttpGet("overview")]
    public async Task<ActionResult<object>> GetOverview(
        [FromQuery] string view = "week",
        [FromQuery] string? weekStart = null,
        [FromQuery] int? year = null,
        [FromQuery] int? month = null,
        [FromQuery] int? salesTeamMemberId = null,
        [FromQuery] int? companyId = null,
        CancellationToken ct = default)
    {
        try
        {
            var result = await clientUpdateService.GetOverviewAsync(
                view, weekStart, year, month, salesTeamMemberId, companyId, ct);
            return Ok(result);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    /// <summary>
    /// List Client Update rows for last week plus week-to-date only
    /// (Instant Sales Update → Weekly Update sheet).
    /// Prefer salesTeamMemberId to scope by Sales Team Hunter.
    /// </summary>
    [HttpGet("client-updates")]
    public async Task<ActionResult<IEnumerable<object>>> GetClientUpdates(
        [FromQuery] string? hunter = null,
        [FromQuery] int? salesTeamMemberId = null,
        CancellationToken ct = default)
    {
        var rows = await clientUpdateService.ListAsync(hunter, salesTeamMemberId, ct);
        return Ok(rows);
    }

    /// <summary>
    /// Rematch free-text Client Update Hunter values (manual upload) to Sales Team members.
    /// Normalizes Hunter to the team member display name and sets SalesTeamMemberId.
    /// </summary>
    [HttpPost("client-updates/rematch-hunters")]
    public async Task<ActionResult<object>> RematchClientUpdateHunters(CancellationToken ct = default)
    {
        var result = await clientUpdateService.RematchHuntersAsync(ct);
        return Ok(result);
    }

    /// <summary>
    /// Fill blank Client Update identity fields (Date Created, Hunter, Company, Brand, No. of Location).
    /// Existing non-blank values are not overwritten.
    /// </summary>
    [HttpPatch("client-updates/{id:int}")]
    public async Task<ActionResult<object>> PatchClientUpdate(
        int id,
        [FromBody] PatchSalesModuleClientUpdateRequest request,
        CancellationToken ct = default)
    {
        if (id <= 0) return BadRequest(new { message = "id is required." });
        try
        {
            var row = await clientUpdateService.PatchBlankFieldsAsync(
                id,
                request.DateCreated,
                request.Hunter,
                request.Company,
                request.Brand,
                request.LocationCount,
                request.SalesTeamMemberId,
                ct);
            return Ok(row);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    /// <summary>List Sales Diary entries for a Hunter (Sales Team member).</summary>
    [HttpGet("diary")]
    public async Task<ActionResult<IEnumerable<object>>> GetDiaryEntries(
        [FromQuery] int salesTeamMemberId,
        CancellationToken ct = default)
    {
        if (salesTeamMemberId <= 0)
            return BadRequest(new { message = "salesTeamMemberId is required." });

        await EnsureSalesDiarySchemaAsync(ct);
        var rows = await db.SalesModuleDiaryEntries.AsNoTracking()
            .Where(e => e.SalesTeamMemberId == salesTeamMemberId)
            .OrderByDescending(e => e.ContactDate)
            .ThenByDescending(e => e.Id)
            .Take(200)
            .ToListAsync(ct);
        return Ok(rows.Select(MapDiaryEntry));
    }

    /// <summary>Create a Sales Diary Status Change or Sales Call entry.</summary>
    [HttpPost("diary")]
    public async Task<ActionResult<object>> CreateDiaryEntry(
        [FromBody] CreateSalesModuleDiaryEntryRequest request,
        CancellationToken ct = default)
    {
        await EnsureSalesDiarySchemaAsync(ct);
        await EnsureSalesCompanySchemaAsync(ct);

        var error = ValidateDiaryEntry(request);
        if (error is not null) return BadRequest(new { message = error });

        var member = await db.SalesModuleTeamMembers.AsNoTracking()
            .FirstOrDefaultAsync(m => m.Id == request.SalesTeamMemberId, ct);
        if (member is null)
            return BadRequest(new { message = "Sales team member not found." });

        var activity = NormalizeDiaryActivity(request.ActivityType);
        var contactType = (request.ContactType ?? string.Empty).Trim();
        var skipsCompany = activity == "SalesCall"
            && (contactType.Equals("Cold Call", StringComparison.OrdinalIgnoreCase)
                || contactType.Equals("Email Blast", StringComparison.OrdinalIgnoreCase));

        int? companyId = null;
        var companyName = (request.CompanyName ?? string.Empty).Trim();

        if (!skipsCompany)
        {
            if (request.SalesModuleCompanyId is not > 0)
                return BadRequest(new { message = "Select a company tagged to this Hunter." });

            var tagged = await db.SalesModuleCompanyMembers.AsNoTracking()
                .AnyAsync(
                    t => t.SalesModuleCompanyId == request.SalesModuleCompanyId.Value
                        && t.SalesTeamMemberId == request.SalesTeamMemberId,
                    ct);
            if (!tagged)
                return BadRequest(new { message = "Company is not tagged to this Hunter." });

            var company = await db.SalesModuleCompanies.AsNoTracking()
                .FirstOrDefaultAsync(c => c.Id == request.SalesModuleCompanyId.Value && c.Active, ct);
            if (company is null)
                return BadRequest(new { message = "Company not found." });

            companyId = company.Id;
            companyName = company.Name;
        }
        else if (contactType.Equals("Cold Call", StringComparison.OrdinalIgnoreCase))
        {
            if (string.IsNullOrWhiteSpace(companyName) && string.IsNullOrWhiteSpace(request.BrandName))
                return BadRequest(new { message = "Cold Call requires company / brand name." });
            if (string.IsNullOrWhiteSpace(request.LocationVisited))
                return BadRequest(new { message = "Cold Call requires location visited." });
            if (string.IsNullOrWhiteSpace(companyName))
                companyName = (request.BrandName ?? string.Empty).Trim();
        }
        else if (contactType.Equals("Email Blast", StringComparison.OrdinalIgnoreCase))
        {
            if (request.EmailsSent is null or < 1)
                return BadRequest(new { message = "Email Blast requires number of emails sent." });
        }

        var contacts = (request.Contacts ?? [])
            .Where(c => !string.IsNullOrWhiteSpace(c.Name))
            .Select(c => new
            {
                name = c.Name.Trim(),
                position = (c.Position ?? string.Empty).Trim(),
            })
            .ToList();

        if (activity == "SalesCall" && contacts.Count == 0
            && !contactType.Equals("Email Blast", StringComparison.OrdinalIgnoreCase))
        {
            // Contact person required for sales calls except email blast (mass send).
            // User asked for Contact Person / Position with + button — require at least one name for non-blast.
            return BadRequest(new { message = "Add at least one contact person." });
        }

        var statuses = activity == "StatusChange"
            ? (request.Statuses ?? [])
                .Select(s => s.Trim())
                .Where(s => AllowedDiaryStatuses.Contains(s))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToList()
            : [];

        if (activity == "StatusChange" && statuses.Count == 0)
            return BadRequest(new { message = "Tick at least one status." });

        var row = new SalesModuleDiaryEntry
        {
            SalesTeamMemberId = request.SalesTeamMemberId,
            ActivityType = activity,
            SalesModuleCompanyId = companyId,
            CompanyName = companyName,
            BrandName = (request.BrandName ?? string.Empty).Trim(),
            LocationVisited = (request.LocationVisited ?? string.Empty).Trim(),
            EmailsSent = contactType.Equals("Email Blast", StringComparison.OrdinalIgnoreCase)
                ? request.EmailsSent
                : null,
            StatusesJson = JsonSerializer.Serialize(statuses, JsonOpts),
            ContactType = activity == "SalesCall" ? contactType : string.Empty,
            ContactDate = DateTime.SpecifyKind(request.ContactDate.Date, DateTimeKind.Utc),
            ContactsJson = JsonSerializer.Serialize(contacts, JsonOpts),
            CreatedAt = DateTime.UtcNow,
            CreatedByEmail = (request.CreatedByEmail ?? string.Empty).Trim().ToLowerInvariant(),
        };
        db.SalesModuleDiaryEntries.Add(row);
        await db.SaveChangesAsync(ct);

        // Keep Client Update (and Overview metrics) aligned with diary activity.
        var contactTuples = contacts
            .Select(c => (c.name, c.position))
            .ToList();
        try
        {
            await clientUpdateService.ApplyDiaryEntryAsync(
                member.Id,
                member.Name,
                activity,
                companyName,
                row.BrandName,
                row.LocationVisited,
                row.EmailsSent,
                statuses,
                row.ContactType,
                row.ContactDate,
                contactTuples,
                ct);
        }
        catch
        {
            // Diary is already saved; do not fail the request if Client Update sync fails.
        }

        return Ok(MapDiaryEntry(row));
    }

    [HttpDelete("diary/{id:int}")]
    public async Task<IActionResult> DeleteDiaryEntry(int id, CancellationToken ct = default)
    {
        await EnsureSalesDiarySchemaAsync(ct);
        var row = await db.SalesModuleDiaryEntries.FirstOrDefaultAsync(e => e.Id == id, ct);
        if (row is null) return NotFound();
        db.SalesModuleDiaryEntries.Remove(row);
        await db.SaveChangesAsync(ct);
        return NoContent();
    }

    /// <summary>
    /// Import only the "Weekly Update" sheet from Instant Sales Update.xlsx (replaces existing Client Update rows).
    /// </summary>
    [HttpPost("client-updates/import")]
    [RequestSizeLimit(20_000_000)]
    public async Task<ActionResult<object>> ImportClientUpdates(IFormFile file, CancellationToken ct = default)
    {
        if (file is null || file.Length == 0)
            return BadRequest(new { message = "Upload Instant Sales Update.xlsx (Weekly Update sheet)." });
        try
        {
            await using var stream = file.OpenReadStream();
            var result = await clientUpdateService.ImportWeeklyUpdateAsync(stream, file.FileName, ct);
            return Ok(result);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
        catch (Exception ex)
        {
            return BadRequest(new { message = $"Client Update import failed: {ex.Message}" });
        }
    }

    [HttpGet("team")]
    public async Task<ActionResult<IEnumerable<object>>> GetTeam(CancellationToken ct)
    {
        var rows = await calendarSync.ListTeamAsync(ct);
        return Ok(rows.Select(SalesModuleCalendarSyncService.MapTeamMember));
    }

    /// <summary>Shared Graph credentials used when wiring Sales Team member calendars.</summary>
    [HttpGet("team/graph-settings")]
    public async Task<ActionResult<object>> GetTeamGraphSettings(CancellationToken ct)
    {
        var settings = await calendarSync.GetOrCreateAsync(ct);
        return Ok(calendarSync.ToPublicDto(settings));
    }

    [HttpPost("team")]
    public async Task<ActionResult<object>> CreateTeamMember(
        [FromBody] UpsertSalesModuleTeamMemberRequest request,
        CancellationToken ct)
    {
        try
        {
            var row = await calendarSync.CreateTeamMemberAsync(
                request.Name,
                request.Email,
                request.CalendarSyncEnabled,
                request.GraphTenantId,
                request.GraphClientId,
                request.GraphClientSecret,
                ct);
            return Ok(SalesModuleCalendarSyncService.MapTeamMember(row));
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    [HttpPut("team/{id:int}")]
    public async Task<ActionResult<object>> UpdateTeamMember(
        int id,
        [FromBody] UpsertSalesModuleTeamMemberRequest request,
        CancellationToken ct)
    {
        try
        {
            var row = await calendarSync.UpdateTeamMemberAsync(
                id,
                request.Name,
                request.Email,
                request.Active,
                request.CalendarSyncEnabled,
                request.GraphTenantId,
                request.GraphClientId,
                request.GraphClientSecret,
                ct);
            if (row is null) return NotFound();
            return Ok(SalesModuleCalendarSyncService.MapTeamMember(row));
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { message = ex.Message });
        }
    }

    [HttpDelete("team/{id:int}")]
    public async Task<ActionResult> DeleteTeamMember(int id, CancellationToken ct)
    {
        var ok = await calendarSync.DeleteTeamMemberAsync(id, ct);
        return ok ? NoContent() : NotFound();
    }

    [HttpPost("team/{id:int}/test-calendar")]
    public async Task<ActionResult<object>> TestTeamMemberCalendar(int id, CancellationToken ct)
    {
        var (ok, message) = await calendarSync.TestTeamMemberAsync(id, ct);
        var members = await calendarSync.ListTeamAsync(ct);
        var member = members.FirstOrDefault(m => m.Id == id);
        return Ok(new
        {
            ok,
            message,
            member = member is null ? null : SalesModuleCalendarSyncService.MapTeamMember(member),
        });
    }

    [HttpGet("team-calendars")]
    public async Task<ActionResult<object>> GetTeamCalendars(
        [FromQuery] DateTime? from = null,
        [FromQuery] DateTime? to = null,
        CancellationToken ct = default)
    {
        var rangeStart = from ?? new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, 1, 0, 0, 0, DateTimeKind.Utc);
        var rangeEnd = to ?? rangeStart.AddMonths(2);
        var payload = await calendarSync.PullTeamCalendarsAsync(rangeStart, rangeEnd, ct);
        return Ok(payload);
    }

    async Task<string> NextCustomerExternalIdAsync(int companyId, CancellationToken ct)
    {
        var existing = await db.SalesModuleCustomers.AsNoTracking()
            .Where(c => c.CompanyId == companyId)
            .Select(c => c.ExternalId)
            .ToListAsync(ct);
        var max = 0;
        foreach (var id in existing)
        {
            var digits = new string(id.Where(char.IsDigit).ToArray());
            if (int.TryParse(digits, out var n) && n > max) max = n;
        }
        return $"SMC-{max + 1:D4}";
    }

    static string? ValidateCustomer(UpsertSalesModuleCustomerRequest request)
    {
        if (request.CompanyId <= 0) return "Sales company is required.";
        if (string.IsNullOrWhiteSpace(request.CompanyName)) return "Company name is required.";
        if (!AllowedStatuses.Contains(request.Status?.Trim() ?? string.Empty))
            return "Status must be Prospect, Engaged, Active, Inactive, or Closed.";
        if (request.Contacts.Count == 0 || request.Contacts.All(c => string.IsNullOrWhiteSpace(c.Name)))
            return "At least one contact person is required.";
        return null;
    }

    static string? ValidateAppointment(UpsertSalesModuleAppointmentRequest request)
    {
        if (request.CompanyId <= 0) return "Sales company is required.";
        if (request.SalesModuleCustomerId <= 0) return "Customer is required.";
        if (string.IsNullOrWhiteSpace(request.Title)) return "Title is required.";
        if (request.EndsAt <= request.StartsAt) return "End time must be after start time.";
        return null;
    }

    static string? ValidateSalesCompany(UpsertSalesModuleCompanyRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Name)) return "Company name is required.";
        if (request.SalesTeamMemberIds is null || request.SalesTeamMemberIds.Count == 0
            || request.SalesTeamMemberIds.All(id => id <= 0))
            return "Tag at least one sales team member to this company.";
        return null;
    }

    async Task EnsureSalesCompanySchemaAsync(CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SalesModuleCompanies" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SalesModuleCompanies" PRIMARY KEY,
                "Name" TEXT NOT NULL DEFAULT '',
                "Active" boolean NOT NULL DEFAULT true,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "CreatedByEmail" TEXT NOT NULL DEFAULT ''
            );
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SalesModuleCompanyMembers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SalesModuleCompanyMembers" PRIMARY KEY,
                "SalesModuleCompanyId" integer NOT NULL,
                "SalesTeamMemberId" integer NOT NULL
            );
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesModuleCompanyMembers_Pair"
            ON "SalesModuleCompanyMembers" ("SalesModuleCompanyId", "SalesTeamMemberId");
            """, ct);
    }

    static object MapSalesCompany(
        SalesModuleCompany c,
        List<SalesModuleCompanyMember> tags,
        Dictionary<int, SalesModuleTeamMember> members)
    {
        var memberIds = tags
            .Where(t => t.SalesModuleCompanyId == c.Id)
            .Select(t => t.SalesTeamMemberId)
            .Distinct()
            .ToList();
        return new
        {
            c.Id,
            c.Name,
            c.Active,
            createdAt = c.CreatedAt,
            updatedAt = c.UpdatedAt,
            createdByEmail = c.CreatedByEmail,
            salesTeamMemberIds = memberIds,
            salesTeamMembers = memberIds
                .Where(id => members.ContainsKey(id))
                .Select(id => new
                {
                    id,
                    name = members[id].Name,
                    email = members[id].Email,
                }),
        };
    }

    static SalesModuleCustomer MapToCustomer(SalesModuleCustomer customer, UpsertSalesModuleCustomerRequest request, string externalId)
    {
        customer.CompanyId = request.CompanyId;
        customer.ExternalId = externalId;
        customer.CompanyName = request.CompanyName.Trim();
        customer.BrandsJson = JsonSerializer.Serialize(
            request.Brands
                .Where(b => !string.IsNullOrWhiteSpace(b.Name))
                .Select(b => new { name = b.Name.Trim(), count = Math.Max(0, b.Count) }),
            JsonOpts);
        customer.ContactsJson = JsonSerializer.Serialize(
            request.Contacts
                .Where(c => !string.IsNullOrWhiteSpace(c.Name))
                .Select(c => new
                {
                    id = string.IsNullOrWhiteSpace(c.Id) ? Guid.NewGuid().ToString("N")[..8] : c.Id.Trim(),
                    name = c.Name.Trim(),
                    position = (c.Position ?? string.Empty).Trim(),
                    email = (c.Email ?? string.Empty).Trim(),
                    mobile = (c.Mobile ?? string.Empty).Trim(),
                }),
            JsonOpts);
        customer.Status = request.Status.Trim();
        customer.LastContactDate = request.LastContactDate.HasValue
            ? DateTime.SpecifyKind(request.LastContactDate.Value, DateTimeKind.Utc)
            : null;
        customer.LastDiscussionBrief = (request.LastDiscussionBrief ?? string.Empty).Trim();
        customer.LocationCount = Math.Max(0, request.LocationCount);
        if (request.CreatedAt.HasValue)
            customer.CreatedAt = DateTime.SpecifyKind(request.CreatedAt.Value, DateTimeKind.Utc);
        customer.LastChangedAt = request.LastChangedAt.HasValue
            ? DateTime.SpecifyKind(request.LastChangedAt.Value, DateTimeKind.Utc)
            : DateTime.UtcNow;
        customer.HunterMemberId = request.HunterMemberId is > 0 ? request.HunterMemberId : null;
        customer.HunterName = (request.HunterName ?? string.Empty).Trim();
        customer.FarmerMemberId = request.FarmerMemberId is > 0 ? request.FarmerMemberId : null;
        customer.FarmerName = (request.FarmerName ?? string.Empty).Trim();
        customer.EngagedUserId = request.EngagedUserId;
        customer.EngagedUserEmail = (request.EngagedUserEmail ?? string.Empty).Trim().ToLowerInvariant();
        customer.EngagedUserName = (request.EngagedUserName ?? string.Empty).Trim();
        customer.Active = request.Active;
        return customer;
    }

    static object MapCustomer(SalesModuleCustomer c) => new
    {
        c.Id,
        c.CompanyId,
        c.ExternalId,
        c.CompanyName,
        brands = ParseJson(c.BrandsJson),
        contacts = ParseJson(c.ContactsJson),
        c.Status,
        createdAt = c.CreatedAt,
        lastContactDate = c.LastContactDate,
        c.LastDiscussionBrief,
        locationCount = c.LocationCount,
        lastChangedAt = c.LastChangedAt == default ? c.CreatedAt : c.LastChangedAt,
        hunterMemberId = c.HunterMemberId,
        hunterName = c.HunterName,
        farmerMemberId = c.FarmerMemberId,
        farmerName = c.FarmerName,
        c.EngagedUserId,
        c.EngagedUserEmail,
        c.EngagedUserName,
        c.Active,
    };

    static object MapAppointment(SalesModuleAppointment a, SalesModuleCustomer? customer) => new
    {
        a.Id,
        a.CompanyId,
        a.SalesModuleCustomerId,
        customerName = customer?.CompanyName ?? string.Empty,
        customerExternalId = customer?.ExternalId ?? string.Empty,
        a.Title,
        a.Notes,
        startsAt = a.StartsAt,
        endsAt = a.EndsAt,
        a.Location,
        a.EngagedUserId,
        a.EngagedUserEmail,
        salesTeamMemberId = a.SalesTeamMemberId,
        createdAt = a.CreatedAt,
        outlookEventId = a.OutlookEventId,
        outlookWebLink = string.IsNullOrWhiteSpace(a.OutlookWebLink) ? null : a.OutlookWebLink,
        outlookSynced = !string.IsNullOrWhiteSpace(a.OutlookEventId),
        outlookSyncError = string.IsNullOrWhiteSpace(a.OutlookSyncError) ? null : a.OutlookSyncError,
        outlookSyncedAt = a.OutlookSyncedAt,
    };

    static object ParseJson(string json)
    {
        try
        {
            return JsonSerializer.Deserialize<object>(json) ?? Array.Empty<object>();
        }
        catch
        {
            return Array.Empty<object>();
        }
    }
}
