using Bisync.Api.Data;
using Bisync.Api.Models;
using Bisync.Api.Tenancy;
using Microsoft.EntityFrameworkCore;

namespace Bisync.Api.Services;

public sealed class LocationSubscriptionDetail
{
    public string LocationExternalId { get; set; } = string.Empty;
    public string LocationName { get; set; } = string.Empty;
    public string Status { get; set; } = LocationSubscription.StatusFreeTrial;
    public string StatusLabel { get; set; } = "Free Trial";
    public DateTime? StatusDate { get; set; }
    public DateTime? ExpiryDate { get; set; }
    public DateTime? RegisteredAt { get; set; }
    public int YearsRenewed { get; set; }
    public bool Locked { get; set; }
    public string? PaymentMethod { get; set; }
    public string? PaymentReference { get; set; }
    public string? BankName { get; set; }
    public decimal? Amount { get; set; }
    public string? Currency { get; set; }
}

public sealed class CompanySubscriptionPanel
{
    public int CompanyId { get; set; }
    public string CompanyName { get; set; } = string.Empty;
    public DateTime? RegisteredAt { get; set; }
    public bool CompanyLocked { get; set; }
    public List<LocationSubscriptionDetail> Locations { get; set; } = [];
}

public class LocationSubscriptionService(
    ITenantConnectionResolver resolver,
    ILogger<LocationSubscriptionService> logger)
{
    public const int DefaultTrialMonths = 1;

    BisyncDbContext CreateControlDb()
    {
        var options = new DbContextOptionsBuilder<BisyncDbContext>()
            .UseNpgsql(resolver.DefaultOperationalConnection)
            .Options;
        return new BisyncDbContext(options);
    }

    public async Task EnsureSchemaAsync(CancellationToken ct = default)
    {
        await using var db = CreateControlDb();
        await EnsureSchemaAsync(db, ct);
    }

    public static async Task EnsureSchemaAsync(BisyncDbContext db, CancellationToken ct = default)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "LocationSubscriptions" (
                "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CompanyId" INTEGER NOT NULL,
                "LocationExternalId" TEXT NOT NULL DEFAULT '',
                "Status" TEXT NOT NULL DEFAULT 'free-trial',
                "StatusDate" timestamp with time zone NULL,
                "ExpiryDate" timestamp with time zone NULL,
                "SubscribedSince" timestamp with time zone NULL,
                "LastPaymentDate" timestamp with time zone NULL,
                "Amount" NUMERIC(18,2) NULL,
                "Currency" TEXT NOT NULL DEFAULT 'MYR',
                "RenewalDate" timestamp with time zone NULL,
                "YearsRenewed" INTEGER NOT NULL DEFAULT 0,
                "PaymentMethod" TEXT NULL,
                "PaymentReference" TEXT NULL,
                "BankName" TEXT NULL,
                "Active" BOOLEAN NOT NULL DEFAULT TRUE,
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_LocationSubscriptions_CompanyId_LocationExternalId"
                ON "LocationSubscriptions" ("CompanyId", "LocationExternalId");
            """, ct);

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "LocationSubscriptions", "Status", "TEXT NOT NULL DEFAULT 'free-trial'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "LocationSubscriptions", "StatusDate", "timestamp with time zone NULL");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "LocationSubscriptions", "ExpiryDate", "timestamp with time zone NULL");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "LocationSubscriptions", "YearsRenewed", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "LocationSubscriptions", "PaymentMethod", "TEXT NULL");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "LocationSubscriptions", "PaymentReference", "TEXT NULL");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "LocationSubscriptions", "BankName", "TEXT NULL");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "RegisteredAt", "timestamp with time zone NULL");

        // Legacy columns were created as timestamp without time zone; Npgsql rejects DateTime Kind=UTC on those.
        await PromoteTimestampColumnsToTimestamptzAsync(db, ct);
    }

    static async Task PromoteTimestampColumnsToTimestamptzAsync(BisyncDbContext db, CancellationToken ct)
    {
        string[][] columns =
        [
            ["LocationSubscriptions", "StatusDate"],
            ["LocationSubscriptions", "ExpiryDate"],
            ["LocationSubscriptions", "SubscribedSince"],
            ["LocationSubscriptions", "LastPaymentDate"],
            ["LocationSubscriptions", "RenewalDate"],
            ["LocationSubscriptions", "UpdatedAt"],
            ["Companies", "RegisteredAt"],
        ];

        foreach (var pair in columns)
        {
            var table = pair[0];
            var column = pair[1];
            try
            {
                await db.Database.ExecuteSqlRawAsync($"""
                    DO $$
                    BEGIN
                      IF EXISTS (
                        SELECT 1 FROM information_schema.columns
                        WHERE table_schema = 'public'
                          AND table_name = '{table}'
                          AND column_name = '{column}'
                          AND data_type = 'timestamp without time zone'
                      ) THEN
                        EXECUTE format(
                          'ALTER TABLE %I ALTER COLUMN %I TYPE timestamp with time zone USING %I AT TIME ZONE ''UTC''',
                          '{table}', '{column}', '{column}');
                      END IF;
                    END $$;
                    """, ct);
            }
            catch
            {
                // Best-effort upgrade for already-deployed control-plane DBs.
            }
        }
    }

    public static string FormatStatusLabel(string? status, int yearsRenewed)
    {
        return (status ?? LocationSubscription.StatusFreeTrial).Trim().ToLowerInvariant() switch
        {
            LocationSubscription.StatusSubscribed => "Subscribed",
            LocationSubscription.StatusRenewed => yearsRenewed > 0 ? $"Renewed ({yearsRenewed}y)" : "Renewed",
            LocationSubscription.StatusLocked => "Locked",
            _ => "Free Trial",
        };
    }

    public async Task<CompanySubscriptionPanel?> GetCompanyPanelAsync(int companyId, CancellationToken ct = default)
    {
        await using var db = CreateControlDb();
        await EnsureSchemaAsync(db, ct);
        await EnsureDefaultsForCompanyAsync(db, companyId, ct);
        await ApplyExpiryLocksAsync(db, companyId, ct);

        var company = await db.Companies.AsNoTracking().FirstOrDefaultAsync(c => c.Id == companyId, ct);
        if (company is null) return null;

        var locations = await db.Locations.AsNoTracking()
            .Where(l => l.CompanyId == companyId)
            .OrderBy(l => l.Name)
            .ToListAsync(ct);
        var subs = await db.LocationSubscriptions.AsNoTracking()
            .Where(s => s.CompanyId == companyId)
            .ToListAsync(ct);
        var byLoc = subs.ToDictionary(s => s.LocationExternalId, StringComparer.OrdinalIgnoreCase);

        var details = locations.Select(loc =>
        {
            byLoc.TryGetValue(loc.ExternalId, out var sub);
            var status = sub?.Status ?? LocationSubscription.StatusFreeTrial;
            var years = sub?.YearsRenewed ?? 0;
            return new LocationSubscriptionDetail
            {
                LocationExternalId = loc.ExternalId,
                LocationName = loc.Name,
                Status = status,
                StatusLabel = FormatStatusLabel(status, years),
                StatusDate = sub?.StatusDate,
                ExpiryDate = sub?.ExpiryDate ?? sub?.RenewalDate,
                RegisteredAt = company.RegisteredAt,
                YearsRenewed = years,
                Locked = string.Equals(status, LocationSubscription.StatusLocked, StringComparison.OrdinalIgnoreCase),
                PaymentMethod = sub?.PaymentMethod,
                PaymentReference = sub?.PaymentReference,
                BankName = sub?.BankName,
                Amount = sub?.Amount,
                Currency = sub?.Currency,
            };
        }).ToList();

        return new CompanySubscriptionPanel
        {
            CompanyId = company.Id,
            CompanyName = company.Name,
            RegisteredAt = company.RegisteredAt,
            CompanyLocked = !company.Active || details.Count > 0 && details.All(d => d.Locked),
            Locations = details,
        };
    }

    public async Task ExtendFreeTrialAsync(
        int companyId,
        string locationExternalId,
        int months,
        CancellationToken ct = default)
    {
        if (months < 1 || months > 36)
            throw new ArgumentException("Extend Free Trial by 1–36 months.");

        await using var db = CreateControlDb();
        await EnsureSchemaAsync(db, ct);
        var sub = await GetOrCreateAsync(db, companyId, locationExternalId, ct);
        var now = DateTime.UtcNow.Date;
        var baseDate = sub.ExpiryDate?.Date > now ? sub.ExpiryDate.Value.Date : now;
        sub.Status = LocationSubscription.StatusFreeTrial;
        sub.StatusDate = DateTime.UtcNow;
        sub.ExpiryDate = baseDate.AddMonths(months);
        sub.RenewalDate = sub.ExpiryDate;
        sub.Active = true;
        sub.UpdatedAt = DateTime.UtcNow;
        await db.SaveChangesAsync(ct);
        await SyncCompanyLockAsync(db, companyId, ct);
    }

    public async Task ActivateYearSubscriptionAsync(
        int companyId,
        string locationExternalId,
        DateTime commencementDate,
        string paymentMethod,
        string paymentReference,
        string? bankName,
        decimal? amount,
        string? currency,
        CancellationToken ct = default)
    {
        var method = (paymentMethod ?? string.Empty).Trim().ToLowerInvariant();
        if (method is not (LocationSubscription.PaymentCheck or LocationSubscription.PaymentBankTransfer))
            throw new ArgumentException("Payment method must be check or bank-transfer.");

        var reference = (paymentReference ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(reference))
            throw new ArgumentException(
                method == LocationSubscription.PaymentCheck
                    ? "Check number is required."
                    : "Bank transaction detail is required.");

        if (method == LocationSubscription.PaymentBankTransfer && string.IsNullOrWhiteSpace(bankName))
            throw new ArgumentException("Bank name is required for bank transfer.");

        await using var db = CreateControlDb();
        await EnsureSchemaAsync(db, ct);
        var sub = await GetOrCreateAsync(db, companyId, locationExternalId, ct);
        var commence = commencementDate.Kind == DateTimeKind.Unspecified
            ? DateTime.SpecifyKind(commencementDate.Date, DateTimeKind.Utc)
            : commencementDate.ToUniversalTime().Date;
        var wasPaid = string.Equals(sub.Status, LocationSubscription.StatusSubscribed, StringComparison.OrdinalIgnoreCase)
            || string.Equals(sub.Status, LocationSubscription.StatusRenewed, StringComparison.OrdinalIgnoreCase)
            || sub.SubscribedSince is not null;

        if (wasPaid)
        {
            sub.Status = LocationSubscription.StatusRenewed;
            sub.YearsRenewed = Math.Max(0, sub.YearsRenewed) + 1;
        }
        else
        {
            sub.Status = LocationSubscription.StatusSubscribed;
            sub.YearsRenewed = 0;
            sub.SubscribedSince ??= commence;
        }

        sub.StatusDate = DateTime.UtcNow;
        sub.ExpiryDate = commence.AddYears(1);
        sub.RenewalDate = sub.ExpiryDate;
        sub.LastPaymentDate = DateTime.UtcNow.Date;
        sub.PaymentMethod = method;
        sub.PaymentReference = reference;
        sub.BankName = method == LocationSubscription.PaymentBankTransfer
            ? bankName!.Trim()
            : null;
        if (amount is > 0) sub.Amount = amount;
        if (!string.IsNullOrWhiteSpace(currency)) sub.Currency = currency.Trim().ToUpperInvariant();
        sub.Active = true;
        sub.UpdatedAt = DateTime.UtcNow;
        await db.SaveChangesAsync(ct);
        await SyncCompanyLockAsync(db, companyId, ct);
    }

    /// <summary>Flip expired trials/subscriptions to Locked and sync company Active.</summary>
    public async Task ApplyExpiryLocksAsync(BisyncDbContext db, int? companyId = null, CancellationToken ct = default)
    {
        await EnsureSchemaAsync(db, ct);
        var now = DateTime.UtcNow.Date;
        var query = db.LocationSubscriptions.AsQueryable();
        if (companyId is int cid)
            query = query.Where(s => s.CompanyId == cid);

        var rows = await query.ToListAsync(ct);
        var touchedCompanies = new HashSet<int>();
        foreach (var sub in rows)
        {
            var expiry = sub.ExpiryDate ?? sub.RenewalDate;
            if (expiry is null) continue;
            if (expiry.Value.Date >= now) continue;
            if (string.Equals(sub.Status, LocationSubscription.StatusLocked, StringComparison.OrdinalIgnoreCase))
                continue;
            if (string.Equals(sub.Status, LocationSubscription.StatusFreeTrial, StringComparison.OrdinalIgnoreCase)
                || string.Equals(sub.Status, LocationSubscription.StatusSubscribed, StringComparison.OrdinalIgnoreCase)
                || string.Equals(sub.Status, LocationSubscription.StatusRenewed, StringComparison.OrdinalIgnoreCase)
                || sub.Active)
            {
                sub.Status = LocationSubscription.StatusLocked;
                sub.StatusDate = DateTime.UtcNow;
                sub.Active = false;
                sub.UpdatedAt = DateTime.UtcNow;
                touchedCompanies.Add(sub.CompanyId);
            }
        }

        if (touchedCompanies.Count > 0)
            await db.SaveChangesAsync(ct);

        foreach (var id in companyId is int only ? new[] { only } : touchedCompanies.ToArray())
            await SyncCompanyLockAsync(db, id, ct);
    }

    public async Task EnsureDefaultsForAllAsync(BisyncDbContext db, CancellationToken ct = default)
    {
        await EnsureSchemaAsync(db, ct);
        var companyIds = await db.Companies.AsNoTracking().Select(c => c.Id).ToListAsync(ct);
        foreach (var id in companyIds)
            await EnsureDefaultsForCompanyAsync(db, id, ct);
    }

    async Task EnsureDefaultsForCompanyAsync(BisyncDbContext db, int companyId, CancellationToken ct)
    {
        var company = await db.Companies.FirstOrDefaultAsync(c => c.Id == companyId, ct);
        if (company is null) return;

        if (company.RegisteredAt is null)
        {
            var tenantCreated = await db.TenantConnections.AsNoTracking()
                .Where(t => t.CompanyId == companyId)
                .Select(t => (DateTime?)t.CreatedAt)
                .FirstOrDefaultAsync(ct);
            company.RegisteredAt = AsUtc(tenantCreated) ?? DateTime.UtcNow;
            await db.SaveChangesAsync(ct);
        }

        var locations = await db.Locations.AsNoTracking()
            .Where(l => l.CompanyId == companyId)
            .Select(l => l.ExternalId)
            .ToListAsync(ct);
        var existing = await db.LocationSubscriptions
            .Where(s => s.CompanyId == companyId)
            .Select(s => s.LocationExternalId)
            .ToListAsync(ct);
        var existingSet = new HashSet<string>(existing, StringComparer.OrdinalIgnoreCase);
        var registered = AsUtcDate(company.RegisteredAt) ?? DateTime.UtcNow.Date;
        var added = false;
        foreach (var externalId in locations)
        {
            if (string.IsNullOrWhiteSpace(externalId) || existingSet.Contains(externalId))
                continue;
            var key = externalId.Trim();
            existingSet.Add(key);
            db.LocationSubscriptions.Add(new LocationSubscription
            {
                CompanyId = companyId,
                LocationExternalId = key,
                Status = LocationSubscription.StatusFreeTrial,
                StatusDate = registered,
                ExpiryDate = registered.AddMonths(DefaultTrialMonths),
                RenewalDate = registered.AddMonths(DefaultTrialMonths),
                Active = true,
                UpdatedAt = DateTime.UtcNow,
            });
            added = true;
        }

        if (added)
            await db.SaveChangesAsync(ct);
    }

    async Task<LocationSubscription> GetOrCreateAsync(
        BisyncDbContext db,
        int companyId,
        string locationExternalId,
        CancellationToken ct)
    {
        var key = (locationExternalId ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(key))
            throw new ArgumentException("Location is required.");

        var exists = await db.Locations.AsNoTracking()
            .AnyAsync(l => l.CompanyId == companyId && l.ExternalId == key, ct);
        if (!exists)
            throw new ArgumentException("Location not found for this company.");

        var sub = await db.LocationSubscriptions
            .FirstOrDefaultAsync(s => s.CompanyId == companyId && s.LocationExternalId == key, ct);
        if (sub is not null) return sub;

        await EnsureDefaultsForCompanyAsync(db, companyId, ct);
        sub = await db.LocationSubscriptions
            .FirstOrDefaultAsync(s => s.CompanyId == companyId && s.LocationExternalId == key, ct);
        if (sub is not null) return sub;

        sub = new LocationSubscription
        {
            CompanyId = companyId,
            LocationExternalId = key,
            Status = LocationSubscription.StatusFreeTrial,
            StatusDate = DateTime.UtcNow,
            ExpiryDate = DateTime.UtcNow.Date.AddMonths(DefaultTrialMonths),
            RenewalDate = DateTime.UtcNow.Date.AddMonths(DefaultTrialMonths),
            Active = true,
            UpdatedAt = DateTime.UtcNow,
        };
        db.LocationSubscriptions.Add(sub);
        await db.SaveChangesAsync(ct);
        return sub;
    }

    async Task SyncCompanyLockAsync(BisyncDbContext db, int companyId, CancellationToken ct)
    {
        var company = await db.Companies.FirstOrDefaultAsync(c => c.Id == companyId, ct);
        if (company is null) return;

        var locIds = await db.Locations.AsNoTracking()
            .Where(l => l.CompanyId == companyId)
            .Select(l => l.ExternalId)
            .ToListAsync(ct);
        if (locIds.Count == 0) return;

        var subs = await db.LocationSubscriptions.AsNoTracking()
            .Where(s => s.CompanyId == companyId)
            .ToListAsync(ct);
        var byLoc = subs.ToDictionary(s => s.LocationExternalId, StringComparer.OrdinalIgnoreCase);

        var allLocked = locIds.All(id =>
            byLoc.TryGetValue(id, out var sub)
            && string.Equals(sub.Status, LocationSubscription.StatusLocked, StringComparison.OrdinalIgnoreCase));

        // Lock company when every location is locked; unlock when any location is active again.
        if (allLocked && company.Active)
        {
            company.Active = false;
            await db.SaveChangesAsync(ct);
            logger.LogInformation("Company {CompanyId} locked — all location subscriptions expired.", companyId);
        }
        else if (!allLocked && !company.Active)
        {
            // Only auto-unlock when we previously locked for billing; admin may have deactivated for other reasons.
            // If any location is unlocked/active status, restore company Active.
            var anyActive = locIds.Any(id =>
                byLoc.TryGetValue(id, out var sub)
                && !string.Equals(sub.Status, LocationSubscription.StatusLocked, StringComparison.OrdinalIgnoreCase)
                && sub.Active);
            if (anyActive)
            {
                company.Active = true;
                await db.SaveChangesAsync(ct);
                logger.LogInformation("Company {CompanyId} unlocked after subscription reactivation.", companyId);
            }
        }
    }

    public async Task<bool> IsCompanyBillingLockedAsync(int companyId, CancellationToken ct = default)
    {
        await using var db = CreateControlDb();
        await EnsureSchemaAsync(db, ct);
        await ApplyExpiryLocksAsync(db, companyId, ct);
        var company = await db.Companies.AsNoTracking().FirstOrDefaultAsync(c => c.Id == companyId, ct);
        if (company is null) return false;
        if (!company.Active)
        {
            // Distinguish billing lock: all locations locked
            var panel = await GetCompanyPanelAsync(companyId, ct);
            return panel?.CompanyLocked == true;
        }
        return false;
    }

    static DateTime? AsUtc(DateTime? value)
    {
        if (value is null) return null;
        var dt = value.Value;
        return dt.Kind switch
        {
            DateTimeKind.Utc => dt,
            DateTimeKind.Local => dt.ToUniversalTime(),
            _ => DateTime.SpecifyKind(dt, DateTimeKind.Utc),
        };
    }

    static DateTime? AsUtcDate(DateTime? value)
    {
        var utc = AsUtc(value);
        return utc?.Date is DateTime d ? DateTime.SpecifyKind(d, DateTimeKind.Utc) : null;
    }
}
