using System.Globalization;
using Bisync.Api.Data;
using Bisync.Api.Models;
using ClosedXML.Excel;
using Microsoft.EntityFrameworkCore;

namespace Bisync.Api.Services;

/// <summary>
/// Imports the "Weekly Update" sheet from Instant Sales Update.xlsx into Sales Module Client Update rows.
/// </summary>
public class SalesModuleClientUpdateService(
    BisyncDbContext db,
    IHostEnvironment env,
    ILogger<SalesModuleClientUpdateService> logger)
{
    public const string WeeklyUpdateSheetName = "Weekly Update";

    static int _schemaReady;
    static readonly object CacheLock = new();
    static List<SalesModuleClientUpdate>? _listCache;
    static DateTime _listCacheExpiresUtc;
    static readonly TimeSpan ListCacheTtl = TimeSpan.FromMinutes(2);

    public async Task EnsureSchemaAsync(CancellationToken ct = default)
    {
        if (Volatile.Read(ref _schemaReady) == 1)
            return;

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SalesModuleClientUpdates" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SalesModuleClientUpdates" PRIMARY KEY,
                "DateCreated" timestamp with time zone NULL,
                "Hunter" TEXT NOT NULL DEFAULT '',
                "Company" TEXT NOT NULL DEFAULT '',
                "Brand" TEXT NOT NULL DEFAULT '',
                "LocationCount" integer NULL,
                "Status" TEXT NOT NULL DEFAULT '',
                "LastContactDate" timestamp with time zone NULL,
                "ContactPerson" TEXT NOT NULL DEFAULT '',
                "ContactType" TEXT NOT NULL DEFAULT '',
                "Note" TEXT NOT NULL DEFAULT '',
                "FollowUpReminder" timestamp with time zone NULL,
                "Appointment" TEXT NOT NULL DEFAULT '',
                "ImportedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_Hunter"
            ON "SalesModuleClientUpdates" ("Hunter");
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_DateCreated"
            ON "SalesModuleClientUpdates" ("DateCreated");
            """, ct);
        // Case-insensitive hunter lookups without LOWER() on every row.
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_Hunter_Lower"
            ON "SalesModuleClientUpdates" (LOWER("Hunter"));
            """, ct);

        Volatile.Write(ref _schemaReady, 1);
    }

    static void InvalidateListCache()
    {
        lock (CacheLock)
        {
            _listCache = null;
            _listCacheExpiresUtc = default;
        }
    }

    async Task<List<SalesModuleClientUpdate>> GetCachedRowsAsync(CancellationToken ct)
    {
        lock (CacheLock)
        {
            if (_listCache is not null && _listCacheExpiresUtc > DateTime.UtcNow)
                return _listCache;
        }

        await EnsureSchemaAsync(ct);
        var rows = await db.SalesModuleClientUpdates.AsNoTracking()
            .OrderByDescending(r => r.DateCreated)
            .ThenBy(r => r.Brand)
            .ThenBy(r => r.Id)
            .ToListAsync(ct);

        lock (CacheLock)
        {
            _listCache = rows;
            _listCacheExpiresUtc = DateTime.UtcNow.Add(ListCacheTtl);
            return _listCache;
        }
    }

    public async Task<List<object>> ListAsync(string? hunter = null, CancellationToken ct = default)
    {
        var rows = await GetCachedRowsAsync(ct);
        if (!string.IsNullOrWhiteSpace(hunter))
        {
            var key = hunter.Trim().ToLowerInvariant();
            rows = rows.Where(r => r.Hunter.ToLowerInvariant() == key).ToList();
        }

        return rows.ConvertAll(Map);
    }

    public async Task<object> ImportWeeklyUpdateAsync(Stream stream, string? fileName, CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        var rows = ParseWeeklyUpdateSheet(stream);
        if (rows.Count == 0)
            throw new InvalidOperationException(
                $"No data rows found on sheet \"{WeeklyUpdateSheetName}\". Check the workbook has that sheet.");

        await using var tx = await db.Database.BeginTransactionAsync(ct);
        db.SalesModuleClientUpdates.RemoveRange(db.SalesModuleClientUpdates);
        await db.SaveChangesAsync(ct);

        var importedAt = DateTime.UtcNow;
        foreach (var row in rows)
            row.ImportedAt = importedAt;
        db.SalesModuleClientUpdates.AddRange(rows);
        await db.SaveChangesAsync(ct);
        await tx.CommitAsync(ct);
        InvalidateListCache();

        logger.LogInformation(
            "Sales Module Client Update import: {Count} rows from {File}",
            rows.Count,
            fileName ?? "stream");

        return new
        {
            imported = rows.Count,
            sheet = WeeklyUpdateSheetName,
            fileName = fileName ?? string.Empty,
            importedAt,
            messages = new[]
            {
                $"Imported {rows.Count} row(s) from \"{WeeklyUpdateSheetName}\".",
            },
        };
    }

    /// <summary>Seeds Client Update from bundled Instant Sales Update.xlsx when the table is empty.</summary>
    public async Task SeedBundledIfEmptyAsync(CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        if (await db.SalesModuleClientUpdates.AnyAsync(ct))
            return;

        var path = ResolveSeedPath();
        if (path is null)
        {
            logger.LogWarning("Sales Module Client Update seed file not found; skipping seed.");
            return;
        }

        await using var fs = File.OpenRead(path);
        await ImportWeeklyUpdateAsync(fs, Path.GetFileName(path), ct);
        logger.LogInformation("Seeded Sales Module Client Updates from {Path}", path);
    }

    string? ResolveSeedPath()
    {
        var candidates = new[]
        {
            Path.Combine(env.ContentRootPath, "Data", "Seeds", "instant-sales-update.xlsx"),
            Path.Combine(AppContext.BaseDirectory, "Data", "Seeds", "instant-sales-update.xlsx"),
        };
        return candidates.FirstOrDefault(File.Exists);
    }

    public static List<SalesModuleClientUpdate> ParseWeeklyUpdateSheet(Stream stream)
    {
        using var wb = new XLWorkbook(stream);
        var ws = wb.Worksheets.FirstOrDefault(w =>
            w.Name.Equals(WeeklyUpdateSheetName, StringComparison.OrdinalIgnoreCase)
            || w.Name.Equals("WeeklyUpdate", StringComparison.OrdinalIgnoreCase));
        if (ws is null)
            throw new InvalidOperationException(
                $"Workbook must contain a sheet named \"{WeeklyUpdateSheetName}\".");

        var used = ws.RangeUsed();
        if (used is null) return [];

        var headerRow = 1;
        var map = MapHeaders(ws, headerRow, used.ColumnCount());
        if (map.Count == 0)
        {
            // Header might be missing labels — fall back to fixed Instant Sales Update column order.
            map = DefaultColumnMap();
        }

        var rows = new List<SalesModuleClientUpdate>();
        for (var r = headerRow + 1; r <= used.RowCount(); r++)
        {
            var brand = CellText(ws, r, map, "brand");
            var company = CellText(ws, r, map, "company");
            var hunter = CellText(ws, r, map, "hunter");
            if (string.IsNullOrWhiteSpace(brand)
                && string.IsNullOrWhiteSpace(company)
                && string.IsNullOrWhiteSpace(hunter))
                continue;

            rows.Add(new SalesModuleClientUpdate
            {
                DateCreated = CellDate(ws, r, map, "datecreated"),
                Hunter = hunter,
                Company = company,
                Brand = brand,
                LocationCount = CellInt(ws, r, map, "locationcount"),
                Status = CellText(ws, r, map, "status"),
                LastContactDate = CellDate(ws, r, map, "lastcontact"),
                ContactPerson = CellText(ws, r, map, "contactperson"),
                ContactType = CellText(ws, r, map, "contacttype"),
                Note = CellText(ws, r, map, "note"),
                FollowUpReminder = CellDate(ws, r, map, "followup"),
                Appointment = CellAppointment(ws, r, map),
            });
        }

        return rows;
    }

    static Dictionary<string, int> MapHeaders(IXLWorksheet ws, int headerRow, int colCount)
    {
        var map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        for (var c = 1; c <= colCount; c++)
        {
            var raw = ws.Cell(headerRow, c).GetString().Trim();
            if (string.IsNullOrWhiteSpace(raw)) continue;
            var key = NormalizeHeader(raw);
            if (key is null) continue;
            map.TryAdd(key, c);
        }
        return map;
    }

    static Dictionary<string, int> DefaultColumnMap() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["datecreated"] = 1,
        ["hunter"] = 2,
        ["company"] = 3,
        ["brand"] = 4,
        ["locationcount"] = 5,
        ["status"] = 6,
        ["lastcontact"] = 7,
        ["contactperson"] = 8,
        ["contacttype"] = 9,
        ["note"] = 10,
        ["followup"] = 11,
        ["appointment"] = 12,
    };

    static string? NormalizeHeader(string raw)
    {
        var s = raw.Trim().ToLowerInvariant()
            .Replace(".", "")
            .Replace("_", " ");
        while (s.Contains("  ", StringComparison.Ordinal))
            s = s.Replace("  ", " ", StringComparison.Ordinal);

        return s switch
        {
            "date created" or "datecreated" or "created" or "created on" => "datecreated",
            "hunter" or "sales" => "hunter",
            "company" => "company",
            "brand" => "brand",
            "no of location" or "no of locations" or "number of location" or "number of locations"
                or "location count" or "locations" => "locationcount",
            "status" or "current status" => "status",
            "last contact date" or "last contact" or "lastcontact" => "lastcontact",
            "contact person" or "contactperson" => "contactperson",
            "contact type" or "contacttype" => "contacttype",
            "note" or "notes" or "discussion" or "discussion detail" => "note",
            "follow up reminder" or "follow-up reminder" or "follow up" or "followup" => "followup",
            "appointment" or "appointments" => "appointment",
            _ => null,
        };
    }

    static string CellText(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return string.Empty;
        return ws.Cell(row, col).GetString().Trim();
    }

    static DateTime? CellDate(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return null;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return null;
        if (cell.TryGetValue(out DateTime dt))
            return DateTime.SpecifyKind(dt.Date, DateTimeKind.Utc);
        var text = cell.GetString().Trim();
        if (string.IsNullOrWhiteSpace(text)) return null;
        string[] formats =
        [
            "yyyy-MM-dd", "d/M/yyyy", "dd/MM/yyyy", "M/d/yyyy", "MM/dd/yyyy",
            "d MMM yyyy", "dd MMM yyyy", "d MMMM yyyy", "dd MMMM yyyy",
        ];
        if (DateTime.TryParseExact(text, formats, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var exact))
            return DateTime.SpecifyKind(exact.Date, DateTimeKind.Utc);
        if (DateTime.TryParse(text, CultureInfo.GetCultureInfo("en-GB"), DateTimeStyles.AssumeUniversal, out var gb))
            return DateTime.SpecifyKind(gb.Date, DateTimeKind.Utc);
        return null;
    }

    static int? CellInt(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return null;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return null;
        if (cell.TryGetValue(out double d))
        {
            // Excel serial dates sometimes land in location columns — ignore tiny/huge garbage.
            if (d is >= 0 and <= 100_000 && Math.Abs(d - Math.Round(d)) < 0.001)
                return (int)Math.Round(d);
            return null;
        }
        var text = cell.GetString().Trim();
        return int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var n) ? n : null;
    }

    static string CellAppointment(IXLWorksheet ws, int row, Dictionary<string, int> map)
    {
        if (!map.TryGetValue("appointment", out var col)) return string.Empty;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return string.Empty;
        if (cell.TryGetValue(out DateTime dt))
            return dt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        return cell.GetString().Trim();
    }

    public static object Map(SalesModuleClientUpdate r) => new
    {
        r.Id,
        dateCreated = r.DateCreated,
        hunter = r.Hunter,
        company = r.Company,
        brand = r.Brand,
        locationCount = r.LocationCount,
        status = r.Status,
        lastContactDate = r.LastContactDate,
        contactPerson = r.ContactPerson,
        contactType = r.ContactType,
        note = r.Note,
        followUpReminder = r.FollowUpReminder,
        appointment = r.Appointment,
        importedAt = r.ImportedAt,
    };
}
