using System.Globalization;
using Bisync.Api.Data;
using Bisync.Api.Models;
using ClosedXML.Excel;
using Microsoft.EntityFrameworkCore;

namespace Bisync.Api.Services;

/// <summary>
/// Imports the "Weekly Update" sheet from Instant Sales Update.xlsx into Sales Module Client Update rows.
/// </summary>
public class SalesModuleClientUpdateService(
    BisyncDbContext db,
    IHostEnvironment env,
    ILogger<SalesModuleClientUpdateService> logger)
{
    public const string WeeklyUpdateSheetName = "Weekly Update";

    static int _schemaReady;
    static readonly object CacheLock = new();
    static List<SalesModuleClientUpdate>? _listCache;
    static DateTime _listCacheExpiresUtc;
    static readonly TimeSpan ListCacheTtl = TimeSpan.FromMinutes(2);

    public async Task EnsureSchemaAsync(CancellationToken ct = default)
    {
        if (Volatile.Read(ref _schemaReady) == 1)
            return;

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SalesModuleClientUpdates" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SalesModuleClientUpdates" PRIMARY KEY,
                "DateCreated" timestamp with time zone NULL,
                "Hunter" TEXT NOT NULL DEFAULT '',
                "SalesTeamMemberId" integer NULL,
                "Company" TEXT NOT NULL DEFAULT '',
                "Brand" TEXT NOT NULL DEFAULT '',
                "LocationCount" integer NULL,
                "Status" TEXT NOT NULL DEFAULT '',
                "LastContactDate" timestamp with time zone NULL,
                "ContactPerson" TEXT NOT NULL DEFAULT '',
                "ContactType" TEXT NOT NULL DEFAULT '',
                "Note" TEXT NOT NULL DEFAULT '',
                "FollowUpReminder" timestamp with time zone NULL,
                "Appointment" TEXT NOT NULL DEFAULT '',
                "ImportedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """, ct);
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SalesModuleClientUpdates", "SalesTeamMemberId", "INTEGER NULL");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_Hunter"
            ON "SalesModuleClientUpdates" ("Hunter");
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_DateCreated"
            ON "SalesModuleClientUpdates" ("DateCreated");
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_SalesTeamMemberId"
            ON "SalesModuleClientUpdates" ("SalesTeamMemberId");
            """, ct);
        // Case-insensitive hunter lookups without LOWER() on every row.
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_Hunter_Lower"
            ON "SalesModuleClientUpdates" (LOWER("Hunter"));
            """, ct);

        Volatile.Write(ref _schemaReady, 1);
    }

    static void InvalidateListCache()
    {
        lock (CacheLock)
        {
            _listCache = null;
            _listCacheExpiresUtc = default;
        }
    }

    /// <summary>Allow controllers to refresh Client Update list cache after external writes.</summary>
    public void InvalidateListCachePublic() => InvalidateListCache();

    async Task<List<SalesModuleClientUpdate>> GetCachedRowsAsync(CancellationToken ct)
    {
        lock (CacheLock)
        {
            if (_listCache is not null && _listCacheExpiresUtc > DateTime.UtcNow)
                return _listCache;
        }

        await EnsureSchemaAsync(ct);
        var rows = await db.SalesModuleClientUpdates.AsNoTracking()
            .OrderByDescending(r => r.DateCreated)
            .ThenBy(r => r.Brand)
            .ThenBy(r => r.Id)
            .ToListAsync(ct);

        lock (CacheLock)
        {
            _listCache = rows;
            _listCacheExpiresUtc = DateTime.UtcNow.Add(ListCacheTtl);
            return _listCache;
        }
    }

    /// <summary>
    /// Lists Client Update rows for last week (Mon–Sun) plus week-to-date (Mon–today),
    /// using activity date = LastContactDate ?? DateCreated.
    /// Prefer salesTeamMemberId (tagged hunter); hunter string is a fallback / legacy filter.
    /// </summary>
    public async Task<List<object>> ListAsync(
        string? hunter = null,
        int? salesTeamMemberId = null,
        CancellationToken ct = default)
    {
        await EnsureHuntersTaggedAsync(ct);
        var rows = await GetCachedRowsAsync(ct);
        var (from, toInclusive) = ClientUpdateListWindow(DateTime.UtcNow.Date);
        rows = rows.Where(r =>
        {
            var activity = ActivityDate(r);
            return activity.HasValue
                && activity.Value.Date >= from
                && activity.Value.Date <= toInclusive;
        }).ToList();

        if (salesTeamMemberId is > 0)
        {
            var memberId = salesTeamMemberId.Value;
            var member = await db.SalesModuleTeamMembers.AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == memberId, ct);
            var memberName = member?.Name?.Trim() ?? string.Empty;
            rows = rows.Where(r =>
                r.SalesTeamMemberId == memberId
                || (!string.IsNullOrWhiteSpace(memberName)
                    && r.Hunter.Equals(memberName, StringComparison.OrdinalIgnoreCase)))
                .ToList();
        }
        else if (!string.IsNullOrWhiteSpace(hunter))
        {
            var key = hunter.Trim().ToLowerInvariant();
            rows = rows.Where(r => r.Hunter.ToLowerInvariant() == key).ToList();
        }

        return rows.ConvertAll(Map);
    }

    /// <summary>Rematch when any Client Update hunter text is not yet tagged to Sales Team.</summary>
    async Task EnsureHuntersTaggedAsync(CancellationToken ct)
    {
        await EnsureSchemaAsync(ct);
        var needs = await db.SalesModuleClientUpdates.AsNoTracking()
            .AnyAsync(r => r.SalesTeamMemberId == null && r.Hunter != "", ct);
        if (needs)
            await RematchHuntersAsync(ct);
    }

    /// <summary>
    /// Tag Client Update Hunter free-text (from manual Excel upload) to Sales Team members.
    /// Sets SalesTeamMemberId and normalizes Hunter to the team member display name.
    /// </summary>
    public async Task<object> RematchHuntersAsync(CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        var team = await db.SalesModuleTeamMembers.AsNoTracking()
            .Where(m => m.Active)
            .OrderBy(m => m.Name)
            .ToListAsync(ct);
        if (team.Count == 0)
            return new { matched = 0, unmatched = 0, changed = 0, teamMembers = 0, total = 0 };

        var rows = await db.SalesModuleClientUpdates.ToListAsync(ct);
        var changed = 0;

        foreach (var row in rows)
        {
            var member = ResolveTeamMember(team, row.Hunter, row.SalesTeamMemberId);
            if (member is null)
            {
                if (row.SalesTeamMemberId is > 0)
                {
                    row.SalesTeamMemberId = null;
                    changed++;
                }
                continue;
            }

            if (row.SalesTeamMemberId != member.Id || !string.Equals(row.Hunter, member.Name, StringComparison.Ordinal))
            {
                row.SalesTeamMemberId = member.Id;
                row.Hunter = member.Name;
                changed++;
            }
        }

        if (changed > 0)
        {
            await db.SaveChangesAsync(ct);
            InvalidateListCache();
        }

        var matched = rows.Count(r => r.SalesTeamMemberId is > 0);
        var unmatched = rows.Count - matched;
        logger.LogInformation(
            "Client Update hunter rematch: {Changed} updated, {Matched} tagged, {Unmatched} unmatched, {Team} team members",
            changed,
            matched,
            unmatched,
            team.Count);
        return new
        {
            changed,
            matched,
            unmatched,
            total = rows.Count,
            teamMembers = team.Count,
            hunters = team.Select(m => new
            {
                m.Id,
                m.Name,
                count = rows.Count(r => r.SalesTeamMemberId == m.Id),
            }),
        };
    }

    static SalesModuleTeamMember? ResolveTeamMember(
        List<SalesModuleTeamMember> team,
        string? hunter,
        int? existingMemberId)
    {
        if (existingMemberId is > 0)
        {
            var byId = team.FirstOrDefault(m => m.Id == existingMemberId.Value);
            if (byId is not null) return byId;
        }

        var key = (hunter ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(key)) return null;

        return team.FirstOrDefault(m =>
            m.Name.Equals(key, StringComparison.OrdinalIgnoreCase)
            || m.Email.Equals(key, StringComparison.OrdinalIgnoreCase)
            || m.Email.StartsWith(key + "@", StringComparison.OrdinalIgnoreCase));
    }

    /// <summary>
    /// Fill blank identity fields only: DateCreated, Hunter, Company, Brand, LocationCount.
    /// Non-blank existing values are left unchanged.
    /// </summary>
    public async Task<object> PatchBlankFieldsAsync(
        int id,
        DateTime? dateCreated,
        string? hunter,
        string? company,
        string? brand,
        int? locationCount,
        int? salesTeamMemberId = null,
        CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        var row = await db.SalesModuleClientUpdates.FirstOrDefaultAsync(r => r.Id == id, ct)
            ?? throw new InvalidOperationException("Client Update row not found.");

        var changed = false;

        if (!row.DateCreated.HasValue && dateCreated.HasValue)
        {
            row.DateCreated = DateTime.SpecifyKind(dateCreated.Value.Date, DateTimeKind.Utc);
            changed = true;
        }

        // Prefer tagging from Sales Team list when filling blank hunter.
        if (string.IsNullOrWhiteSpace(row.Hunter) || row.SalesTeamMemberId is null or <= 0)
        {
            if (salesTeamMemberId is > 0)
            {
                var member = await db.SalesModuleTeamMembers.AsNoTracking()
                    .FirstOrDefaultAsync(m => m.Id == salesTeamMemberId.Value && m.Active, ct)
                    ?? throw new InvalidOperationException("Sales team member not found.");
                if (string.IsNullOrWhiteSpace(row.Hunter) || row.SalesTeamMemberId != member.Id)
                {
                    row.Hunter = member.Name;
                    row.SalesTeamMemberId = member.Id;
                    changed = true;
                }
            }
            else if (string.IsNullOrWhiteSpace(row.Hunter) && !string.IsNullOrWhiteSpace(hunter))
            {
                var team = await db.SalesModuleTeamMembers.AsNoTracking()
                    .Where(m => m.Active).ToListAsync(ct);
                var member = ResolveTeamMember(team, hunter, null);
                row.Hunter = member?.Name ?? hunter.Trim();
                row.SalesTeamMemberId = member?.Id;
                changed = true;
            }
        }

        if (string.IsNullOrWhiteSpace(row.Company) && !string.IsNullOrWhiteSpace(company))
        {
            row.Company = company.Trim();
            changed = true;
        }

        if (string.IsNullOrWhiteSpace(row.Brand) && !string.IsNullOrWhiteSpace(brand))
        {
            row.Brand = brand.Trim();
            changed = true;
        }

        if (!row.LocationCount.HasValue && locationCount.HasValue)
        {
            if (locationCount.Value < 0)
                throw new InvalidOperationException("No. of Location cannot be negative.");
            row.LocationCount = locationCount.Value;
            changed = true;
        }

        if (!changed)
            return Map(row);

        await db.SaveChangesAsync(ct);
        InvalidateListCache();
        return Map(row);
    }

    /// <summary>
    /// Apply a Sales Diary log to Client Update: update matching Hunter+Company row when found,
    /// otherwise insert a new Client Update row so Overview / Client Update stay in sync.
    /// </summary>
    public async Task<object> ApplyDiaryEntryAsync(
        int salesTeamMemberId,
        string hunterName,
        string activityType,
        string companyName,
        string brandName,
        string locationVisited,
        int? emailsSent,
        IReadOnlyList<string> statuses,
        string contactType,
        DateTime contactDate,
        IReadOnlyList<(string Name, string Position)> contacts,
        string? comment = null,
        CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);

        var hunter = (hunterName ?? string.Empty).Trim();
        var company = (companyName ?? string.Empty).Trim();
        var brand = (brandName ?? string.Empty).Trim();
        var contactDateUtc = DateTime.SpecifyKind(contactDate.Date, DateTimeKind.Utc);
        var isStatusChange = activityType.Equals("StatusChange", StringComparison.OrdinalIgnoreCase);
        var resolvedContactType = isStatusChange
            ? "STATUS UPDATE"
            : (contactType ?? string.Empty).Trim();
        var contactPerson = FormatDiaryContacts(contacts);
        var note = BuildDiaryNote(isStatusChange, statuses, resolvedContactType, locationVisited, emailsSent, comment);
        var statusValue = isStatusChange && statuses.Count > 0
            ? string.Join(", ", statuses)
            : string.Empty;

        SalesModuleClientUpdate? row = null;
        if (!string.IsNullOrWhiteSpace(company) || !string.IsNullOrWhiteSpace(brand))
        {
            var companyKey = company.ToLowerInvariant();
            var brandKey = brand.ToLowerInvariant();
            var hunterKey = hunter.ToLowerInvariant();

            var candidates = await db.SalesModuleClientUpdates
                .Where(r =>
                    (salesTeamMemberId > 0 && r.SalesTeamMemberId == salesTeamMemberId)
                    || (string.IsNullOrWhiteSpace(hunterKey) || r.Hunter.ToLower() == hunterKey))
                .Where(r =>
                    (!string.IsNullOrWhiteSpace(companyKey) && r.Company.ToLower() == companyKey)
                    || (!string.IsNullOrWhiteSpace(brandKey) && r.Brand.ToLower() == brandKey)
                    || (!string.IsNullOrWhiteSpace(companyKey) && r.Brand.ToLower() == companyKey))
                .ToListAsync(ct);

            row = candidates
                .OrderByDescending(r =>
                    !string.IsNullOrWhiteSpace(brandKey)
                    && r.Brand.Equals(brand, StringComparison.OrdinalIgnoreCase) ? 1 : 0)
                .ThenByDescending(r => r.LastContactDate ?? r.DateCreated ?? DateTime.MinValue)
                .ThenByDescending(r => r.Id)
                .FirstOrDefault();
        }

        if (row is null)
        {
            row = new SalesModuleClientUpdate
            {
                DateCreated = contactDateUtc,
                Hunter = hunter,
                SalesTeamMemberId = salesTeamMemberId > 0 ? salesTeamMemberId : null,
                Company = company,
                Brand = brand,
                Status = statusValue,
                LastContactDate = contactDateUtc,
                ContactPerson = contactPerson,
                ContactType = resolvedContactType,
                Note = note,
                ImportedAt = DateTime.UtcNow,
            };
            db.SalesModuleClientUpdates.Add(row);
        }
        else
        {
            if (!row.DateCreated.HasValue)
                row.DateCreated = contactDateUtc;
            if (string.IsNullOrWhiteSpace(row.Hunter) && !string.IsNullOrWhiteSpace(hunter))
                row.Hunter = hunter;
            if (row.SalesTeamMemberId is null && salesTeamMemberId > 0)
                row.SalesTeamMemberId = salesTeamMemberId;
            if (string.IsNullOrWhiteSpace(row.Company) && !string.IsNullOrWhiteSpace(company))
                row.Company = company;
            if (string.IsNullOrWhiteSpace(row.Brand) && !string.IsNullOrWhiteSpace(brand))
                row.Brand = brand;

            row.LastContactDate = contactDateUtc;
            if (!string.IsNullOrWhiteSpace(contactPerson))
                row.ContactPerson = contactPerson;
            if (!string.IsNullOrWhiteSpace(resolvedContactType))
                row.ContactType = resolvedContactType;
            if (!string.IsNullOrWhiteSpace(note))
                row.Note = note;
            if (isStatusChange && !string.IsNullOrWhiteSpace(statusValue))
                row.Status = statusValue;
        }

        await db.SaveChangesAsync(ct);
        InvalidateListCache();
        return Map(row);
    }

    static string FormatDiaryContacts(IReadOnlyList<(string Name, string Position)> contacts)
    {
        if (contacts is null || contacts.Count == 0) return string.Empty;
        return string.Join("; ", contacts
            .Where(c => !string.IsNullOrWhiteSpace(c.Name))
            .Select(c => string.IsNullOrWhiteSpace(c.Position)
                ? c.Name.Trim()
                : $"{c.Name.Trim()} ({c.Position.Trim()})"));
    }

    static string BuildDiaryNote(
        bool isStatusChange,
        IReadOnlyList<string> statuses,
        string contactType,
        string locationVisited,
        int? emailsSent,
        string? comment = null)
    {
        if (isStatusChange)
        {
            var statusText = statuses.Count > 0 ? string.Join(", ", statuses) : "—";
            var baseNote = $"Sales Diary · Status Change · {statusText}";
            var trimmed = (comment ?? string.Empty).Trim();
            return string.IsNullOrWhiteSpace(trimmed) ? baseNote : $"{baseNote} · {trimmed}";
        }

        var parts = new List<string> { "Sales Diary", contactType };
        if (!string.IsNullOrWhiteSpace(locationVisited))
            parts.Add($"Location: {locationVisited.Trim()}");
        if (emailsSent is > 0)
            parts.Add($"{emailsSent} emails sent");
        var meetingNote = (comment ?? string.Empty).Trim();
        if (!string.IsNullOrWhiteSpace(meetingNote))
            parts.Add(meetingNote);
        return string.Join(" · ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    /// <summary>Monday of last week through today (UTC date).</summary>
    public static (DateTime From, DateTime ToInclusive) ClientUpdateListWindow(DateTime utcToday)
    {
        var today = utcToday.Date;
        var thisWeekStart = StartOfWeekMonday(today);
        var lastWeekStart = thisWeekStart.AddDays(-7);
        return (lastWeekStart, today);
    }

    /// <summary>
    /// Available week/month periods derived from Client Update activity dates
    /// (LastContactDate, falling back to DateCreated).
    /// </summary>
    public async Task<object> GetOverviewPeriodsAsync(CancellationToken ct = default)
    {
        await EnsureHuntersTaggedAsync(ct);
        var rows = await GetCachedRowsAsync(ct);
        var dates = rows
            .Select(ActivityDate)
            .Where(d => d.HasValue)
            .Select(d => d!.Value.Date)
            .Distinct()
            .OrderByDescending(d => d)
            .ToList();

        var weekKeys = new HashSet<DateTime>();
        var monthKeys = new HashSet<(int Year, int Month)>();
        foreach (var d in dates)
        {
            weekKeys.Add(StartOfWeekMonday(d));
            monthKeys.Add((d.Year, d.Month));
        }

        var weeks = weekKeys
            .OrderByDescending(w => w)
            .Select(w =>
            {
                var end = w.AddDays(6);
                return new
                {
                    value = w.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
                    weekStart = w,
                    weekEnd = end,
                    label = FormatWeekLabel(w, end),
                };
            })
            .ToList();

        var months = monthKeys
            .OrderByDescending(m => m.Year)
            .ThenByDescending(m => m.Month)
            .Select(m => new
            {
                value = $"{m.Year:D4}-{m.Month:D2}",
                year = m.Year,
                month = m.Month,
                label = new DateTime(m.Year, m.Month, 1, 0, 0, 0, DateTimeKind.Utc)
                    .ToString("MMMM yyyy", CultureInfo.InvariantCulture),
            })
            .ToList();

        return new { weeks, months };
    }

    /// <summary>
    /// Hunter summary for Overview: status changes, interactions (contact), and new leads
    /// for a required week or month period. Always returns every active Sales Team hunter
    /// (zeros when no activity). Optional salesTeamMemberId / companyId still accepted for API compat.
    /// </summary>
    public async Task<object> GetOverviewAsync(
        string view,
        string? weekStart = null,
        int? year = null,
        int? month = null,
        int? salesTeamMemberId = null,
        int? companyId = null,
        CancellationToken ct = default)
    {
        await EnsureHuntersTaggedAsync(ct);
        var mode = (view ?? string.Empty).Trim().ToLowerInvariant();
        if (mode is not ("week" or "month"))
            throw new InvalidOperationException("view must be \"week\" or \"month\".");

        DateTime periodStart;
        DateTime periodEndExclusive;
        string periodKey;
        string periodLabel;

        if (mode == "week")
        {
            if (string.IsNullOrWhiteSpace(weekStart)
                || !DateTime.TryParseExact(
                    weekStart.Trim(),
                    "yyyy-MM-dd",
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                    out var parsed))
            {
                throw new InvalidOperationException("weekStart is required (yyyy-MM-dd, Monday of the week).");
            }

            periodStart = StartOfWeekMonday(parsed.Date);
            periodEndExclusive = periodStart.AddDays(7);
            periodKey = periodStart.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
            periodLabel = FormatWeekLabel(periodStart, periodStart.AddDays(6));
        }
        else
        {
            if (year is null or < 2000 or > 2100 || month is null or < 1 or > 12)
                throw new InvalidOperationException("year and month are required for month view.");

            periodStart = new DateTime(year.Value, month.Value, 1, 0, 0, 0, DateTimeKind.Utc);
            periodEndExclusive = periodStart.AddMonths(1);
            periodKey = $"{year.Value:D4}-{month.Value:D2}";
            periodLabel = periodStart.ToString("MMMM yyyy", CultureInfo.InvariantCulture);
        }

        string? hunterNameFilter = null;
        if (salesTeamMemberId is > 0)
        {
            var member = await db.SalesModuleTeamMembers.AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == salesTeamMemberId.Value, ct);
            if (member is null)
                throw new InvalidOperationException("Sales team member not found.");
            hunterNameFilter = member.Name.Trim();
        }

        string? companyNameFilter = null;
        if (companyId is > 0)
        {
            var company = await db.SalesModuleCompanies.AsNoTracking()
                .FirstOrDefaultAsync(c => c.Id == companyId.Value, ct);
            if (company is null)
                throw new InvalidOperationException("Company not found.");
            if (salesTeamMemberId is > 0)
            {
                var tagged = await db.SalesModuleCompanyMembers.AsNoTracking()
                    .AnyAsync(
                        t => t.SalesModuleCompanyId == companyId.Value
                            && t.SalesTeamMemberId == salesTeamMemberId.Value,
                        ct);
                if (!tagged)
                    throw new InvalidOperationException("Company is not tagged to this Sales Team member.");
            }
            companyNameFilter = company.Name.Trim();
        }

        // Seed every active hunter so Overview always lists the full Sales Team.
        var teamHunters = await db.SalesModuleTeamMembers.AsNoTracking()
            .Where(m => m.Active && m.IsHunter)
            .OrderBy(m => m.Name)
            .ThenBy(m => m.Id)
            .ToListAsync(ct);

        if (salesTeamMemberId is > 0)
            teamHunters = teamHunters.Where(m => m.Id == salesTeamMemberId.Value).ToList();

        var byHunter = new Dictionary<string, HunterTotals>(StringComparer.OrdinalIgnoreCase);
        foreach (var member in teamHunters)
        {
            var name = string.IsNullOrWhiteSpace(member.Name) ? member.Email : member.Name.Trim();
            if (string.IsNullOrWhiteSpace(name)) continue;
            if (!byHunter.ContainsKey(name))
                byHunter[name] = new HunterTotals { Hunter = name };
        }

        var rows = await GetCachedRowsAsync(ct);
        var inPeriod = rows.Where(r =>
        {
            var activity = ActivityDate(r);
            if (!activity.HasValue
                || activity.Value.Date < periodStart
                || activity.Value.Date >= periodEndExclusive)
                return false;

            if (salesTeamMemberId is > 0)
            {
                var hunterOk = r.SalesTeamMemberId == salesTeamMemberId.Value
                    || (!string.IsNullOrWhiteSpace(hunterNameFilter)
                        && r.Hunter.Equals(hunterNameFilter, StringComparison.OrdinalIgnoreCase));
                if (!hunterOk) return false;
            }

            if (!string.IsNullOrWhiteSpace(companyNameFilter))
            {
                var companyOk = r.Company.Equals(companyNameFilter, StringComparison.OrdinalIgnoreCase)
                    || r.Brand.Equals(companyNameFilter, StringComparison.OrdinalIgnoreCase);
                if (!companyOk) return false;
            }

            return true;
        });

        foreach (var row in inPeriod)
        {
            var hunter = string.IsNullOrWhiteSpace(row.Hunter) ? "(Unassigned)" : row.Hunter.Trim();
            if (!byHunter.TryGetValue(hunter, out var totals))
            {
                // Keep unmatched Client Update hunters visible when not filtering to one team member.
                if (salesTeamMemberId is > 0) continue;
                totals = new HunterTotals { Hunter = hunter };
                byHunter[hunter] = totals;
            }

            if (IsStatusChange(row)) totals.StatusChanges++;
            if (IsInteraction(row)) totals.Interactions++;
            if (IsNewLead(row)) totals.NewLeads++;
        }

        var teamOrder = teamHunters
            .Select(m => string.IsNullOrWhiteSpace(m.Name) ? m.Email.Trim() : m.Name.Trim())
            .Where(n => !string.IsNullOrWhiteSpace(n))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var hunters = byHunter.Values
            .OrderBy(h =>
            {
                var idx = teamOrder.FindIndex(n => n.Equals(h.Hunter, StringComparison.OrdinalIgnoreCase));
                return idx < 0 ? int.MaxValue : idx;
            })
            .ThenBy(h => h.Hunter, StringComparer.OrdinalIgnoreCase)
            .Select(h => new
            {
                hunter = h.Hunter,
                statusChanges = h.StatusChanges,
                interactions = h.Interactions,
                newLeads = h.NewLeads,
            })
            .ToList();

        var totalsOut = new
        {
            statusChanges = hunters.Sum(h => h.statusChanges),
            interactions = hunters.Sum(h => h.interactions),
            newLeads = hunters.Sum(h => h.newLeads),
        };

        return new
        {
            view = mode,
            periodKey,
            periodLabel,
            periodStart,
            periodEnd = periodEndExclusive.AddDays(-1),
            salesTeamMemberId = salesTeamMemberId is > 0 ? salesTeamMemberId : null,
            companyId = companyId is > 0 ? companyId : null,
            companyName = companyNameFilter,
            hunters,
            totals = totalsOut,
        };
    }

    sealed class HunterTotals
    {
        public string Hunter { get; set; } = string.Empty;
        public int StatusChanges { get; set; }
        public int Interactions { get; set; }
        public int NewLeads { get; set; }
    }

    static DateTime? ActivityDate(SalesModuleClientUpdate r) =>
        (r.LastContactDate ?? r.DateCreated)?.Date;

    static DateTime StartOfWeekMonday(DateTime date)
    {
        var d = date.Date;
        var diff = ((int)d.DayOfWeek - (int)DayOfWeek.Monday + 7) % 7;
        return DateTime.SpecifyKind(d.AddDays(-diff), DateTimeKind.Utc);
    }

    static string FormatWeekLabel(DateTime start, DateTime end)
    {
        if (start.Year == end.Year && start.Month == end.Month)
        {
            return $"{start.Day}–{end.Day} {start.ToString("MMM yyyy", CultureInfo.InvariantCulture)}";
        }

        if (start.Year == end.Year)
        {
            return $"{start.Day} {start.ToString("MMM", CultureInfo.InvariantCulture)} – {end.Day} {end.ToString("MMM yyyy", CultureInfo.InvariantCulture)}";
        }

        return $"{start.ToString("d MMM yyyy", CultureInfo.InvariantCulture)} – {end.ToString("d MMM yyyy", CultureInfo.InvariantCulture)}";
    }

    static string NormalizeToken(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return string.Empty;
        var s = value.Trim().ToUpperInvariant();
        while (s.Contains("  ", StringComparison.Ordinal))
            s = s.Replace("  ", " ", StringComparison.Ordinal);
        return s;
    }

    /// <summary>Status UPDATED or Contact Type STATUS UPDATE.</summary>
    static bool IsStatusChange(SalesModuleClientUpdate r)
    {
        var status = NormalizeToken(r.Status);
        var contact = NormalizeToken(r.ContactType);
        return status == "UPDATED" || contact == "STATUS UPDATE" || contact.Contains("STATUS UPDATE", StringComparison.Ordinal);
    }

    /// <summary>Any non-empty contact type counts as a client interaction.</summary>
    static bool IsInteraction(SalesModuleClientUpdate r) =>
        !string.IsNullOrWhiteSpace(r.ContactType);

    static bool IsNewLead(SalesModuleClientUpdate r) =>
        NormalizeToken(r.Status) == "LEAD";

    public async Task<object> ImportWeeklyUpdateAsync(Stream stream, string? fileName, CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        var rows = ParseWeeklyUpdateSheet(stream);
        if (rows.Count == 0)
            throw new InvalidOperationException(
                $"No data rows found on sheet \"{WeeklyUpdateSheetName}\". Check the workbook has that sheet.");

        await using var tx = await db.Database.BeginTransactionAsync(ct);
        db.SalesModuleClientUpdates.RemoveRange(db.SalesModuleClientUpdates);
        await db.SaveChangesAsync(ct);

        var importedAt = DateTime.UtcNow;
        foreach (var row in rows)
            row.ImportedAt = importedAt;
        db.SalesModuleClientUpdates.AddRange(rows);
        await db.SaveChangesAsync(ct);
        await tx.CommitAsync(ct);
        InvalidateListCache();

        var rematch = await RematchHuntersAsync(ct);

        logger.LogInformation(
            "Sales Module Client Update import: {Count} rows from {File}",
            rows.Count,
            fileName ?? "stream");

        return new
        {
            imported = rows.Count,
            sheet = WeeklyUpdateSheetName,
            fileName = fileName ?? string.Empty,
            importedAt,
            hunterRematch = rematch,
            messages = new[]
            {
                $"Imported {rows.Count} row(s) from \"{WeeklyUpdateSheetName}\".",
                "Hunter names rematched to Sales Team members where possible.",
            },
        };
    }

    /// <summary>Seeds Client Update from bundled Instant Sales Update.xlsx when the table is empty.</summary>
    public async Task SeedBundledIfEmptyAsync(CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        if (await db.SalesModuleClientUpdates.AnyAsync(ct))
            return;

        var path = ResolveSeedPath();
        if (path is null)
        {
            logger.LogWarning("Sales Module Client Update seed file not found; skipping seed.");
            return;
        }

        await using var fs = File.OpenRead(path);
        await ImportWeeklyUpdateAsync(fs, Path.GetFileName(path), ct);
        logger.LogInformation("Seeded Sales Module Client Updates from {Path}", path);
    }

    string? ResolveSeedPath()
    {
        var candidates = new[]
        {
            Path.Combine(env.ContentRootPath, "Data", "Seeds", "instant-sales-update.xlsx"),
            Path.Combine(AppContext.BaseDirectory, "Data", "Seeds", "instant-sales-update.xlsx"),
        };
        return candidates.FirstOrDefault(File.Exists);
    }

    public static List<SalesModuleClientUpdate> ParseWeeklyUpdateSheet(Stream stream)
    {
        using var wb = new XLWorkbook(stream);
        var ws = wb.Worksheets.FirstOrDefault(w =>
            w.Name.Equals(WeeklyUpdateSheetName, StringComparison.OrdinalIgnoreCase)
            || w.Name.Equals("WeeklyUpdate", StringComparison.OrdinalIgnoreCase));
        if (ws is null)
            throw new InvalidOperationException(
                $"Workbook must contain a sheet named \"{WeeklyUpdateSheetName}\".");

        var used = ws.RangeUsed();
        if (used is null) return [];

        var headerRow = 1;
        var map = MapHeaders(ws, headerRow, used.ColumnCount());
        if (map.Count == 0)
        {
            // Header might be missing labels — fall back to fixed Instant Sales Update column order.
            map = DefaultColumnMap();
        }

        var rows = new List<SalesModuleClientUpdate>();
        for (var r = headerRow + 1; r <= used.RowCount(); r++)
        {
            var brand = CellText(ws, r, map, "brand");
            var company = CellText(ws, r, map, "company");
            var hunter = CellText(ws, r, map, "hunter");
            if (string.IsNullOrWhiteSpace(brand)
                && string.IsNullOrWhiteSpace(company)
                && string.IsNullOrWhiteSpace(hunter))
                continue;

            rows.Add(new SalesModuleClientUpdate
            {
                DateCreated = CellDate(ws, r, map, "datecreated"),
                Hunter = hunter,
                Company = company,
                Brand = brand,
                LocationCount = CellInt(ws, r, map, "locationcount"),
                Status = CellText(ws, r, map, "status"),
                LastContactDate = CellDate(ws, r, map, "lastcontact"),
                ContactPerson = CellText(ws, r, map, "contactperson"),
                ContactType = CellText(ws, r, map, "contacttype"),
                Note = CellText(ws, r, map, "note"),
                FollowUpReminder = CellDate(ws, r, map, "followup"),
                Appointment = CellAppointment(ws, r, map),
            });
        }

        return rows;
    }

    static Dictionary<string, int> MapHeaders(IXLWorksheet ws, int headerRow, int colCount)
    {
        var map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        for (var c = 1; c <= colCount; c++)
        {
            var raw = ws.Cell(headerRow, c).GetString().Trim();
            if (string.IsNullOrWhiteSpace(raw)) continue;
            var key = NormalizeHeader(raw);
            if (key is null) continue;
            map.TryAdd(key, c);
        }
        return map;
    }

    static Dictionary<string, int> DefaultColumnMap() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["datecreated"] = 1,
        ["hunter"] = 2,
        ["company"] = 3,
        ["brand"] = 4,
        ["locationcount"] = 5,
        ["status"] = 6,
        ["lastcontact"] = 7,
        ["contactperson"] = 8,
        ["contacttype"] = 9,
        ["note"] = 10,
        ["followup"] = 11,
        ["appointment"] = 12,
    };

    static string? NormalizeHeader(string raw)
    {
        var s = raw.Trim().ToLowerInvariant()
            .Replace(".", "")
            .Replace("_", " ");
        while (s.Contains("  ", StringComparison.Ordinal))
            s = s.Replace("  ", " ", StringComparison.Ordinal);

        return s switch
        {
            "date created" or "datecreated" or "created" or "created on" => "datecreated",
            "hunter" or "sales" => "hunter",
            "company" => "company",
            "brand" => "brand",
            "no of location" or "no of locations" or "number of location" or "number of locations"
                or "location count" or "locations" => "locationcount",
            "status" or "current status" => "status",
            "last contact date" or "last contact" or "lastcontact" => "lastcontact",
            "contact person" or "contactperson" => "contactperson",
            "contact type" or "contacttype" => "contacttype",
            "note" or "notes" or "discussion" or "discussion detail" => "note",
            "follow up reminder" or "follow-up reminder" or "follow up" or "followup" => "followup",
            "appointment" or "appointments" => "appointment",
            _ => null,
        };
    }

    static string CellText(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return string.Empty;
        return ws.Cell(row, col).GetString().Trim();
    }

    static DateTime? CellDate(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return null;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return null;
        if (cell.TryGetValue(out DateTime dt))
            return DateTime.SpecifyKind(dt.Date, DateTimeKind.Utc);
        var text = cell.GetString().Trim();
        if (string.IsNullOrWhiteSpace(text)) return null;
        string[] formats =
        [
            "yyyy-MM-dd", "d/M/yyyy", "dd/MM/yyyy", "M/d/yyyy", "MM/dd/yyyy",
            "d MMM yyyy", "dd MMM yyyy", "d MMMM yyyy", "dd MMMM yyyy",
        ];
        if (DateTime.TryParseExact(text, formats, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var exact))
            return DateTime.SpecifyKind(exact.Date, DateTimeKind.Utc);
        if (DateTime.TryParse(text, CultureInfo.GetCultureInfo("en-GB"), DateTimeStyles.AssumeUniversal, out var gb))
            return DateTime.SpecifyKind(gb.Date, DateTimeKind.Utc);
        return null;
    }

    static int? CellInt(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return null;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return null;
        if (cell.TryGetValue(out double d))
        {
            // Excel serial dates sometimes land in location columns — ignore tiny/huge garbage.
            if (d is >= 0 and <= 100_000 && Math.Abs(d - Math.Round(d)) < 0.001)
                return (int)Math.Round(d);
            return null;
        }
        var text = cell.GetString().Trim();
        return int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var n) ? n : null;
    }

    static string CellAppointment(IXLWorksheet ws, int row, Dictionary<string, int> map)
    {
        if (!map.TryGetValue("appointment", out var col)) return string.Empty;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return string.Empty;
        if (cell.TryGetValue(out DateTime dt))
            return dt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        return cell.GetString().Trim();
    }

    public static object Map(SalesModuleClientUpdate r) => new
    {
        r.Id,
        dateCreated = r.DateCreated,
        hunter = r.Hunter,
        salesTeamMemberId = r.SalesTeamMemberId,
        company = r.Company,
        brand = r.Brand,
        locationCount = r.LocationCount,
        status = r.Status,
        lastContactDate = r.LastContactDate,
        contactPerson = r.ContactPerson,
        contactType = r.ContactType,
        note = r.Note,
        followUpReminder = r.FollowUpReminder,
        appointment = r.Appointment,
        importedAt = r.ImportedAt,
    };
}
