using System.Globalization;
using Bisync.Api.Data;
using Bisync.Api.Models;
using ClosedXML.Excel;
using Microsoft.EntityFrameworkCore;

namespace Bisync.Api.Services;

/// <summary>
/// Imports Instant Sales Update.xlsx into Sales Module Client Update rows:
/// Weekly Update (activity) + Client DB (customers attached to Sales Team hunters).
/// </summary>
public class SalesModuleClientUpdateService(
    BisyncDbContext db,
    IHostEnvironment env,
    ILogger<SalesModuleClientUpdateService> logger)
{
    public const string WeeklyUpdateSheetName = "Weekly Update";
    public const string ClientDbSheetName = "Client DB";

    static int _schemaReady;
    static readonly object CacheLock = new();
    static List<SalesModuleClientUpdate>? _listCache;
    static DateTime _listCacheExpiresUtc;
    static readonly TimeSpan ListCacheTtl = TimeSpan.FromMinutes(2);

    public async Task EnsureSchemaAsync(CancellationToken ct = default)
    {
        if (Volatile.Read(ref _schemaReady) == 1)
            return;

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SalesModuleClientUpdates" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SalesModuleClientUpdates" PRIMARY KEY,
                "DateCreated" timestamp with time zone NULL,
                "Hunter" TEXT NOT NULL DEFAULT '',
                "SalesTeamMemberId" integer NULL,
                "Company" TEXT NOT NULL DEFAULT '',
                "Brand" TEXT NOT NULL DEFAULT '',
                "LocationCount" integer NULL,
                "Status" TEXT NOT NULL DEFAULT '',
                "LastContactDate" timestamp with time zone NULL,
                "ContactPerson" TEXT NOT NULL DEFAULT '',
                "ContactType" TEXT NOT NULL DEFAULT '',
                "Note" TEXT NOT NULL DEFAULT '',
                "FollowUpReminder" timestamp with time zone NULL,
                "Appointment" TEXT NOT NULL DEFAULT '',
                "ImportedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """, ct);
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SalesModuleClientUpdates", "SalesTeamMemberId", "INTEGER NULL");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_Hunter"
            ON "SalesModuleClientUpdates" ("Hunter");
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_DateCreated"
            ON "SalesModuleClientUpdates" ("DateCreated");
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_SalesTeamMemberId"
            ON "SalesModuleClientUpdates" ("SalesTeamMemberId");
            """, ct);
        // Case-insensitive hunter lookups without LOWER() on every row.
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_SalesModuleClientUpdates_Hunter_Lower"
            ON "SalesModuleClientUpdates" (LOWER("Hunter"));
            """, ct);

        Volatile.Write(ref _schemaReady, 1);
    }

    static void InvalidateListCache()
    {
        lock (CacheLock)
        {
            _listCache = null;
            _listCacheExpiresUtc = default;
        }
    }

    /// <summary>Allow controllers to refresh Client Update list cache after external writes.</summary>
    public void InvalidateListCachePublic() => InvalidateListCache();

    async Task<List<SalesModuleClientUpdate>> GetCachedRowsAsync(CancellationToken ct)
    {
        lock (CacheLock)
        {
            if (_listCache is not null && _listCacheExpiresUtc > DateTime.UtcNow)
                return _listCache;
        }

        await EnsureSchemaAsync(ct);
        var rows = await db.SalesModuleClientUpdates.AsNoTracking()
            .OrderByDescending(r => r.DateCreated)
            .ThenBy(r => r.Brand)
            .ThenBy(r => r.Id)
            .ToListAsync(ct);

        lock (CacheLock)
        {
            _listCache = rows;
            _listCacheExpiresUtc = DateTime.UtcNow.Add(ListCacheTtl);
            return _listCache;
        }
    }

    /// <summary>
    /// Lists Client Update rows.
    /// When <paramref name="salesTeamMemberId"/> is set and view is omitted: all clients attached
    /// to that member (tagged companies + existing rows).
    /// When view is week/month: period rows with a change signal, optionally scoped to a member/hunter.
    /// Activity date = LastContactDate ?? DateCreated.
    /// When view is omitted (and no member), falls back to last week (Mon–Sun) plus week-to-date.
    /// </summary>
    public async Task<List<object>> ListAsync(
        string? hunter = null,
        int? salesTeamMemberId = null,
        string? view = null,
        string? weekStart = null,
        int? year = null,
        int? month = null,
        CancellationToken ct = default)
    {
        await EnsureHuntersTaggedAsync(ct);

        var mode = (view ?? string.Empty).Trim().ToLowerInvariant();

        // Member / hunter without a period → full attached client book (latest interaction first).
        if (mode is not ("week" or "month"))
        {
            if (salesTeamMemberId is > 0)
                return await ListAttachedClientsForMemberAsync(salesTeamMemberId.Value, ct);

            if (!string.IsNullOrWhiteSpace(hunter))
            {
                var hunterKey = hunter.Trim();
                var member = await db.SalesModuleTeamMembers.AsNoTracking()
                    .Where(m => m.Active)
                    .OrderBy(m => m.Name)
                    .ToListAsync(ct);
                var resolved = ResolveTeamMember(member, hunterKey, null);
                if (resolved is not null)
                    return await ListAttachedClientsForMemberAsync(resolved.Id, ct);

                return await ListAllRowsForHunterNameAsync(hunterKey, ct);
            }
        }

        var rows = await GetCachedRowsAsync(ct);

        DateTime fromInclusive;
        DateTime toExclusive;
        if (mode is "week" or "month")
        {
            var period = ResolvePeriod(mode, weekStart, year, month);
            fromInclusive = period.Start;
            toExclusive = period.EndExclusive;
        }
        else
        {
            var (from, toInclusive) = ClientUpdateListWindow(DateTime.UtcNow.Date);
            fromInclusive = from;
            toExclusive = toInclusive.AddDays(1);
        }

        rows = rows.Where(r =>
        {
            var activity = ActivityDate(r);
            if (!activity.HasValue
                || activity.Value.Date < fromInclusive
                || activity.Value.Date >= toExclusive)
                return false;

            // Week/month selection: only rows with actual change activity in the period.
            if (mode is "week" or "month")
                return HasAnyChange(r);

            return true;
        }).ToList();

        if (salesTeamMemberId is > 0)
        {
            var memberId = salesTeamMemberId.Value;
            var member = await db.SalesModuleTeamMembers.AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == memberId, ct);
            var memberName = member?.Name?.Trim() ?? string.Empty;
            rows = rows.Where(r =>
                r.SalesTeamMemberId == memberId
                || (!string.IsNullOrWhiteSpace(memberName)
                    && r.Hunter.Equals(memberName, StringComparison.OrdinalIgnoreCase)))
                .ToList();
        }
        else if (!string.IsNullOrWhiteSpace(hunter))
        {
            var key = hunter.Trim().ToLowerInvariant();
            rows = rows.Where(r => r.Hunter.ToLowerInvariant() == key).ToList();
        }

        return rows.ConvertAll(Map);
    }

    /// <summary>
    /// All clients attached to a Sales Team member: ensure a Client Update row exists for each
    /// tagged company, then return every Client Update row tagged to that member.
    /// </summary>
    async Task<List<object>> ListAttachedClientsForMemberAsync(int memberId, CancellationToken ct)
    {
        var member = await db.SalesModuleTeamMembers.AsNoTracking()
            .FirstOrDefaultAsync(m => m.Id == memberId && m.Active, ct)
            ?? throw new InvalidOperationException("Sales Team member not found.");

        var memberName = string.IsNullOrWhiteSpace(member.Name) ? member.Email.Trim() : member.Name.Trim();
        await EnsureAttachedCompanyClientUpdateRowsAsync(memberId, memberName, ct);

        var rows = await GetCachedRowsAsync(ct);
        return rows
            .Where(r =>
                r.SalesTeamMemberId == memberId
                || (!string.IsNullOrWhiteSpace(memberName)
                    && r.Hunter.Equals(memberName, StringComparison.OrdinalIgnoreCase)))
            // Status changes → interactions → new leads → other; latest activity within each group.
            .OrderBy(OverviewClientSortPriority)
            .ThenByDescending(r => r.LastContactDate ?? r.DateCreated ?? DateTime.MinValue)
            .ThenByDescending(r => r.Id)
            .ThenBy(r => r.Company, StringComparer.OrdinalIgnoreCase)
            .Select(Map)
            .ToList();
    }

    /// <summary>0 = status change, 1 = interaction, 2 = new lead, 3 = other.</summary>
    static int OverviewClientSortPriority(SalesModuleClientUpdate r)
    {
        if (IsStatusChange(r)) return 0;
        if (IsInteraction(r)) return 1;
        if (IsNewLead(r)) return 2;
        return 3;
    }

    /// <summary>
    /// All Client Update rows for a free-text hunter name.
    /// "(Unassigned)" / blank maps to rows with no Sales Team member and empty Hunter text.
    /// </summary>
    async Task<List<object>> ListAllRowsForHunterNameAsync(string hunterName, CancellationToken ct)
    {
        var key = hunterName.Trim();
        var rows = await GetCachedRowsAsync(ct);
        var isUnassigned = IsUnassignedHunterLabel(key);

        IEnumerable<SalesModuleClientUpdate> filtered = isUnassigned
            ? rows.Where(IsUnassignedClientRow)
            : rows.Where(r =>
                r.Hunter.Equals(key, StringComparison.OrdinalIgnoreCase)
                || NormalizePersonToken(r.Hunter) == NormalizePersonToken(key));

        return filtered
            .OrderBy(OverviewClientSortPriority)
            .ThenByDescending(r => r.LastContactDate ?? r.DateCreated ?? DateTime.MinValue)
            .ThenByDescending(r => r.Id)
            .ThenBy(r => r.Company, StringComparer.OrdinalIgnoreCase)
            .Select(Map)
            .ToList();
    }

    internal static bool IsUnassignedHunterLabel(string? hunter) =>
        string.IsNullOrWhiteSpace(hunter)
        || hunter.Trim().Equals("(Unassigned)", StringComparison.OrdinalIgnoreCase)
        || hunter.Trim().Equals("Unassigned", StringComparison.OrdinalIgnoreCase);

    /// <summary>Rows not tagged to a Sales Team member and with blank or Unassigned Hunter free-text.</summary>
    internal static bool IsUnassignedClientRow(SalesModuleClientUpdate r) =>
        r.SalesTeamMemberId is null or <= 0
        && (string.IsNullOrWhiteSpace(r.Hunter) || IsUnassignedHunterLabel(r.Hunter));

    /// <summary>
    /// Create placeholder Client Update rows for Sales Module companies tagged to the member
    /// that do not already have a matching company row for that hunter.
    /// </summary>
    async Task EnsureAttachedCompanyClientUpdateRowsAsync(
        int memberId,
        string memberName,
        CancellationToken ct)
    {
        var companyIds = await db.SalesModuleCompanyMembers.AsNoTracking()
            .Where(t => t.SalesTeamMemberId == memberId)
            .Select(t => t.SalesModuleCompanyId)
            .ToListAsync(ct);
        if (companyIds.Count == 0) return;

        var companies = await db.SalesModuleCompanies.AsNoTracking()
            .Where(c => c.Active && companyIds.Contains(c.Id))
            .OrderBy(c => c.Name)
            .ToListAsync(ct);
        if (companies.Count == 0) return;

        var existing = await db.SalesModuleClientUpdates
            .Where(r => r.SalesTeamMemberId == memberId)
            .Select(r => r.Company)
            .ToListAsync(ct);
        var existingKeys = existing
            .Select(c => (c ?? string.Empty).Trim().ToLowerInvariant())
            .Where(c => c.Length > 0)
            .ToHashSet(StringComparer.Ordinal);

        var added = 0;
        foreach (var company in companies)
        {
            var name = company.Name.Trim();
            if (string.IsNullOrWhiteSpace(name)) continue;
            var key = name.ToLowerInvariant();
            if (!existingKeys.Add(key)) continue;

            db.SalesModuleClientUpdates.Add(new SalesModuleClientUpdate
            {
                DateCreated = DateTime.SpecifyKind(company.CreatedAt.Date, DateTimeKind.Utc),
                Hunter = memberName,
                SalesTeamMemberId = memberId,
                Company = name,
                Brand = string.Empty,
                Status = string.Empty,
                ImportedAt = DateTime.UtcNow,
            });
            added++;
        }

        if (added == 0) return;

        await db.SaveChangesAsync(ct);
        InvalidateListCache();
        logger.LogInformation(
            "Client Update: seeded {Count} attached company row(s) for Sales Team member {MemberId}",
            added,
            memberId);
    }

    /// <summary>Rematch when any Client Update hunter text is not yet tagged to Sales Team.</summary>
    async Task EnsureHuntersTaggedAsync(CancellationToken ct)
    {
        await EnsureSchemaAsync(ct);
        var needs = await db.SalesModuleClientUpdates.AsNoTracking()
            .AnyAsync(r => r.SalesTeamMemberId == null && r.Hunter != "", ct);
        if (needs)
            await RematchHuntersAsync(ct);
    }

    /// <summary>
    /// Tag Client Update Hunter free-text (from manual Excel upload) to Sales Team members.
    /// Sets SalesTeamMemberId and normalizes Hunter to the team member display name.
    /// </summary>
    public async Task<object> RematchHuntersAsync(CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        var team = await db.SalesModuleTeamMembers.AsNoTracking()
            .Where(m => m.Active)
            .OrderBy(m => m.Name)
            .ToListAsync(ct);
        if (team.Count == 0)
            return new { matched = 0, unmatched = 0, changed = 0, teamMembers = 0, total = 0 };

        var rows = await db.SalesModuleClientUpdates.ToListAsync(ct);
        var changed = 0;

        foreach (var row in rows)
        {
            var member = ResolveTeamMember(team, row.Hunter, row.SalesTeamMemberId);
            if (member is null)
            {
                if (row.SalesTeamMemberId is > 0)
                {
                    row.SalesTeamMemberId = null;
                    changed++;
                }
                continue;
            }

            if (row.SalesTeamMemberId != member.Id || !string.Equals(row.Hunter, member.Name, StringComparison.Ordinal))
            {
                row.SalesTeamMemberId = member.Id;
                row.Hunter = member.Name;
                changed++;
            }
        }

        if (changed > 0)
        {
            await db.SaveChangesAsync(ct);
            InvalidateListCache();
        }

        var matched = rows.Count(r => r.SalesTeamMemberId is > 0);
        var unmatched = rows.Count - matched;
        logger.LogInformation(
            "Client Update hunter rematch: {Changed} updated, {Matched} tagged, {Unmatched} unmatched, {Team} team members",
            changed,
            matched,
            unmatched,
            team.Count);
        return new
        {
            changed,
            matched,
            unmatched,
            total = rows.Count,
            teamMembers = team.Count,
            hunters = team.Select(m => new
            {
                m.Id,
                m.Name,
                count = rows.Count(r => r.SalesTeamMemberId == m.Id),
            }),
        };
    }

    /// <summary>
    /// Match Excel Hunter / SALES text to a Sales Team member.
    /// Accepts full name, email, email local-part, or first-name token (e.g. MANFRED → Manfred Wong).
    /// </summary>
    internal static SalesModuleTeamMember? ResolveTeamMember(
        List<SalesModuleTeamMember> team,
        string? hunter,
        int? existingMemberId)
    {
        if (existingMemberId is > 0)
        {
            var byId = team.FirstOrDefault(m => m.Id == existingMemberId.Value);
            if (byId is not null) return byId;
        }

        var key = (hunter ?? string.Empty).Trim();
        if (string.IsNullOrWhiteSpace(key)) return null;
        // Placeholder / header leftovers in Client DB.
        if (key.Equals("SALES", StringComparison.OrdinalIgnoreCase)
            || key.Equals("HUNTER", StringComparison.OrdinalIgnoreCase))
            return null;

        var exact = team.FirstOrDefault(m =>
            m.Name.Equals(key, StringComparison.OrdinalIgnoreCase)
            || m.Email.Equals(key, StringComparison.OrdinalIgnoreCase)
            || m.Email.StartsWith(key + "@", StringComparison.OrdinalIgnoreCase));
        if (exact is not null) return exact;

        var token = NormalizePersonToken(key);
        if (token.Length < 2) return null;

        var matches = team.Where(m =>
        {
            if (NormalizePersonToken(FirstNameToken(m.Name)) == token) return true;
            if (NormalizePersonToken(m.Name) == token) return true;
            var at = m.Email.IndexOf('@');
            var local = at > 0 ? m.Email[..at] : m.Email;
            return NormalizePersonToken(local) == token;
        }).ToList();

        if (matches.Count == 1) return matches[0];
        if (matches.Count > 1)
        {
            var huntersOnly = matches.Where(m => m.IsHunter).ToList();
            if (huntersOnly.Count == 1) return huntersOnly[0];
        }

        return null;
    }

    static string FirstNameToken(string name)
    {
        var parts = name.Trim().Split([' ', '\t'], StringSplitOptions.RemoveEmptyEntries);
        return parts.Length == 0 ? string.Empty : parts[0];
    }

    static string NormalizePersonToken(string value)
    {
        if (string.IsNullOrWhiteSpace(value)) return string.Empty;
        var chars = value.Trim().ToUpperInvariant().Where(char.IsLetterOrDigit).ToArray();
        return new string(chars);
    }

    /// <summary>
    /// Fill blank identity fields only: DateCreated, Hunter, Company, Brand, LocationCount.
    /// Non-blank existing values are left unchanged.
    /// </summary>
    public async Task<object> PatchBlankFieldsAsync(
        int id,
        DateTime? dateCreated,
        string? hunter,
        string? company,
        string? brand,
        int? locationCount,
        int? salesTeamMemberId = null,
        CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        var row = await db.SalesModuleClientUpdates.FirstOrDefaultAsync(r => r.Id == id, ct)
            ?? throw new InvalidOperationException("Client Update row not found.");

        var changed = false;

        if (!row.DateCreated.HasValue && dateCreated.HasValue)
        {
            row.DateCreated = DateTime.SpecifyKind(dateCreated.Value.Date, DateTimeKind.Utc);
            changed = true;
        }

        // Prefer tagging from Sales Team list when filling blank hunter.
        if (string.IsNullOrWhiteSpace(row.Hunter) || row.SalesTeamMemberId is null or <= 0)
        {
            if (salesTeamMemberId is > 0)
            {
                var member = await db.SalesModuleTeamMembers.AsNoTracking()
                    .FirstOrDefaultAsync(m => m.Id == salesTeamMemberId.Value && m.Active, ct)
                    ?? throw new InvalidOperationException("Sales team member not found.");
                if (string.IsNullOrWhiteSpace(row.Hunter) || row.SalesTeamMemberId != member.Id)
                {
                    row.Hunter = member.Name;
                    row.SalesTeamMemberId = member.Id;
                    changed = true;
                }
            }
            else if (string.IsNullOrWhiteSpace(row.Hunter) && !string.IsNullOrWhiteSpace(hunter))
            {
                var team = await db.SalesModuleTeamMembers.AsNoTracking()
                    .Where(m => m.Active).ToListAsync(ct);
                var member = ResolveTeamMember(team, hunter, null);
                row.Hunter = member?.Name ?? hunter.Trim();
                row.SalesTeamMemberId = member?.Id;
                changed = true;
            }
        }

        if (string.IsNullOrWhiteSpace(row.Company) && !string.IsNullOrWhiteSpace(company))
        {
            row.Company = company.Trim();
            changed = true;
        }

        if (string.IsNullOrWhiteSpace(row.Brand) && !string.IsNullOrWhiteSpace(brand))
        {
            row.Brand = brand.Trim();
            changed = true;
        }

        if (!row.LocationCount.HasValue && locationCount.HasValue)
        {
            if (locationCount.Value < 0)
                throw new InvalidOperationException("No. of Location cannot be negative.");
            row.LocationCount = locationCount.Value;
            changed = true;
        }

        if (!changed)
            return Map(row);

        await db.SaveChangesAsync(ct);
        InvalidateListCache();
        return Map(row);
    }

    /// <summary>
    /// Apply a Sales Diary log to Client Update: update matching Hunter+Company row when found,
    /// otherwise insert a new Client Update row so Overview / Client Update stay in sync.
    /// </summary>
    public async Task<object> ApplyDiaryEntryAsync(
        int salesTeamMemberId,
        string hunterName,
        string activityType,
        string companyName,
        string brandName,
        string locationVisited,
        int? emailsSent,
        IReadOnlyList<string> statuses,
        string contactType,
        DateTime contactDate,
        IReadOnlyList<(string Name, string Position)> contacts,
        string? comment = null,
        CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);

        var hunter = (hunterName ?? string.Empty).Trim();
        var company = (companyName ?? string.Empty).Trim();
        var brand = (brandName ?? string.Empty).Trim();
        var contactDateUtc = DateTime.SpecifyKind(contactDate.Date, DateTimeKind.Utc);
        var isStatusChange = activityType.Equals("StatusChange", StringComparison.OrdinalIgnoreCase);
        var resolvedContactType = isStatusChange
            ? "STATUS UPDATE"
            : (contactType ?? string.Empty).Trim();
        var contactPerson = FormatDiaryContacts(contacts);
        var note = BuildDiaryNote(isStatusChange, statuses, resolvedContactType, locationVisited, emailsSent, comment);
        var statusValue = isStatusChange && statuses.Count > 0
            ? string.Join(", ", statuses)
            : string.Empty;

        SalesModuleClientUpdate? row = null;
        if (!string.IsNullOrWhiteSpace(company) || !string.IsNullOrWhiteSpace(brand))
        {
            var companyKey = company.ToLowerInvariant();
            var brandKey = brand.ToLowerInvariant();
            var hunterKey = hunter.ToLowerInvariant();

            var candidates = await db.SalesModuleClientUpdates
                .Where(r =>
                    (salesTeamMemberId > 0 && r.SalesTeamMemberId == salesTeamMemberId)
                    || (string.IsNullOrWhiteSpace(hunterKey) || r.Hunter.ToLower() == hunterKey))
                .Where(r =>
                    (!string.IsNullOrWhiteSpace(companyKey) && r.Company.ToLower() == companyKey)
                    || (!string.IsNullOrWhiteSpace(brandKey) && r.Brand.ToLower() == brandKey)
                    || (!string.IsNullOrWhiteSpace(companyKey) && r.Brand.ToLower() == companyKey))
                .ToListAsync(ct);

            row = candidates
                .OrderByDescending(r =>
                    !string.IsNullOrWhiteSpace(brandKey)
                    && r.Brand.Equals(brand, StringComparison.OrdinalIgnoreCase) ? 1 : 0)
                .ThenByDescending(r => r.LastContactDate ?? r.DateCreated ?? DateTime.MinValue)
                .ThenByDescending(r => r.Id)
                .FirstOrDefault();
        }

        if (row is null)
        {
            row = new SalesModuleClientUpdate
            {
                DateCreated = contactDateUtc,
                Hunter = hunter,
                SalesTeamMemberId = salesTeamMemberId > 0 ? salesTeamMemberId : null,
                Company = company,
                Brand = brand,
                Status = statusValue,
                LastContactDate = contactDateUtc,
                ContactPerson = contactPerson,
                ContactType = resolvedContactType,
                Note = note,
                ImportedAt = DateTime.UtcNow,
            };
            db.SalesModuleClientUpdates.Add(row);
        }
        else
        {
            if (!row.DateCreated.HasValue)
                row.DateCreated = contactDateUtc;
            if (string.IsNullOrWhiteSpace(row.Hunter) && !string.IsNullOrWhiteSpace(hunter))
                row.Hunter = hunter;
            if (row.SalesTeamMemberId is null && salesTeamMemberId > 0)
                row.SalesTeamMemberId = salesTeamMemberId;
            if (string.IsNullOrWhiteSpace(row.Company) && !string.IsNullOrWhiteSpace(company))
                row.Company = company;
            if (string.IsNullOrWhiteSpace(row.Brand) && !string.IsNullOrWhiteSpace(brand))
                row.Brand = brand;

            row.LastContactDate = contactDateUtc;
            if (!string.IsNullOrWhiteSpace(contactPerson))
                row.ContactPerson = contactPerson;
            if (!string.IsNullOrWhiteSpace(resolvedContactType))
                row.ContactType = resolvedContactType;
            if (!string.IsNullOrWhiteSpace(note))
                row.Note = note;
            if (isStatusChange && !string.IsNullOrWhiteSpace(statusValue))
                row.Status = statusValue;
        }

        await db.SaveChangesAsync(ct);
        InvalidateListCache();
        return Map(row);
    }

    static string FormatDiaryContacts(IReadOnlyList<(string Name, string Position)> contacts)
    {
        if (contacts is null || contacts.Count == 0) return string.Empty;
        return string.Join("; ", contacts
            .Where(c => !string.IsNullOrWhiteSpace(c.Name))
            .Select(c => string.IsNullOrWhiteSpace(c.Position)
                ? c.Name.Trim()
                : $"{c.Name.Trim()} ({c.Position.Trim()})"));
    }

    static string BuildDiaryNote(
        bool isStatusChange,
        IReadOnlyList<string> statuses,
        string contactType,
        string locationVisited,
        int? emailsSent,
        string? comment = null)
    {
        if (isStatusChange)
        {
            var statusText = statuses.Count > 0 ? string.Join(", ", statuses) : "—";
            var baseNote = $"Sales Diary · Status Change · {statusText}";
            var trimmed = (comment ?? string.Empty).Trim();
            return string.IsNullOrWhiteSpace(trimmed) ? baseNote : $"{baseNote} · {trimmed}";
        }

        var parts = new List<string> { "Sales Diary", contactType };
        if (!string.IsNullOrWhiteSpace(locationVisited))
            parts.Add($"Location: {locationVisited.Trim()}");
        if (emailsSent is > 0)
            parts.Add($"{emailsSent} emails sent");
        var meetingNote = (comment ?? string.Empty).Trim();
        if (!string.IsNullOrWhiteSpace(meetingNote))
            parts.Add(meetingNote);
        return string.Join(" · ", parts.Where(p => !string.IsNullOrWhiteSpace(p)));
    }

    /// <summary>Monday of last week through today (UTC date).</summary>
    public static (DateTime From, DateTime ToInclusive) ClientUpdateListWindow(DateTime utcToday)
    {
        var today = utcToday.Date;
        var thisWeekStart = StartOfWeekMonday(today);
        var lastWeekStart = thisWeekStart.AddDays(-7);
        return (lastWeekStart, today);
    }

    /// <summary>
    /// Available week/month periods derived from Client Update activity dates
    /// (LastContactDate, falling back to DateCreated).
    /// </summary>
    public async Task<object> GetOverviewPeriodsAsync(CancellationToken ct = default)
    {
        await EnsureHuntersTaggedAsync(ct);
        var rows = await GetCachedRowsAsync(ct);
        var dates = rows
            .Select(ActivityDate)
            .Where(d => d.HasValue)
            .Select(d => d!.Value.Date)
            .Distinct()
            .OrderByDescending(d => d)
            .ToList();

        var weekKeys = new HashSet<DateTime>();
        var monthKeys = new HashSet<(int Year, int Month)>();
        foreach (var d in dates)
        {
            weekKeys.Add(StartOfWeekMonday(d));
            monthKeys.Add((d.Year, d.Month));
        }

        var weeks = weekKeys
            .OrderByDescending(w => w)
            .Select(w =>
            {
                var end = w.AddDays(6);
                return new
                {
                    value = w.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture),
                    weekStart = w,
                    weekEnd = end,
                    label = FormatWeekLabel(w, end),
                };
            })
            .ToList();

        var months = monthKeys
            .OrderByDescending(m => m.Year)
            .ThenByDescending(m => m.Month)
            .Select(m => new
            {
                value = $"{m.Year:D4}-{m.Month:D2}",
                year = m.Year,
                month = m.Month,
                label = new DateTime(m.Year, m.Month, 1, 0, 0, 0, DateTimeKind.Utc)
                    .ToString("MMMM yyyy", CultureInfo.InvariantCulture),
            })
            .ToList();

        return new { weeks, months };
    }

    /// <summary>
    /// Hunter summary for Overview: status changes, interactions (contact), and new leads
    /// for a required week or month period. Always returns every active Sales Team hunter
    /// (zeros when no activity). Optional salesTeamMemberId / companyId still accepted for API compat.
    /// </summary>
    public async Task<object> GetOverviewAsync(
        string view,
        string? weekStart = null,
        int? year = null,
        int? month = null,
        int? salesTeamMemberId = null,
        int? companyId = null,
        CancellationToken ct = default)
    {
        await EnsureHuntersTaggedAsync(ct);
        var mode = (view ?? string.Empty).Trim().ToLowerInvariant();
        if (mode is not ("week" or "month"))
            throw new InvalidOperationException("view must be \"week\" or \"month\".");

        var period = ResolvePeriod(mode, weekStart, year, month);
        var periodStart = period.Start;
        var periodEndExclusive = period.EndExclusive;
        var periodKey = period.Key;
        var periodLabel = period.Label;

        string? hunterNameFilter = null;
        if (salesTeamMemberId is > 0)
        {
            var member = await db.SalesModuleTeamMembers.AsNoTracking()
                .FirstOrDefaultAsync(m => m.Id == salesTeamMemberId.Value, ct);
            if (member is null)
                throw new InvalidOperationException("Sales team member not found.");
            hunterNameFilter = member.Name.Trim();
        }

        string? companyNameFilter = null;
        if (companyId is > 0)
        {
            var company = await db.SalesModuleCompanies.AsNoTracking()
                .FirstOrDefaultAsync(c => c.Id == companyId.Value, ct);
            if (company is null)
                throw new InvalidOperationException("Company not found.");
            if (salesTeamMemberId is > 0)
            {
                var tagged = await db.SalesModuleCompanyMembers.AsNoTracking()
                    .AnyAsync(
                        t => t.SalesModuleCompanyId == companyId.Value
                            && t.SalesTeamMemberId == salesTeamMemberId.Value,
                        ct);
                if (!tagged)
                    throw new InvalidOperationException("Company is not tagged to this Sales Team member.");
            }
            companyNameFilter = company.Name.Trim();
        }

        // Seed every active hunter so Overview always lists the full Sales Team.
        var teamHunters = await db.SalesModuleTeamMembers.AsNoTracking()
            .Where(m => m.Active && m.IsHunter)
            .OrderBy(m => m.Name)
            .ThenBy(m => m.Id)
            .ToListAsync(ct);

        if (salesTeamMemberId is > 0)
            teamHunters = teamHunters.Where(m => m.Id == salesTeamMemberId.Value).ToList();

        var byHunter = new Dictionary<string, HunterTotals>(StringComparer.OrdinalIgnoreCase);
        foreach (var member in teamHunters)
        {
            var name = string.IsNullOrWhiteSpace(member.Name) ? member.Email : member.Name.Trim();
            if (string.IsNullOrWhiteSpace(name)) continue;
            // Ensure company-tagged clients exist as Client Update rows so Total Client matches the detail book.
            await EnsureAttachedCompanyClientUpdateRowsAsync(member.Id, name, ct);
            if (!byHunter.ContainsKey(name))
            {
                byHunter[name] = new HunterTotals
                {
                    Hunter = name,
                    SalesTeamMemberId = member.Id,
                };
            }
        }

        var rows = await GetCachedRowsAsync(ct);

        // Total Client = distinct clients attached to each team member (full book), not period-only.
        foreach (var row in rows)
        {
            HunterTotals? totals = null;
            if (row.SalesTeamMemberId is > 0)
            {
                totals = byHunter.Values.FirstOrDefault(h => h.SalesTeamMemberId == row.SalesTeamMemberId);
            }
            if (totals is null)
            {
                var hunter = string.IsNullOrWhiteSpace(row.Hunter) ? "(Unassigned)" : row.Hunter.Trim();
                if (!byHunter.TryGetValue(hunter, out totals))
                {
                    if (salesTeamMemberId is > 0) continue;
                    totals = new HunterTotals
                    {
                        Hunter = hunter,
                        SalesTeamMemberId = row.SalesTeamMemberId,
                    };
                    byHunter[hunter] = totals;
                }
            }

            if (!string.IsNullOrWhiteSpace(companyNameFilter))
            {
                var companyOk = row.Company.Equals(companyNameFilter, StringComparison.OrdinalIgnoreCase)
                    || row.Brand.Equals(companyNameFilter, StringComparison.OrdinalIgnoreCase);
                if (!companyOk) continue;
            }

            if (salesTeamMemberId is > 0)
            {
                var hunterOk = row.SalesTeamMemberId == salesTeamMemberId.Value
                    || (!string.IsNullOrWhiteSpace(hunterNameFilter)
                        && row.Hunter.Equals(hunterNameFilter, StringComparison.OrdinalIgnoreCase));
                if (!hunterOk) continue;
            }

            var clientKey = ClientKey(row);
            if (clientKey is not null)
                totals.ClientKeys.Add(clientKey);
        }

        var inPeriod = rows.Where(r =>
        {
            var activity = ActivityDate(r);
            if (!activity.HasValue
                || activity.Value.Date < periodStart
                || activity.Value.Date >= periodEndExclusive)
                return false;

            if (salesTeamMemberId is > 0)
            {
                var hunterOk = r.SalesTeamMemberId == salesTeamMemberId.Value
                    || (!string.IsNullOrWhiteSpace(hunterNameFilter)
                        && r.Hunter.Equals(hunterNameFilter, StringComparison.OrdinalIgnoreCase));
                if (!hunterOk) return false;
            }

            if (!string.IsNullOrWhiteSpace(companyNameFilter))
            {
                var companyOk = r.Company.Equals(companyNameFilter, StringComparison.OrdinalIgnoreCase)
                    || r.Brand.Equals(companyNameFilter, StringComparison.OrdinalIgnoreCase);
                if (!companyOk) return false;
            }

            return true;
        });

        foreach (var row in inPeriod)
        {
            var hunter = string.IsNullOrWhiteSpace(row.Hunter) ? "(Unassigned)" : row.Hunter.Trim();
            if (!byHunter.TryGetValue(hunter, out var totals))
            {
                // Keep unmatched Client Update hunters visible when not filtering to one team member.
                if (salesTeamMemberId is > 0) continue;
                totals = new HunterTotals
                {
                    Hunter = hunter,
                    SalesTeamMemberId = row.SalesTeamMemberId,
                };
                byHunter[hunter] = totals;
            }

            if (IsStatusChange(row)) totals.StatusChanges++;
            if (IsInteraction(row)) totals.Interactions++;
            if (IsNewLead(row)) totals.NewLeads++;
        }

        var teamOrder = teamHunters
            .Select(m => string.IsNullOrWhiteSpace(m.Name) ? m.Email.Trim() : m.Name.Trim())
            .Where(n => !string.IsNullOrWhiteSpace(n))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        var hunters = byHunter.Values
            .OrderBy(h =>
            {
                var idx = teamOrder.FindIndex(n => n.Equals(h.Hunter, StringComparison.OrdinalIgnoreCase));
                return idx < 0 ? int.MaxValue : idx;
            })
            .ThenBy(h => h.Hunter, StringComparer.OrdinalIgnoreCase)
            .Select(h => new
            {
                hunter = h.Hunter,
                salesTeamMemberId = h.SalesTeamMemberId is > 0 ? h.SalesTeamMemberId : (int?)null,
                totalClients = h.ClientKeys.Count,
                statusChanges = h.StatusChanges,
                interactions = h.Interactions,
                newLeads = h.NewLeads,
            })
            .ToList();

        var totalsOut = new
        {
            totalClients = hunters.Sum(h => h.totalClients),
            statusChanges = hunters.Sum(h => h.statusChanges),
            interactions = hunters.Sum(h => h.interactions),
            newLeads = hunters.Sum(h => h.newLeads),
        };

        return new
        {
            view = mode,
            periodKey,
            periodLabel,
            periodStart,
            periodEnd = periodEndExclusive.AddDays(-1),
            salesTeamMemberId = salesTeamMemberId is > 0 ? salesTeamMemberId : null,
            companyId = companyId is > 0 ? companyId : null,
            companyName = companyNameFilter,
            hunters,
            totals = totalsOut,
        };
    }

    sealed class HunterTotals
    {
        public string Hunter { get; set; } = string.Empty;
        public int? SalesTeamMemberId { get; set; }
        public HashSet<string> ClientKeys { get; } = new(StringComparer.OrdinalIgnoreCase);
        public int StatusChanges { get; set; }
        public int Interactions { get; set; }
        public int NewLeads { get; set; }
    }

    static string? ClientKey(SalesModuleClientUpdate r)
    {
        if (!string.IsNullOrWhiteSpace(r.Company)) return r.Company.Trim();
        if (!string.IsNullOrWhiteSpace(r.Brand)) return r.Brand.Trim();
        return null;
    }

    static DateTime? ActivityDate(SalesModuleClientUpdate r) =>
        (r.LastContactDate ?? r.DateCreated)?.Date;

    /// <summary>
    /// Row has a change signal: status update, contact/interaction, new lead, or an explicit last-contact date.
    /// </summary>
    static bool HasAnyChange(SalesModuleClientUpdate r) =>
        IsStatusChange(r) || IsInteraction(r) || IsNewLead(r) || r.LastContactDate.HasValue;

    sealed record PeriodWindow(DateTime Start, DateTime EndExclusive, string Key, string Label);

    static PeriodWindow ResolvePeriod(string mode, string? weekStart, int? year, int? month)
    {
        if (mode == "week")
        {
            if (string.IsNullOrWhiteSpace(weekStart)
                || !DateTime.TryParseExact(
                    weekStart.Trim(),
                    "yyyy-MM-dd",
                    CultureInfo.InvariantCulture,
                    DateTimeStyles.AssumeUniversal | DateTimeStyles.AdjustToUniversal,
                    out var parsed))
            {
                throw new InvalidOperationException("weekStart is required (yyyy-MM-dd, Monday of the week).");
            }

            var periodStart = StartOfWeekMonday(parsed.Date);
            var periodEndExclusive = periodStart.AddDays(7);
            var periodKey = periodStart.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
            var periodLabel = FormatWeekLabel(periodStart, periodStart.AddDays(6));
            return new PeriodWindow(periodStart, periodEndExclusive, periodKey, periodLabel);
        }

        if (year is null or < 2000 or > 2100 || month is null or < 1 or > 12)
            throw new InvalidOperationException("year and month are required for month view.");

        var monthStart = new DateTime(year.Value, month.Value, 1, 0, 0, 0, DateTimeKind.Utc);
        return new PeriodWindow(
            monthStart,
            monthStart.AddMonths(1),
            $"{year.Value:D4}-{month.Value:D2}",
            monthStart.ToString("MMMM yyyy", CultureInfo.InvariantCulture));
    }

    static DateTime StartOfWeekMonday(DateTime date)
    {
        var d = date.Date;
        var diff = ((int)d.DayOfWeek - (int)DayOfWeek.Monday + 7) % 7;
        return DateTime.SpecifyKind(d.AddDays(-diff), DateTimeKind.Utc);
    }

    static string FormatWeekLabel(DateTime start, DateTime end)
    {
        if (start.Year == end.Year && start.Month == end.Month)
        {
            return $"{start.Day}–{end.Day} {start.ToString("MMM yyyy", CultureInfo.InvariantCulture)}";
        }

        if (start.Year == end.Year)
        {
            return $"{start.Day} {start.ToString("MMM", CultureInfo.InvariantCulture)} – {end.Day} {end.ToString("MMM yyyy", CultureInfo.InvariantCulture)}";
        }

        return $"{start.ToString("d MMM yyyy", CultureInfo.InvariantCulture)} – {end.ToString("d MMM yyyy", CultureInfo.InvariantCulture)}";
    }

    static string NormalizeToken(string? value)
    {
        if (string.IsNullOrWhiteSpace(value)) return string.Empty;
        var s = value.Trim().ToUpperInvariant();
        while (s.Contains("  ", StringComparison.Ordinal))
            s = s.Replace("  ", " ", StringComparison.Ordinal);
        return s;
    }

    /// <summary>Status UPDATED or Contact Type STATUS UPDATE.</summary>
    static bool IsStatusChange(SalesModuleClientUpdate r)
    {
        var status = NormalizeToken(r.Status);
        var contact = NormalizeToken(r.ContactType);
        return status == "UPDATED" || contact == "STATUS UPDATE" || contact.Contains("STATUS UPDATE", StringComparison.Ordinal);
    }

    /// <summary>Any non-empty contact type counts as a client interaction.</summary>
    static bool IsInteraction(SalesModuleClientUpdate r) =>
        !string.IsNullOrWhiteSpace(r.ContactType);

    static bool IsNewLead(SalesModuleClientUpdate r) =>
        NormalizeToken(r.Status) == "LEAD";

    public async Task<object> ImportWeeklyUpdateAsync(Stream stream, string? fileName, CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        await EnsureSalesCompanySchemaAsync(ct);

        await using var ms = new MemoryStream();
        await stream.CopyToAsync(ms, ct);
        ms.Position = 0;

        var weeklyRows = ParseWeeklyUpdateSheet(ms);
        ms.Position = 0;
        var clientDbRows = ParseClientDbSheet(ms);

        if (weeklyRows.Count == 0 && clientDbRows.Count == 0)
        {
            throw new InvalidOperationException(
                $"No data rows found on \"{WeeklyUpdateSheetName}\" or \"{ClientDbSheetName}\".");
        }

        EnrichWeeklyRowsFromClientDb(weeklyRows, clientDbRows);

        var importedAt = DateTime.UtcNow;
        if (weeklyRows.Count > 0)
        {
            await using var tx = await db.Database.BeginTransactionAsync(ct);
            db.SalesModuleClientUpdates.RemoveRange(db.SalesModuleClientUpdates);
            await db.SaveChangesAsync(ct);

            foreach (var row in weeklyRows)
                row.ImportedAt = importedAt;
            db.SalesModuleClientUpdates.AddRange(weeklyRows);
            await db.SaveChangesAsync(ct);
            await tx.CommitAsync(ct);
            InvalidateListCache();
        }

        var rematch = await RematchHuntersAsync(ct);
        var clientDbWire = await WireClientDbRowsAsync(clientDbRows, importedAt, ct);
        // Rematch again after Client DB rows are inserted with free-text SALES values.
        if (clientDbWire.RowsUpserted > 0)
            rematch = await RematchHuntersAsync(ct);

        var companiesSynced = await SyncCompaniesFromClientUpdatesAsync(ct);

        logger.LogInformation(
            "Sales Module Instant Sales import: weekly={Weekly}, clientDb={ClientDb}, wired={Wired}, companies={Companies}, file={File}",
            weeklyRows.Count,
            clientDbRows.Count,
            clientDbWire.RowsUpserted,
            companiesSynced,
            fileName ?? "stream");

        var messages = new List<string>
        {
            weeklyRows.Count > 0
                ? $"Imported {weeklyRows.Count} row(s) from \"{WeeklyUpdateSheetName}\"."
                : $"No rows on \"{WeeklyUpdateSheetName}\" — kept existing Client Update activity where present.",
            clientDbRows.Count > 0
                ? $"Wired {clientDbWire.RowsUpserted} client(s) from \"{ClientDbSheetName}\" "
                  + $"({clientDbWire.CompaniesCreated} compan{(clientDbWire.CompaniesCreated == 1 ? "y" : "ies")} created, "
                  + $"{clientDbWire.UnmatchedSales} SALES value(s) unmatched to Sales Team)."
                : $"No \"{ClientDbSheetName}\" sheet (or empty) — skipped customer attachment import.",
            $"Hunter rematch: {GetRematchMatched(rematch)} tagged, {GetRematchUnmatched(rematch)} unmatched.",
            $"Company tags synced: {companiesSynced} new link(s).",
        };

        return new
        {
            imported = weeklyRows.Count,
            clientDbRows = clientDbRows.Count,
            clientDbWired = clientDbWire.RowsUpserted,
            companiesCreated = clientDbWire.CompaniesCreated,
            unmatchedSales = clientDbWire.UnmatchedSales,
            companiesSynced,
            sheet = weeklyRows.Count > 0 ? WeeklyUpdateSheetName : ClientDbSheetName,
            fileName = fileName ?? string.Empty,
            importedAt,
            hunterRematch = rematch,
            messages,
        };
    }

    sealed class ClientDbParseRow
    {
        public string Brand { get; set; } = string.Empty;
        public string Company { get; set; } = string.Empty;
        public int? LocationCount { get; set; }
        public string Sales { get; set; } = string.Empty;
        public DateTime? CreatedOn { get; set; }
        public string ContactPerson { get; set; } = string.Empty;
    }

    sealed class ClientDbWireResult
    {
        public int RowsUpserted { get; set; }
        public int CompaniesCreated { get; set; }
        public int UnmatchedSales { get; set; }
    }

    static int GetRematchMatched(object rematch) =>
        rematch.GetType().GetProperty("matched")?.GetValue(rematch) as int? ?? 0;

    static int GetRematchUnmatched(object rematch) =>
        rematch.GetType().GetProperty("unmatched")?.GetValue(rematch) as int? ?? 0;

    static void EnrichWeeklyRowsFromClientDb(
        List<SalesModuleClientUpdate> weeklyRows,
        List<ClientDbParseRow> clientDbRows)
    {
        if (weeklyRows.Count == 0) return;

        var byBrand = clientDbRows
            .Where(r => !string.IsNullOrWhiteSpace(r.Brand) && !string.IsNullOrWhiteSpace(r.Company))
            .GroupBy(r => r.Brand.Trim(), StringComparer.OrdinalIgnoreCase)
            .ToDictionary(g => g.Key, g => g.First(), StringComparer.OrdinalIgnoreCase);

        foreach (var row in weeklyRows)
        {
            if (!string.IsNullOrWhiteSpace(row.Company)) continue;
            if (string.IsNullOrWhiteSpace(row.Brand)) continue;

            if (byBrand.TryGetValue(row.Brand.Trim(), out var dbRow))
                row.Company = dbRow.Company.Trim();
            else
                row.Company = row.Brand.Trim();
        }
    }

    /// <summary>
    /// Attach Client DB customers to Sales Team members: create/tag companies and upsert Client Update rows.
    /// </summary>
    async Task<ClientDbWireResult> WireClientDbRowsAsync(
        List<ClientDbParseRow> clientDbRows,
        DateTime importedAt,
        CancellationToken ct)
    {
        var result = new ClientDbWireResult();
        if (clientDbRows.Count == 0) return result;

        var team = await db.SalesModuleTeamMembers.AsNoTracking()
            .Where(m => m.Active)
            .OrderBy(m => m.Name)
            .ToListAsync(ct);
        if (team.Count == 0)
        {
            result.UnmatchedSales = clientDbRows.Count;
            return result;
        }

        var existing = await db.SalesModuleClientUpdates.ToListAsync(ct);
        var changed = false;

        foreach (var src in clientDbRows)
        {
            var member = ResolveTeamMember(team, src.Sales, null);
            if (member is null)
            {
                result.UnmatchedSales++;
                continue;
            }

            var companyName = !string.IsNullOrWhiteSpace(src.Company)
                ? src.Company.Trim()
                : src.Brand.Trim();
            if (string.IsNullOrWhiteSpace(companyName)) continue;

            var (_, companyCreated) = await FindOrCreateCompanyForMemberAsync(companyName, member.Id, ct);
            if (companyCreated) result.CompaniesCreated++;

            var brand = src.Brand.Trim();

            var row = existing.FirstOrDefault(r =>
                r.SalesTeamMemberId == member.Id
                && (
                    (!string.IsNullOrWhiteSpace(r.Company)
                        && r.Company.Trim().Equals(companyName, StringComparison.OrdinalIgnoreCase))
                    || (!string.IsNullOrWhiteSpace(brand)
                        && !string.IsNullOrWhiteSpace(r.Brand)
                        && r.Brand.Trim().Equals(brand, StringComparison.OrdinalIgnoreCase))
                    || (!string.IsNullOrWhiteSpace(brand)
                        && !string.IsNullOrWhiteSpace(r.Company)
                        && r.Company.Trim().Equals(brand, StringComparison.OrdinalIgnoreCase))
                ));

            // Also match weekly rows that used Brand as Company before Client DB enrich.
            row ??= existing.FirstOrDefault(r =>
                (r.SalesTeamMemberId == member.Id
                    || r.Hunter.Equals(member.Name, StringComparison.OrdinalIgnoreCase)
                    || NormalizePersonToken(r.Hunter) == NormalizePersonToken(src.Sales))
                && !string.IsNullOrWhiteSpace(brand)
                && (
                    r.Brand.Trim().Equals(brand, StringComparison.OrdinalIgnoreCase)
                    || r.Company.Trim().Equals(brand, StringComparison.OrdinalIgnoreCase)
                ));

            if (row is null)
            {
                row = new SalesModuleClientUpdate
                {
                    DateCreated = src.CreatedOn ?? importedAt.Date,
                    Hunter = member.Name,
                    SalesTeamMemberId = member.Id,
                    Company = companyName,
                    Brand = brand,
                    LocationCount = src.LocationCount,
                    ContactPerson = src.ContactPerson,
                    ImportedAt = importedAt,
                };
                db.SalesModuleClientUpdates.Add(row);
                existing.Add(row);
                result.RowsUpserted++;
                changed = true;
                continue;
            }

            var touched = false;
            if (row.SalesTeamMemberId != member.Id)
            {
                row.SalesTeamMemberId = member.Id;
                touched = true;
            }
            if (!string.Equals(row.Hunter, member.Name, StringComparison.Ordinal))
            {
                row.Hunter = member.Name;
                touched = true;
            }
            if (string.IsNullOrWhiteSpace(row.Company)
                || row.Company.Trim().Equals(brand, StringComparison.OrdinalIgnoreCase))
            {
                if (!row.Company.Trim().Equals(companyName, StringComparison.OrdinalIgnoreCase))
                {
                    row.Company = companyName;
                    touched = true;
                }
            }
            if (string.IsNullOrWhiteSpace(row.Brand) && !string.IsNullOrWhiteSpace(brand))
            {
                row.Brand = brand;
                touched = true;
            }
            if (row.LocationCount is null && src.LocationCount is not null)
            {
                row.LocationCount = src.LocationCount;
                touched = true;
            }
            if (string.IsNullOrWhiteSpace(row.ContactPerson) && !string.IsNullOrWhiteSpace(src.ContactPerson))
            {
                row.ContactPerson = src.ContactPerson;
                touched = true;
            }
            if (!row.DateCreated.HasValue && src.CreatedOn.HasValue)
            {
                row.DateCreated = src.CreatedOn;
                touched = true;
            }

            // Count every Client DB customer that is present on this member's book.
            result.RowsUpserted++;
            if (touched) changed = true;
        }

        if (changed)
        {
            await db.SaveChangesAsync(ct);
            InvalidateListCache();
        }

        return result;
    }

    async Task EnsureSalesCompanySchemaAsync(CancellationToken ct)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SalesModuleCompanies" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SalesModuleCompanies" PRIMARY KEY,
                "Name" TEXT NOT NULL DEFAULT '',
                "Active" boolean NOT NULL DEFAULT true,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "CreatedByEmail" TEXT NOT NULL DEFAULT ''
            );
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SalesModuleCompanyMembers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SalesModuleCompanyMembers" PRIMARY KEY,
                "SalesModuleCompanyId" integer NOT NULL,
                "SalesTeamMemberId" integer NOT NULL
            );
            """, ct);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_SalesModuleCompanyMembers_Pair"
            ON "SalesModuleCompanyMembers" ("SalesModuleCompanyId", "SalesTeamMemberId");
            """, ct);
    }

    async Task<(SalesModuleCompany Company, bool Created)> FindOrCreateCompanyForMemberAsync(
        string name,
        int memberId,
        CancellationToken ct)
    {
        var trimmed = name.Trim();
        var existing = await db.SalesModuleCompanies
            .FirstOrDefaultAsync(c => c.Name.ToLower() == trimmed.ToLower(), ct);
        var created = false;
        if (existing is null)
        {
            existing = new SalesModuleCompany
            {
                Name = trimmed,
                Active = true,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow,
            };
            db.SalesModuleCompanies.Add(existing);
            await db.SaveChangesAsync(ct);
            created = true;
        }

        var tagged = await db.SalesModuleCompanyMembers.AnyAsync(
            t => t.SalesModuleCompanyId == existing.Id && t.SalesTeamMemberId == memberId, ct);
        if (!tagged)
        {
            db.SalesModuleCompanyMembers.Add(new SalesModuleCompanyMember
            {
                SalesModuleCompanyId = existing.Id,
                SalesTeamMemberId = memberId,
            });
            await db.SaveChangesAsync(ct);
        }

        return (existing, created);
    }

    /// <summary>
    /// Create/tag Sales Module companies from Client Update rows that already have a SalesTeamMemberId.
    /// Returns number of company↔member pairs ensured (created or already present).
    /// </summary>
    public async Task<int> SyncCompaniesFromClientUpdatesAsync(CancellationToken ct = default)
    {
        await EnsureSalesCompanySchemaAsync(ct);
        var pairs = await db.SalesModuleClientUpdates.AsNoTracking()
            .Where(r => r.SalesTeamMemberId != null && r.SalesTeamMemberId > 0)
            .Select(r => new
            {
                MemberId = r.SalesTeamMemberId!.Value,
                Company = r.Company,
                Brand = r.Brand,
            })
            .ToListAsync(ct);

        var neededPairs = new Dictionary<string, (int MemberId, string Name)>(StringComparer.Ordinal);
        foreach (var row in pairs)
        {
            var name = !string.IsNullOrWhiteSpace(row.Company)
                ? row.Company.Trim()
                : (row.Brand ?? string.Empty).Trim();
            if (string.IsNullOrWhiteSpace(name)) continue;
            neededPairs.TryAdd($"{row.MemberId}\0{name.ToLowerInvariant()}", (row.MemberId, name));
        }

        if (neededPairs.Count == 0) return 0;

        foreach (var (memberId, name) in neededPairs.Values)
            await FindOrCreateCompanyForMemberAsync(name, memberId, ct);

        return neededPairs.Count;
    }

    /// <summary>Seeds Client Update from bundled Instant Sales Update.xlsx when the table is empty.</summary>
    public async Task SeedBundledIfEmptyAsync(CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        if (!await db.SalesModuleClientUpdates.AnyAsync(ct))
        {
            var path = ResolveSeedPath();
            if (path is null)
            {
                logger.LogWarning("Sales Module Client Update seed file not found; skipping seed.");
                return;
            }

            await using var fs = File.OpenRead(path);
            await ImportWeeklyUpdateAsync(fs, Path.GetFileName(path), ct);
            logger.LogInformation("Seeded Sales Module Client Updates from {Path}", path);
            return;
        }

        // Existing Weekly Update rows but customers never wired from Client DB / company tags missing.
        await WireBundledClientDbIfUnattachedAsync(ct);
    }

    /// <summary>
    /// When Client Update activity exists but Sales Team company tags are missing, wire the bundled
    /// Client DB sheet (and rematch hunters) without wiping Weekly Update rows.
    /// </summary>
    public async Task WireBundledClientDbIfUnattachedAsync(CancellationToken ct = default)
    {
        await EnsureSchemaAsync(ct);
        await EnsureSalesCompanySchemaAsync(ct);

        var hasTags = await db.SalesModuleCompanyMembers.AsNoTracking().AnyAsync(ct);
        var hasUntagged = await db.SalesModuleClientUpdates.AsNoTracking()
            .AnyAsync(r => r.SalesTeamMemberId == null && r.Hunter != "", ct);
        if (hasTags && !hasUntagged) return;

        var path = ResolveSeedPath();
        if (path is null) return;

        await using var fs = File.OpenRead(path);
        await using var ms = new MemoryStream();
        await fs.CopyToAsync(ms, ct);
        ms.Position = 0;
        var clientDbRows = ParseClientDbSheet(ms);
        if (clientDbRows.Count == 0) return;

        await RematchHuntersAsync(ct);
        var wire = await WireClientDbRowsAsync(clientDbRows, DateTime.UtcNow, ct);
        await RematchHuntersAsync(ct);
        var synced = await SyncCompaniesFromClientUpdatesAsync(ct);
        logger.LogInformation(
            "Wired bundled Client DB onto existing Client Updates: upserted={Upserted}, companiesSynced={Synced}, unmatchedSales={Unmatched}",
            wire.RowsUpserted,
            synced,
            wire.UnmatchedSales);
    }

    string? ResolveSeedPath()
    {
        var candidates = new[]
        {
            Path.Combine(env.ContentRootPath, "Data", "Seeds", "instant-sales-update.xlsx"),
            Path.Combine(AppContext.BaseDirectory, "Data", "Seeds", "instant-sales-update.xlsx"),
        };
        return candidates.FirstOrDefault(File.Exists);
    }

    public static List<SalesModuleClientUpdate> ParseWeeklyUpdateSheet(Stream stream)
    {
        using var wb = new XLWorkbook(stream);
        var ws = wb.Worksheets.FirstOrDefault(w =>
            w.Name.Equals(WeeklyUpdateSheetName, StringComparison.OrdinalIgnoreCase)
            || w.Name.Equals("WeeklyUpdate", StringComparison.OrdinalIgnoreCase));
        if (ws is null)
            return [];

        var used = ws.RangeUsed();
        if (used is null) return [];

        var headerRow = 1;
        var map = MapHeaders(ws, headerRow, used.ColumnCount());
        if (map.Count == 0)
        {
            // Header might be missing labels — fall back to fixed Instant Sales Update column order.
            map = DefaultColumnMap();
        }

        var rows = new List<SalesModuleClientUpdate>();
        for (var r = headerRow + 1; r <= used.RowCount(); r++)
        {
            var brand = CellText(ws, r, map, "brand");
            var company = CellText(ws, r, map, "company");
            var hunter = CellText(ws, r, map, "hunter");
            if (string.IsNullOrWhiteSpace(brand)
                && string.IsNullOrWhiteSpace(company)
                && string.IsNullOrWhiteSpace(hunter))
                continue;

            rows.Add(new SalesModuleClientUpdate
            {
                DateCreated = CellDate(ws, r, map, "datecreated"),
                Hunter = hunter,
                Company = company,
                Brand = brand,
                LocationCount = CellInt(ws, r, map, "locationcount"),
                Status = CellText(ws, r, map, "status"),
                LastContactDate = CellDate(ws, r, map, "lastcontact"),
                ContactPerson = CellText(ws, r, map, "contactperson"),
                ContactType = CellText(ws, r, map, "contacttype"),
                Note = CellText(ws, r, map, "note"),
                FollowUpReminder = CellDate(ws, r, map, "followup"),
                Appointment = CellAppointment(ws, r, map),
            });
        }

        return rows;
    }

    static List<ClientDbParseRow> ParseClientDbSheet(Stream stream)
    {
        using var wb = new XLWorkbook(stream);
        var ws = wb.Worksheets.FirstOrDefault(w =>
            w.Name.Equals(ClientDbSheetName, StringComparison.OrdinalIgnoreCase)
            || w.Name.Equals("ClientDB", StringComparison.OrdinalIgnoreCase)
            || w.Name.Equals("Client Database", StringComparison.OrdinalIgnoreCase));
        if (ws is null) return [];

        var used = ws.RangeUsed();
        if (used is null) return [];

        var headerRow = 1;
        var map = MapHeaders(ws, headerRow, used.ColumnCount());
        if (!map.ContainsKey("hunter") && !map.ContainsKey("company") && !map.ContainsKey("brand"))
            return [];

        var rows = new List<ClientDbParseRow>();
        for (var r = headerRow + 1; r <= used.RowCount(); r++)
        {
            var brand = CellText(ws, r, map, "brand");
            var company = CellText(ws, r, map, "company");
            var sales = CellText(ws, r, map, "hunter");
            if (string.IsNullOrWhiteSpace(brand)
                && string.IsNullOrWhiteSpace(company)
                && string.IsNullOrWhiteSpace(sales))
                continue;

            rows.Add(new ClientDbParseRow
            {
                Brand = brand,
                Company = company,
                LocationCount = CellInt(ws, r, map, "locationcount"),
                Sales = sales,
                CreatedOn = CellDate(ws, r, map, "datecreated"),
                ContactPerson = CellText(ws, r, map, "contactperson"),
            });
        }

        return rows;
    }

    static Dictionary<string, int> MapHeaders(IXLWorksheet ws, int headerRow, int colCount)
    {
        var map = new Dictionary<string, int>(StringComparer.OrdinalIgnoreCase);
        for (var c = 1; c <= colCount; c++)
        {
            var raw = ws.Cell(headerRow, c).GetString().Trim();
            if (string.IsNullOrWhiteSpace(raw)) continue;
            var key = NormalizeHeader(raw);
            if (key is null) continue;
            map.TryAdd(key, c);
        }
        return map;
    }

    static Dictionary<string, int> DefaultColumnMap() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["datecreated"] = 1,
        ["hunter"] = 2,
        ["company"] = 3,
        ["brand"] = 4,
        ["locationcount"] = 5,
        ["status"] = 6,
        ["lastcontact"] = 7,
        ["contactperson"] = 8,
        ["contacttype"] = 9,
        ["note"] = 10,
        ["followup"] = 11,
        ["appointment"] = 12,
    };

    static string? NormalizeHeader(string raw)
    {
        var s = raw.Trim().ToLowerInvariant()
            .Replace(".", "")
            .Replace("_", " ");
        while (s.Contains("  ", StringComparison.Ordinal))
            s = s.Replace("  ", " ", StringComparison.Ordinal);

        return s switch
        {
            "date created" or "datecreated" or "created" or "created on" => "datecreated",
            "hunter" or "sales" => "hunter",
            "company" => "company",
            "brand" => "brand",
            "no of location" or "no of locations" or "number of location" or "number of locations"
                or "location count" or "locations" => "locationcount",
            "status" or "current status" => "status",
            "last contact date" or "last contact" or "lastcontact" => "lastcontact",
            "contact person" or "contactperson" => "contactperson",
            "contact type" or "contacttype" => "contacttype",
            "note" or "notes" or "discussion" or "discussion detail" => "note",
            "follow up reminder" or "follow-up reminder" or "follow up" or "followup" => "followup",
            "appointment" or "appointments" => "appointment",
            _ => null,
        };
    }

    static string CellText(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return string.Empty;
        return ws.Cell(row, col).GetString().Trim();
    }

    static DateTime? CellDate(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return null;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return null;
        if (cell.TryGetValue(out DateTime dt))
            return DateTime.SpecifyKind(dt.Date, DateTimeKind.Utc);
        var text = cell.GetString().Trim();
        if (string.IsNullOrWhiteSpace(text)) return null;
        string[] formats =
        [
            "yyyy-MM-dd", "d/M/yyyy", "dd/MM/yyyy", "M/d/yyyy", "MM/dd/yyyy",
            "d MMM yyyy", "dd MMM yyyy", "d MMMM yyyy", "dd MMMM yyyy",
        ];
        if (DateTime.TryParseExact(text, formats, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var exact))
            return DateTime.SpecifyKind(exact.Date, DateTimeKind.Utc);
        if (DateTime.TryParse(text, CultureInfo.GetCultureInfo("en-GB"), DateTimeStyles.AssumeUniversal, out var gb))
            return DateTime.SpecifyKind(gb.Date, DateTimeKind.Utc);
        return null;
    }

    static int? CellInt(IXLWorksheet ws, int row, Dictionary<string, int> map, string key)
    {
        if (!map.TryGetValue(key, out var col)) return null;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return null;
        if (cell.TryGetValue(out double d))
        {
            // Excel serial dates sometimes land in location columns — ignore tiny/huge garbage.
            if (d is >= 0 and <= 100_000 && Math.Abs(d - Math.Round(d)) < 0.001)
                return (int)Math.Round(d);
            return null;
        }
        var text = cell.GetString().Trim();
        return int.TryParse(text, NumberStyles.Integer, CultureInfo.InvariantCulture, out var n) ? n : null;
    }

    static string CellAppointment(IXLWorksheet ws, int row, Dictionary<string, int> map)
    {
        if (!map.TryGetValue("appointment", out var col)) return string.Empty;
        var cell = ws.Cell(row, col);
        if (cell.IsEmpty()) return string.Empty;
        if (cell.TryGetValue(out DateTime dt))
            return dt.ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);
        return cell.GetString().Trim();
    }

    public static object Map(SalesModuleClientUpdate r) => new
    {
        r.Id,
        dateCreated = r.DateCreated,
        hunter = r.Hunter,
        salesTeamMemberId = r.SalesTeamMemberId,
        company = r.Company,
        brand = r.Brand,
        locationCount = r.LocationCount,
        status = r.Status,
        lastContactDate = r.LastContactDate,
        contactPerson = r.ContactPerson,
        contactType = r.ContactType,
        note = r.Note,
        followUpReminder = r.FollowUpReminder,
        appointment = r.Appointment,
        importedAt = r.ImportedAt,
    };
}
