--
-- PostgreSQL database dump
--

\restrict VPiRwDE4XcixIu7dhL9a4aMEwgfn1ffuvI4ISf9Rbd6xNSx0adgsddbOIrPIiMu

-- Dumped from database version 17.10
-- Dumped by pg_dump version 17.10

SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

DROP INDEX IF EXISTS public."IX_ArchivedProductProductionLogs_OriginalId";
DROP INDEX IF EXISTS public."IX_ArchivedInventoryPurchases_OriginalId";
DROP INDEX IF EXISTS public."IX_ArchivedInventoryMovements_OriginalId";
DROP INDEX IF EXISTS public."IX_ArchiveRuns_RanAt";
ALTER TABLE IF EXISTS ONLY public."ArchivedProductProductionLogs" DROP CONSTRAINT IF EXISTS "PK_ArchivedProductProductionLogs";
ALTER TABLE IF EXISTS ONLY public."ArchivedInventoryPurchases" DROP CONSTRAINT IF EXISTS "PK_ArchivedInventoryPurchases";
ALTER TABLE IF EXISTS ONLY public."ArchivedInventoryMovements" DROP CONSTRAINT IF EXISTS "PK_ArchivedInventoryMovements";
ALTER TABLE IF EXISTS ONLY public."ArchiveRuns" DROP CONSTRAINT IF EXISTS "PK_ArchiveRuns";
DROP TABLE IF EXISTS public."ArchivedProductProductionLogs";
DROP TABLE IF EXISTS public."ArchivedInventoryPurchases";
DROP TABLE IF EXISTS public."ArchivedInventoryMovements";
DROP TABLE IF EXISTS public."ArchiveRuns";
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ArchiveRuns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ArchiveRuns" (
    "Id" integer NOT NULL,
    "RanAt" timestamp with time zone NOT NULL,
    "ArchiveCutoff" timestamp with time zone NOT NULL,
    "MovementsArchived" integer NOT NULL,
    "PurchasesArchived" integer NOT NULL,
    "ProductionLogsArchived" integer NOT NULL,
    "ConsolidationMovementsCreated" integer NOT NULL,
    "Notes" text NOT NULL
);


--
-- Name: ArchiveRuns_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ArchiveRuns" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ArchiveRuns_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ArchivedInventoryMovements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ArchivedInventoryMovements" (
    "Id" integer NOT NULL,
    "OriginalId" integer NOT NULL,
    "ArchivedAt" timestamp with time zone NOT NULL,
    "ComponentId" text NOT NULL,
    "ComponentName" text NOT NULL,
    "LocationExternalId" text NOT NULL,
    "QtyDelta" numeric NOT NULL,
    "Uom" text NOT NULL,
    "Reason" text NOT NULL,
    "ReferenceType" text NOT NULL,
    "ReferenceId" integer NOT NULL,
    "CompanyId" integer,
    "UnitPrice" numeric NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: ArchivedInventoryMovements_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ArchivedInventoryMovements" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ArchivedInventoryMovements_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ArchivedInventoryPurchases; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ArchivedInventoryPurchases" (
    "Id" integer NOT NULL,
    "OriginalId" integer NOT NULL,
    "ArchivedAt" timestamp with time zone NOT NULL,
    "ComponentId" text NOT NULL,
    "ComponentName" text NOT NULL,
    "Quantity" numeric NOT NULL,
    "Uom" text NOT NULL,
    "UnitPrice" numeric NOT NULL,
    "DateOrdered" date NOT NULL,
    "DateCreatedInStock" timestamp with time zone NOT NULL,
    "PurchaseOrderId" integer NOT NULL,
    "PurchaseOrderItemId" integer NOT NULL,
    "CompanyId" integer,
    "LocationIdsJson" text NOT NULL
);


--
-- Name: ArchivedInventoryPurchases_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ArchivedInventoryPurchases" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ArchivedInventoryPurchases_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ArchivedProductProductionLogs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."ArchivedProductProductionLogs" (
    "Id" integer NOT NULL,
    "OriginalId" integer NOT NULL,
    "ArchivedAt" timestamp with time zone NOT NULL,
    "ProductId" integer NOT NULL,
    "EntryType" text NOT NULL,
    "Quantity" numeric NOT NULL,
    "ProductionDate" text NOT NULL,
    "ExpiryDate" text NOT NULL,
    "BatchNumber" text NOT NULL,
    "LocationIdsJson" text NOT NULL,
    "CompanyId" integer,
    "CreatedAt" timestamp with time zone NOT NULL
);


--
-- Name: ArchivedProductProductionLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."ArchivedProductProductionLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."ArchivedProductProductionLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: ArchiveRuns; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ArchiveRuns" ("Id", "RanAt", "ArchiveCutoff", "MovementsArchived", "PurchasesArchived", "ProductionLogsArchived", "ConsolidationMovementsCreated", "Notes") FROM stdin;
1	2026-07-06 13:44:52.433132+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
2	2026-07-06 14:33:07.369471+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
3	2026-07-06 14:45:33.125718+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
4	2026-07-06 16:16:58.095838+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
5	2026-07-06 19:29:19.980767+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
6	2026-07-06 19:54:33.09834+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
7	2026-07-06 20:14:43.51445+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
8	2026-07-06 20:27:44.371688+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
9	2026-07-06 20:53:03.379499+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
10	2026-07-06 21:40:59.442515+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
11	2026-07-06 22:07:19.813715+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
12	2026-07-06 22:55:17.402038+08	2024-07-06 08:00:00+08	0	0	0	0	No records to archive.
13	2026-07-07 09:56:49.019443+08	2024-07-07 08:00:00+08	0	0	0	0	No records to archive.
14	2026-07-07 10:27:12.18488+08	2024-07-07 08:00:00+08	0	0	0	0	No records to archive.
15	2026-07-08 12:46:32.870395+08	2024-07-08 08:00:00+08	0	0	0	0	No records to archive.
16	2026-07-08 12:51:17.771987+08	2024-07-08 08:00:00+08	0	0	0	0	No records to archive.
17	2026-07-08 16:14:43.564135+08	2024-07-08 08:00:00+08	0	0	0	0	No records to archive.
18	2026-07-08 16:15:27.967406+08	2024-07-08 08:00:00+08	0	0	0	0	No records to archive.
19	2026-07-08 16:19:12.544094+08	2024-07-08 08:00:00+08	0	0	0	0	No records to archive.
20	2026-07-08 16:32:12.884952+08	2024-07-08 08:00:00+08	0	0	0	0	No records to archive.
21	2026-07-08 16:32:56.216889+08	2024-07-08 08:00:00+08	0	0	0	0	No records to archive.
22	2026-07-08 16:35:54.59862+08	2024-07-08 08:00:00+08	0	0	0	0	No records to archive.
23	2026-07-09 09:24:30.600147+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
24	2026-07-09 10:29:57.584999+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
25	2026-07-09 10:59:34.649073+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
26	2026-07-09 11:02:09.986417+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
27	2026-07-09 11:17:48.183553+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
28	2026-07-09 11:25:10.881868+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
29	2026-07-09 11:27:57.488789+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
30	2026-07-09 13:30:55.882346+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
31	2026-07-09 13:35:37.029115+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
32	2026-07-09 14:00:24.7354+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
33	2026-07-09 16:12:14.76807+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
34	2026-07-09 18:24:05.817277+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
35	2026-07-09 18:24:52.811102+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
36	2026-07-09 21:57:47.398844+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
37	2026-07-10 01:17:29.730189+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
38	2026-07-10 01:47:04.109104+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
39	2026-07-10 01:47:34.925208+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
40	2026-07-10 03:28:23.219597+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
41	2026-07-10 03:32:14.217262+08	2024-07-09 08:00:00+08	0	0	0	0	No records to archive.
42	2026-07-10 10:19:58.390124+08	2024-07-10 08:00:00+08	0	0	0	0	No records to archive.
\.


--
-- Data for Name: ArchivedInventoryMovements; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ArchivedInventoryMovements" ("Id", "OriginalId", "ArchivedAt", "ComponentId", "ComponentName", "LocationExternalId", "QtyDelta", "Uom", "Reason", "ReferenceType", "ReferenceId", "CompanyId", "UnitPrice", "CreatedAt") FROM stdin;
\.


--
-- Data for Name: ArchivedInventoryPurchases; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ArchivedInventoryPurchases" ("Id", "OriginalId", "ArchivedAt", "ComponentId", "ComponentName", "Quantity", "Uom", "UnitPrice", "DateOrdered", "DateCreatedInStock", "PurchaseOrderId", "PurchaseOrderItemId", "CompanyId", "LocationIdsJson") FROM stdin;
\.


--
-- Data for Name: ArchivedProductProductionLogs; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public."ArchivedProductProductionLogs" ("Id", "OriginalId", "ArchivedAt", "ProductId", "EntryType", "Quantity", "ProductionDate", "ExpiryDate", "BatchNumber", "LocationIdsJson", "CompanyId", "CreatedAt") FROM stdin;
\.


--
-- Name: ArchiveRuns_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ArchiveRuns_Id_seq"', 42, true);


--
-- Name: ArchivedInventoryMovements_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ArchivedInventoryMovements_Id_seq"', 1, false);


--
-- Name: ArchivedInventoryPurchases_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ArchivedInventoryPurchases_Id_seq"', 1, false);


--
-- Name: ArchivedProductProductionLogs_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public."ArchivedProductProductionLogs_Id_seq"', 1, false);


--
-- Name: ArchiveRuns PK_ArchiveRuns; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ArchiveRuns"
    ADD CONSTRAINT "PK_ArchiveRuns" PRIMARY KEY ("Id");


--
-- Name: ArchivedInventoryMovements PK_ArchivedInventoryMovements; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ArchivedInventoryMovements"
    ADD CONSTRAINT "PK_ArchivedInventoryMovements" PRIMARY KEY ("Id");


--
-- Name: ArchivedInventoryPurchases PK_ArchivedInventoryPurchases; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ArchivedInventoryPurchases"
    ADD CONSTRAINT "PK_ArchivedInventoryPurchases" PRIMARY KEY ("Id");


--
-- Name: ArchivedProductProductionLogs PK_ArchivedProductProductionLogs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."ArchivedProductProductionLogs"
    ADD CONSTRAINT "PK_ArchivedProductProductionLogs" PRIMARY KEY ("Id");


--
-- Name: IX_ArchiveRuns_RanAt; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_ArchiveRuns_RanAt" ON public."ArchiveRuns" USING btree ("RanAt");


--
-- Name: IX_ArchivedInventoryMovements_OriginalId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ArchivedInventoryMovements_OriginalId" ON public."ArchivedInventoryMovements" USING btree ("OriginalId");


--
-- Name: IX_ArchivedInventoryPurchases_OriginalId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ArchivedInventoryPurchases_OriginalId" ON public."ArchivedInventoryPurchases" USING btree ("OriginalId");


--
-- Name: IX_ArchivedProductProductionLogs_OriginalId; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX "IX_ArchivedProductProductionLogs_OriginalId" ON public."ArchivedProductProductionLogs" USING btree ("OriginalId");


--
-- PostgreSQL database dump complete
--

\unrestrict VPiRwDE4XcixIu7dhL9a4aMEwgfn1ffuvI4ISf9Rbd6xNSx0adgsddbOIrPIiMu

