using Bisync.Api.Models;
using Bisync.Api.Services;
using Microsoft.EntityFrameworkCore;

namespace Bisync.Api.Data;

/// <summary>
/// One-time startup migration that:
/// 1) assigns unique 4-letter company codes,
/// 2) sanitizes component names,
/// 3) merges company-level duplicate names,
/// 4) rewrites component IDs to {COMPANY_CODE}-{mixed4},
/// 5) remaps denormalized string references across operational tables.
/// </summary>
public static class ComponentIdentityMigrator
{
    public static async Task ApplyAsync(BisyncDbContext db)
    {
        await EnsureRemapTableAsync(db);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Companies", "Code", "TEXT NOT NULL DEFAULT ''");

        await EnsureCompanyCodesAsync(db);
        await BackfillCatalogCompanyIdsAsync(db);

        // Drop exact-name unique index while normalizing/merging (recreated at end).
        try
        {
            await db.Database.ExecuteSqlRawAsync("""DROP INDEX IF EXISTS "IX_Ingredients_CompanyId_Name";""");
            await db.Database.ExecuteSqlRawAsync("""DROP INDEX IF EXISTS "IX_Ingredients_CompanyId_ComponentId";""");
            await db.Database.ExecuteSqlRawAsync("""DROP INDEX IF EXISTS "IX_Companies_Code";""");
        }
        catch
        {
            // Best-effort; recreate later.
        }

        var componentRows = await db.Ingredients
            .AsNoTracking()
            .Select(i => new { i.ComponentId, i.Name })
            .ToListAsync();

        var remapNeeded = componentRows.Any(i =>
            string.IsNullOrWhiteSpace(i.ComponentId)
            || !ComponentIdentityRules.IsValidComponentId(i.ComponentId));

        var anyUnsanitized = componentRows.Any(i =>
            !string.Equals(i.Name, ComponentIdentityRules.NormalizeName(i.Name), StringComparison.Ordinal));

        if (!remapNeeded && !anyUnsanitized)
        {
            // Still enforce indexes/constraints for fresh installs that already comply.
            await EnsureIndexesAsync(db);
            return;
        }

        await SanitizeNamesAsync(db);
        var mergeMap = await MergeDuplicateNamesAsync(db);
        var idMap = await RewriteComponentIdsAsync(db);

        // Fold merge remaps (victim old id -> keeper old id) into final old->new map.
        foreach (var (victimOldId, keeperOldId) in mergeMap)
        {
            if (idMap.TryGetValue(keeperOldId, out var keeperNewId))
                idMap[victimOldId] = keeperNewId;
            else if (!idMap.ContainsKey(victimOldId))
                idMap[victimOldId] = keeperOldId;
        }

        if (idMap.Count > 0)
            await RemapReferencesAsync(db, idMap);

        await PersistRemapsAsync(db, idMap);
        await EnsureIndexesAsync(db);
    }

    static async Task EnsureRemapTableAsync(BisyncDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ComponentIdRemaps" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ComponentIdRemaps" PRIMARY KEY,
                "CompanyId" INTEGER,
                "OldComponentId" TEXT NOT NULL,
                "NewComponentId" TEXT NOT NULL,
                "MigratedAt" TIMESTAMP NOT NULL DEFAULT NOW()
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_ComponentIdRemaps_OldComponentId"
            ON "ComponentIdRemaps" ("OldComponentId");
            """);
    }

    static async Task EnsureCompanyCodesAsync(BisyncDbContext db)
    {
        var companies = await db.Companies.OrderBy(c => c.Id).ToListAsync();
        var used = companies
            .Where(c => !string.IsNullOrWhiteSpace(c.Code))
            .Select(c => c.Code!)
            .ToList();

        var dirty = false;
        foreach (var company in companies)
        {
            if (company.Code is { Length: ComponentIdentityRules.CompanyCodeLength }
                && company.Code.All(char.IsLetter))
            {
                var normalized = company.Code.ToUpperInvariant();
                if (company.Code != normalized)
                {
                    company.Code = normalized;
                    dirty = true;
                }
                continue;
            }

            var code = ComponentIdentityRules.AllocateUniqueCompanyCode(company.Name, used, company.Id);
            used.Add(code);
            company.Code = code;
            dirty = true;
        }

        if (dirty)
            await db.SaveChangesAsync();

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Companies_Code"
            ON "Companies" (UPPER("Code"))
            WHERE "Code" IS NOT NULL AND TRIM("Code") <> '';
            """);
    }

    static async Task BackfillCatalogCompanyIdsAsync(BisyncDbContext db)
    {
        var defaultCompanyId = await db.Companies
            .OrderBy(c => c.Id)
            .Select(c => (int?)c.Id)
            .FirstOrDefaultAsync();
        if (defaultCompanyId is null)
            return;

        await db.Database.ExecuteSqlInterpolatedAsync($"""
            UPDATE "Ingredients" SET "CompanyId" = {defaultCompanyId.Value} WHERE "CompanyId" IS NULL;
            """);
    }

    static async Task SanitizeNamesAsync(BisyncDbContext db)
    {
        var ingredients = await db.Ingredients.OrderBy(i => i.Id).ToListAsync();
        var dirty = false;
        foreach (var ingredient in ingredients)
        {
            var sanitized = ComponentIdentityRules.NormalizeName(ingredient.Name);
            if (string.IsNullOrWhiteSpace(sanitized))
                sanitized = $"Component {ingredient.Id}";
            if (!string.Equals(ingredient.Name, sanitized, StringComparison.Ordinal))
            {
                ingredient.Name = sanitized;
                ingredient.UpdatedAt = DateTime.UtcNow;
                dirty = true;
            }
        }

        if (dirty)
            await db.SaveChangesAsync();
    }

    /// <summary>
    /// Returns map of victim old ComponentId -> keeper old ComponentId.
    /// </summary>
    static async Task<Dictionary<string, string>> MergeDuplicateNamesAsync(BisyncDbContext db)
    {
        var mergeMap = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var ingredients = await db.Ingredients
            .OrderBy(i => i.Id)
            .ToListAsync();

        var groups = ingredients
            .Where(i => i.CompanyId is int)
            .GroupBy(i => (i.CompanyId!.Value, ComponentIdentityRules.NormalizeNameKey(i.Name)));

        var victims = new List<Ingredient>();
        foreach (var group in groups)
        {
            var ordered = group.OrderBy(i => i.Id).ToList();
            if (ordered.Count < 2)
                continue;

            var keeper = ordered[0];
            foreach (var victim in ordered.Skip(1))
            {
                if (!string.IsNullOrWhiteSpace(victim.ComponentId) && !string.IsNullOrWhiteSpace(keeper.ComponentId))
                    mergeMap[victim.ComponentId] = keeper.ComponentId;

                keeper.Active = keeper.Active || victim.Active;
                keeper.AttachedProducts = Math.Max(keeper.AttachedProducts, victim.AttachedProducts);
                keeper.AttachedVendors = Math.Max(keeper.AttachedVendors, victim.AttachedVendors);
                keeper.UpdatedAt = DateTime.UtcNow;
                victims.Add(victim);
            }
        }

        if (victims.Count > 0)
        {
            // Remap victim IDs to keeper IDs before deleting victims.
            if (mergeMap.Count > 0)
                await RemapReferencesAsync(db, mergeMap);

            db.Ingredients.RemoveRange(victims);
            await db.SaveChangesAsync();
        }

        return mergeMap;
    }

    /// <summary>
    /// Returns map of previous ComponentId -> new ComponentId for remaining ingredients.
    /// </summary>
    static async Task<Dictionary<string, string>> RewriteComponentIdsAsync(BisyncDbContext db)
    {
        var map = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        var companies = await db.Companies.AsNoTracking().ToDictionaryAsync(c => c.Id, c => c.Code ?? "");
        var ingredients = await db.Ingredients.OrderBy(i => i.Id).ToListAsync();

        var assignedByCompany = ingredients
            .Where(i => i.CompanyId is int)
            .GroupBy(i => i.CompanyId!.Value)
            .ToDictionary(
                g => g.Key,
                g => g.Select(i => i.ComponentId).Where(id => !string.IsNullOrWhiteSpace(id)).ToList());

        foreach (var ingredient in ingredients)
        {
            if (ingredient.CompanyId is not int companyId)
                continue;
            if (!companies.TryGetValue(companyId, out var code) || string.IsNullOrWhiteSpace(code))
                continue;

            var oldId = ingredient.ComponentId ?? string.Empty;
            if (ComponentIdentityRules.IsValidComponentId(oldId, code))
            {
                // Already compliant for this company; still record identity remap for name sync.
                continue;
            }

            assignedByCompany.TryGetValue(companyId, out var existing);
            existing ??= [];
            var suffix = ComponentIdentityRules.GenerateSuffix(existing, code);
            var newId = ComponentIdentityRules.BuildComponentId(code, suffix);
            existing.Add(newId);
            assignedByCompany[companyId] = existing;

            if (!string.IsNullOrWhiteSpace(oldId))
                map[oldId] = newId;
            ingredient.ComponentId = newId;
            ingredient.UpdatedAt = DateTime.UtcNow;
        }

        if (map.Count > 0)
            await db.SaveChangesAsync();

        return map;
    }

    static async Task RemapReferencesAsync(BisyncDbContext db, Dictionary<string, string> idMap)
    {
        // Distinct deterministic remaps; skip no-ops.
        var pairs = idMap
            .Where(kv => !string.IsNullOrWhiteSpace(kv.Key)
                         && !string.IsNullOrWhiteSpace(kv.Value)
                         && !string.Equals(kv.Key, kv.Value, StringComparison.OrdinalIgnoreCase))
            .GroupBy(kv => kv.Key, StringComparer.OrdinalIgnoreCase)
            .Select(g => (OldId: g.Key, NewId: g.Last().Value))
            .ToList();

        foreach (var (oldId, newId) in pairs)
        {
            await UpdateComponentIdColumnAsync(db, "PurchaseOrderItems", "ComponentId", oldId, newId);
            await UpdateComponentIdColumnAsync(db, "InventoryPurchases", "ComponentId", oldId, newId);
            await UpdateComponentIdColumnAsync(db, "CashPurchases", "ComponentId", oldId, newId);
            await UpdateComponentIdColumnAsync(db, "OrderTemplateItems", "ComponentId", oldId, newId);
            await UpdateComponentIdColumnAsync(db, "InventoryMovements", "ComponentId", oldId, newId);
            await UpdateComponentIdColumnAsync(db, "SampleRequests", "IngredientComponentId", oldId, newId);
            await UpdateComponentIdColumnAsync(db, "QuoteRequestLines", "ComponentExternalId", oldId, newId);

            // Recipe/packaging rows: only rewrite ingredient codes (never product numeric IDs unless exact string match on old ingredient ID).
            await UpdateComponentIdColumnAsync(db, "ProductComponentItems", "ComponentId", oldId, newId);
            await UpdateComponentIdColumnAsync(db, "ProductPackagingItems", "ComponentId", oldId, newId);

            await UpdatePolymorphicItemKeyAsync(db, "WastageEntries", oldId, newId);
            await UpdatePolymorphicItemKeyAsync(db, "TransferEntries", oldId, newId);
            await UpdatePolymorphicItemKeyAsync(db, "InventoryCountSessionLines", oldId, newId);
        }

        // Sync denormalized names from the live Ingredients table where ComponentId matches.
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "PurchaseOrderItems" poi
            SET "ComponentName" = i."Name"
            FROM "Ingredients" i
            WHERE poi."ComponentId" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "InventoryPurchases" ip
            SET "ComponentName" = i."Name"
            FROM "Ingredients" i
            WHERE ip."ComponentId" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "CashPurchases" cp
            SET "ComponentName" = i."Name"
            FROM "Ingredients" i
            WHERE cp."ComponentId" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "OrderTemplateItems" oti
            SET "ComponentName" = i."Name"
            FROM "Ingredients" i
            WHERE oti."ComponentId" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "InventoryMovements" im
            SET "ComponentName" = i."Name"
            FROM "Ingredients" i
            WHERE im."ComponentId" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "ProductComponentItems" pci
            SET "ComponentName" = i."Name"
            FROM "Ingredients" i
            WHERE pci."ComponentId" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "ProductPackagingItems" ppi
            SET "ComponentName" = i."Name"
            FROM "Ingredients" i
            WHERE ppi."ComponentId" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "QuoteRequestLines" qrl
            SET "ComponentName" = i."Name"
            FROM "Ingredients" i
            WHERE qrl."ComponentExternalId" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "WastageEntries" w
            SET "ItemName" = i."Name"
            FROM "Ingredients" i
            WHERE LOWER(w."ItemType") = 'component' AND w."ItemKey" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "TransferEntries" t
            SET "ItemName" = i."Name"
            FROM "Ingredients" i
            WHERE LOWER(t."ItemType") = 'component' AND t."ItemKey" = i."ComponentId";
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "InventoryCountSessionLines" l
            SET "ItemName" = i."Name"
            FROM "Ingredients" i
            WHERE LOWER(l."ItemType") = 'component' AND l."ItemKey" = i."ComponentId";
            """);
    }

    static async Task UpdateComponentIdColumnAsync(
        BisyncDbContext db,
        string table,
        string column,
        string oldId,
        string newId)
    {
        // Table/column names are caller-controlled constants; values are parameterized.
        await db.Database.ExecuteSqlRawAsync(
            "UPDATE \"" + table + "\" SET \"" + column + "\" = {0} WHERE \"" + column + "\" = {1};",
            newId,
            oldId);
    }

    static async Task UpdatePolymorphicItemKeyAsync(
        BisyncDbContext db,
        string table,
        string oldId,
        string newId)
    {
        await db.Database.ExecuteSqlRawAsync(
            "UPDATE \"" + table + "\" SET \"ItemKey\" = {0} WHERE LOWER(\"ItemType\") = 'component' AND \"ItemKey\" = {1};",
            newId,
            oldId);
    }

    static async Task PersistRemapsAsync(BisyncDbContext db, Dictionary<string, string> idMap)
    {
        foreach (var (oldId, newId) in idMap)
        {
            if (string.Equals(oldId, newId, StringComparison.OrdinalIgnoreCase))
                continue;

            await db.Database.ExecuteSqlInterpolatedAsync($"""
                INSERT INTO "ComponentIdRemaps" ("CompanyId", "OldComponentId", "NewComponentId", "MigratedAt")
                SELECT i."CompanyId", {oldId}, {newId}, NOW()
                FROM "Ingredients" i
                WHERE i."ComponentId" = {newId}
                LIMIT 1;
                """);
        }
    }

    static async Task EnsureIndexesAsync(BisyncDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Ingredients_CompanyId_ComponentId"
            ON "Ingredients" ("CompanyId", "ComponentId");
            """);
        // Case/space-normalized uniqueness: store exact sanitized Name, uniqueness via lower(name).
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Ingredients_CompanyId_LowerName"
            ON "Ingredients" ("CompanyId", LOWER("Name"));
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_Ingredients_CompanyId" ON "Ingredients" ("CompanyId");
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Companies_Code"
            ON "Companies" (UPPER("Code"))
            WHERE "Code" IS NOT NULL AND TRIM("Code") <> '';
            """);
    }

    public static async Task RemapArchiveAsync(DbContext archiveDb, BisyncDbContext opsDb)
    {
        try
        {
            var connection = opsDb.Database.GetDbConnection();
            if (connection.State != System.Data.ConnectionState.Open)
                await connection.OpenAsync();

            await using var cmd = connection.CreateCommand();
            cmd.CommandText = """
                SELECT DISTINCT ON ("OldComponentId") "OldComponentId", "NewComponentId"
                FROM "ComponentIdRemaps"
                ORDER BY "OldComponentId", "Id" DESC
                """;

            var remaps = new List<(string OldId, string NewId)>();
            await using (var reader = await cmd.ExecuteReaderAsync())
            {
                while (await reader.ReadAsync())
                    remaps.Add((reader.GetString(0), reader.GetString(1)));
            }

            foreach (var (oldId, newId) in remaps)
            {
                await archiveDb.Database.ExecuteSqlRawAsync("""
                    UPDATE "ArchivedInventoryMovements"
                    SET "ComponentId" = {0}
                    WHERE "ComponentId" = {1};
                    """, newId, oldId);
                await archiveDb.Database.ExecuteSqlRawAsync("""
                    UPDATE "ArchivedInventoryPurchases"
                    SET "ComponentId" = {0}
                    WHERE "ComponentId" = {1};
                    """, newId, oldId);
            }
        }
        catch
        {
            // Archive remap is best-effort; operational data is the source of truth.
        }
    }
}
