using Bisync.Api.Services;
using Microsoft.EntityFrameworkCore;

namespace Bisync.Api.Data;

public static class SchemaPatcher
{
    public static async Task ApplyAsync(BisyncDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Companies" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_Companies" PRIMARY KEY,
                "Name" TEXT NOT NULL,
                "Brn" TEXT NOT NULL,
                "GstTin" TEXT NOT NULL,
                "CountryCode" TEXT NOT NULL,
                "AddressLine1" TEXT NOT NULL,
                "AddressLine2" TEXT NOT NULL,
                "City" TEXT NOT NULL,
                "StateProvince" TEXT NOT NULL,
                "Postcode" TEXT NOT NULL,
                "Phone" TEXT NOT NULL,
                "Fax" TEXT NOT NULL,
                "Email" TEXT NOT NULL,
                "Active" INTEGER NOT NULL
            );
            """);

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "BusinessTypesJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "VendorPolicyTagsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "ModulesJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "BusinessTypesJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "ModulesJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "VendorPolicyTagsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Vendors", "ProductPolicyTag", "TEXT NOT NULL DEFAULT 'non-halal'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "HalalCertNo", "TEXT NOT NULL DEFAULT ''");

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Vendors"
            SET "ProductPolicyTag" = 'non-halal'
            WHERE LOWER("Name" || ' ' || "Products") LIKE '%wine%'
               OR LOWER("Name" || ' ' || "Products") LIKE '%spirit%'
               OR LOWER("Name" || ' ' || "Products") LIKE '%beer%'
               OR LOWER("Name" || ' ' || "Products") LIKE '%pork%';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Vendors"
            SET "ProductPolicyTag" = 'halal'
            WHERE "ProductPolicyTag" IS NULL
               OR TRIM("ProductPolicyTag") = ''
               OR "ProductPolicyTag" = 'non-halal'
                  AND NOT (
                    LOWER("Name" || ' ' || "Products") LIKE '%wine%'
                    OR LOWER("Name" || ' ' || "Products") LIKE '%spirit%'
                    OR LOWER("Name" || ' ' || "Products") LIKE '%beer%'
                    OR LOWER("Name" || ' ' || "Products") LIKE '%pork%'
                  );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Locations" l
            SET "BusinessTypesJson" = c."BusinessTypesJson",
                "VendorPolicyTagsJson" = c."VendorPolicyTagsJson"
            FROM "Companies" c
            WHERE l."CompanyId" = c."Id"
              AND (l."BusinessTypesJson" IS NULL OR l."BusinessTypesJson" = '[]');
            """);

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Locations" l
            SET "BusinessTypesJson" = '[]',
                "VendorPolicyTagsJson" = '[]'
            FROM "Companies" c
            WHERE l."CompanyId" = c."Id"
              AND l."BusinessTypesJson" = c."BusinessTypesJson"
              AND l."VendorPolicyTagsJson" = c."VendorPolicyTagsJson"
              AND l."BusinessTypesJson" <> '[]';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "AppUsers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_AppUsers" PRIMARY KEY,
                "FullName" TEXT NOT NULL,
                "Email" TEXT NOT NULL,
                "Role" TEXT NOT NULL,
                "Phone" TEXT NOT NULL,
                "Active" INTEGER NOT NULL,
                "AccessJson" TEXT NOT NULL DEFAULT '',
                "CompanyId" INTEGER NULL,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]'
            );
            """);

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "CompanyId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "AddressLine1", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "AddressLine2", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "City", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "StateProvince", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "Postcode", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "PrincipalContactUserId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "AccessJson", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "CompanyId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "LocationIdsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "EmployeeId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "PasswordHash", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "ComponentId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "StorageNote", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "DetailConfigJson", "TEXT NOT NULL DEFAULT '{}'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "CreatedAt", "TIMESTAMP NOT NULL DEFAULT NOW()");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "UpdatedAt", "TIMESTAMP NOT NULL DEFAULT NOW()");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "ContactPosition", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "ContactsJson", "TEXT NOT NULL DEFAULT '[]'");
        await BackfillIngredientComponentIdsAsync(db);
        await TryCreateUniqueIndexAsync(db, "IX_Ingredients_ComponentId", "Ingredients", "ComponentId");
        await TryCreateUniqueIndexAsync(db, "IX_Ingredients_Name", "Ingredients", "Name");

        // Resync identity sequences before seeders — SQLite→PostgreSQL migrations often leave sequences behind MAX(Id).
        await DatabaseSchemaHelper.ResyncCoreIdentitySequencesAsync(db);

        await VendorCatalogSeeder.EnsureCatalogVendorsAsync(db);
        await IngredientCatalogSeeder.EnsureCatalogIngredientsAsync(db);

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "DocumentType", "TEXT NOT NULL DEFAULT 'PO'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "CompanyId", "INTEGER");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "LocationIdsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "InitiatedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ApprovedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ApprovedAt", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ReceivedAt", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ReconciledAt", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorShareToken", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorAcceptedAt", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorAcceptedBy", "TEXT NOT NULL DEFAULT ''");

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "PurchaseOrders"
            SET "DocumentType" = 'PR'
            WHERE "Status" = 'Pending Approval' AND "DocumentType" = 'PO';
            """);

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ComponentId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ComponentName", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ComponentUom", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ReceivedQuantity", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ReceivedUnitPrice", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ReconciledQuantity", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ReconciledUnitPrice", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "TaxAmount", "REAL NOT NULL DEFAULT 0");

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "VendorProductId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "IssuedUnitPrice", "REAL NOT NULL DEFAULT 0");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "InventoryPurchases" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_InventoryPurchases" PRIMARY KEY,
                "ComponentId" TEXT NOT NULL,
                "ComponentName" TEXT NOT NULL,
                "Quantity" REAL NOT NULL,
                "Uom" TEXT NOT NULL,
                "UnitPrice" REAL NOT NULL,
                "DateOrdered" TEXT NOT NULL,
                "DateCreatedInStock" TEXT NOT NULL,
                "PurchaseOrderId" INTEGER NOT NULL,
                "PurchaseOrderItemId" INTEGER NOT NULL,
                "CompanyId" INTEGER,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]'
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "VendorProductPrices" (
                "ExternalId" TEXT NOT NULL CONSTRAINT "PK_VendorProductPrices" PRIMARY KEY,
                "DeliveryPrice" REAL NOT NULL,
                "UpdatedAt" TEXT NOT NULL,
                "LastPurchaseOrderId" INTEGER
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "UserNotifications" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_UserNotifications" PRIMARY KEY,
                "UserId" INTEGER,
                "RecipientName" TEXT NOT NULL DEFAULT '',
                "PurchaseOrderId" INTEGER,
                "Type" TEXT NOT NULL DEFAULT '',
                "Title" TEXT NOT NULL DEFAULT '',
                "Body" TEXT NOT NULL DEFAULT '',
                "CreatedAt" TEXT NOT NULL,
                "ReadAt" TEXT
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "CashPurchases" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_CashPurchases" PRIMARY KEY,
                "DatePurchased" TEXT NOT NULL,
                "StoreName" TEXT NOT NULL DEFAULT '',
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "StoreProductName" TEXT NOT NULL DEFAULT '',
                "DeliveryUnit" TEXT NOT NULL DEFAULT '',
                "DeliveryPrice" REAL NOT NULL,
                "Quantity" REAL NOT NULL,
                "ComponentUom" TEXT NOT NULL DEFAULT '',
                "ReceiptNumber" TEXT NOT NULL DEFAULT '',
                "ReceiptFileName" TEXT NOT NULL DEFAULT '',
                "ReceiptFileBase64" TEXT NOT NULL DEFAULT '',
                "InventoryPurchaseId" INTEGER NOT NULL DEFAULT 0,
                "CompanyId" INTEGER,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "CreatedAt" TEXT NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "OrderTemplates" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_OrderTemplates" PRIMARY KEY,
                "Name" TEXT NOT NULL DEFAULT '',
                "VendorExternalId" TEXT NOT NULL DEFAULT '',
                "VendorName" TEXT NOT NULL DEFAULT '',
                "ScheduleMode" TEXT NOT NULL DEFAULT '',
                "WeekdaysJson" TEXT NOT NULL DEFAULT '[]',
                "MonthDaysJson" TEXT NOT NULL DEFAULT '[]',
                "RepeatEnabled" INTEGER NOT NULL DEFAULT 0,
                "CompanyId" INTEGER,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "CreatedAt" TEXT NOT NULL,
                "UpdatedAt" TEXT NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "OrderTemplateItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_OrderTemplateItems" PRIMARY KEY,
                "OrderTemplateId" INTEGER NOT NULL,
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "VendorProductId" TEXT NOT NULL DEFAULT '',
                "VendorExternalId" TEXT NOT NULL DEFAULT '',
                "VendorName" TEXT NOT NULL DEFAULT '',
                "ProductName" TEXT NOT NULL DEFAULT '',
                "Quantity" REAL NOT NULL,
                "ComponentUom" TEXT NOT NULL DEFAULT '',
                "DeliveryUnit" TEXT NOT NULL DEFAULT '',
                "SortOrder" INTEGER NOT NULL DEFAULT 0,
                CONSTRAINT "FK_OrderTemplateItems_OrderTemplates_OrderTemplateId"
                    FOREIGN KEY ("OrderTemplateId") REFERENCES "OrderTemplates" ("Id") ON DELETE CASCADE
            );
            """);

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "OrderTemplateItems", "DeliveryUnit", "TEXT NOT NULL DEFAULT ''");

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "Rrp", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PosEnabled", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "Active", "INTEGER NOT NULL DEFAULT 1");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "YieldQuantity", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "YieldUom", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PackagingCost", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PreviousTotalCost", "REAL NULL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PreviousPackagingCost", "REAL NULL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PreviousRrp", "REAL NULL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "B2bPackageUnit", "TEXT NOT NULL DEFAULT 'pcs'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "B2bSalesConfigJson", "TEXT NOT NULL DEFAULT '{}'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "ExpiryPeriodDays", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "ActivationPeriodHours", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "ParStock", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "ParStockUom", "TEXT NOT NULL DEFAULT ''");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductB2bLocationStocks" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductB2bLocationStocks" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "LocationExternalId" TEXT NOT NULL DEFAULT '',
                "InStock" REAL NOT NULL DEFAULT 0,
                "SalesPerDay" REAL NOT NULL DEFAULT 0,
                "ToProduceQty" REAL NOT NULL DEFAULT 0,
                "UpdatedAt" TEXT NOT NULL,
                CONSTRAINT "FK_ProductB2bLocationStocks_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductB2bLocationStocks", "ProducedQty", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductB2bLocationStocks", "ExpiryDate", "TEXT NOT NULL DEFAULT ''");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductProductionLogs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductProductionLogs" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "EntryType" TEXT NOT NULL DEFAULT '',
                "Quantity" REAL NOT NULL DEFAULT 0,
                "ProductionDate" TEXT NOT NULL DEFAULT '',
                "ExpiryDate" TEXT NOT NULL DEFAULT '',
                "BatchNumber" TEXT NOT NULL DEFAULT '',
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "CompanyId" INTEGER,
                "CreatedAt" TEXT NOT NULL,
                CONSTRAINT "FK_ProductProductionLogs_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductProductionLogs", "ExpiryDate", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductProductionLogs", "BatchNumber", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductProductionLogs", "UnitPrice", "REAL NOT NULL DEFAULT 0");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductB2bLocationStocks_ProductId_LocationExternalId"
            ON "ProductB2bLocationStocks" ("ProductId", "LocationExternalId");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "InventoryMovements" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_InventoryMovements" PRIMARY KEY,
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "LocationExternalId" TEXT NOT NULL DEFAULT '',
                "QtyDelta" REAL NOT NULL DEFAULT 0,
                "Uom" TEXT NOT NULL DEFAULT '',
                "Reason" TEXT NOT NULL DEFAULT '',
                "ReferenceType" TEXT NOT NULL DEFAULT '',
                "ReferenceId" INTEGER NOT NULL DEFAULT 0,
                "CompanyId" INTEGER,
                "CreatedAt" TEXT NOT NULL
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_InventoryMovements_ComponentId_LocationExternalId"
            ON "InventoryMovements" ("ComponentId", "LocationExternalId");
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "InventoryMovements", "UnitPrice", "REAL NOT NULL DEFAULT 0");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductPackagingItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductPackagingItems" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "ComponentUom" TEXT NOT NULL DEFAULT '',
                "ComponentUomPrice" REAL NOT NULL DEFAULT 0,
                "Quantity" REAL NOT NULL,
                "Subtotal" REAL NOT NULL DEFAULT 0,
                "SortOrder" INTEGER NOT NULL DEFAULT 0,
                CONSTRAINT "FK_ProductPackagingItems_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductAliases" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductAliases" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "Name" TEXT NOT NULL DEFAULT '',
                "Rrp" REAL NOT NULL DEFAULT 0,
                "SortOrder" INTEGER NOT NULL DEFAULT 0,
                CONSTRAINT "FK_ProductAliases_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Products" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_Products" PRIMARY KEY,
                "ProductId" TEXT NOT NULL DEFAULT '',
                "Name" TEXT NOT NULL DEFAULT '',
                "Category" TEXT NOT NULL DEFAULT '',
                "Group" TEXT NOT NULL DEFAULT '',
                "IsSubProduct" INTEGER NOT NULL DEFAULT 0,
                "B2cEnabled" INTEGER NOT NULL DEFAULT 0,
                "B2bEnabled" INTEGER NOT NULL DEFAULT 0,
                "TotalCost" REAL NOT NULL DEFAULT 0,
                "CompanyId" INTEGER,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "CreatedAt" TEXT NOT NULL,
                "UpdatedAt" TEXT NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductComponentItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductComponentItems" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "ComponentUom" TEXT NOT NULL DEFAULT '',
                "ComponentUomPrice" REAL NOT NULL DEFAULT 0,
                "Quantity" REAL NOT NULL,
                "Subtotal" REAL NOT NULL DEFAULT 0,
                "SortOrder" INTEGER NOT NULL DEFAULT 0,
                CONSTRAINT "FK_ProductComponentItems_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "InventoryCountSessions" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_InventoryCountSessions" PRIMARY KEY,
                "SessionType" TEXT NOT NULL DEFAULT '',
                "Status" TEXT NOT NULL DEFAULT '',
                "CompanyId" INTEGER NULL,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "PeriodMonth" TEXT NOT NULL DEFAULT '',
                "UomMode" TEXT NOT NULL DEFAULT 'inventory',
                "ItemTypeFilter" TEXT NOT NULL DEFAULT 'all',
                "GroupFilter" TEXT NOT NULL DEFAULT 'All',
                "CountDate" TEXT NOT NULL DEFAULT '',
                "SavedAt" TEXT NOT NULL,
                "SavedBy" TEXT NOT NULL DEFAULT '',
                "ConfirmDeadlineAt" TEXT NULL,
                "ConfirmedAt" TEXT NULL,
                "ConfirmedBy" TEXT NOT NULL DEFAULT '',
                "IsAutoConfirmed" INTEGER NOT NULL DEFAULT 0,
                "CreatedAt" TEXT NOT NULL,
                "UpdatedAt" TEXT NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "InventoryCountSessionLines" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_InventoryCountSessionLines" PRIMARY KEY,
                "SessionId" INTEGER NOT NULL,
                "ItemType" TEXT NOT NULL DEFAULT '',
                "ItemKey" TEXT NOT NULL DEFAULT '',
                "ItemName" TEXT NOT NULL DEFAULT '',
                "GroupName" TEXT NOT NULL DEFAULT '',
                "Uom" TEXT NOT NULL DEFAULT '',
                "SystemQty" REAL NOT NULL DEFAULT 0,
                "CountedQty" REAL NULL,
                "VarianceQty" REAL NULL,
                CONSTRAINT "FK_InventoryCountSessionLines_InventoryCountSessions_SessionId"
                    FOREIGN KEY ("SessionId") REFERENCES "InventoryCountSessions" ("Id") ON DELETE CASCADE
            );
            """);

        await TryCreateIndexAsync(db, "IX_InventoryCountSessions_Company_Type_Period", "InventoryCountSessions", "\"CompanyId\", \"SessionType\", \"PeriodMonth\"");
        await TryCreateIndexAsync(db, "IX_InventoryCountSessionLines_SessionId", "InventoryCountSessionLines", "\"SessionId\"");

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "InventoryCountSessions", "EffectiveDate", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "InventoryCountSessions", "AdjustmentsAppliedAt", "TEXT NULL");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "InventoryCountSessionLines", "SystemUnitPrice", "REAL NULL");

        await InventoryCountHistorySeeder.EnsureAsync(db);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "B2bCustomers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_B2bCustomers" PRIMARY KEY,
                "CompanyId" integer NOT NULL,
                "ExternalId" TEXT NOT NULL,
                "CompanyName" TEXT NOT NULL,
                "Brn" TEXT NOT NULL,
                "Address" TEXT NOT NULL,
                "City" TEXT NOT NULL,
                "State" TEXT NOT NULL,
                "Postcode" TEXT NOT NULL,
                "Phone" TEXT NOT NULL,
                "Fax" TEXT NOT NULL,
                "Email" TEXT NOT NULL,
                "ContactsJson" TEXT NOT NULL DEFAULT '[]',
                "TaggedProductIdsJson" TEXT NOT NULL DEFAULT '[]',
                "PurchaseHistoryJson" TEXT NOT NULL DEFAULT '[]',
                "Active" INTEGER NOT NULL DEFAULT 1
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "PosCustomers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_PosCustomers" PRIMARY KEY,
                "CompanyId" integer NOT NULL,
                "ExternalId" TEXT NOT NULL,
                "Name" TEXT NOT NULL,
                "Address" TEXT NOT NULL,
                "City" TEXT NOT NULL,
                "State" TEXT NOT NULL,
                "Postcode" TEXT NOT NULL,
                "Phone" TEXT NOT NULL,
                "Fax" TEXT NOT NULL,
                "Email" TEXT NOT NULL,
                "LoyaltySummaryJson" TEXT NOT NULL DEFAULT '[]',
                "CouponSummaryJson" TEXT NOT NULL DEFAULT '[]',
                "ActivityHistoryJson" TEXT NOT NULL DEFAULT '[]',
                "Active" INTEGER NOT NULL DEFAULT 1
            );
            """);

        await TryCreateUniqueIndexAsync(db, "IX_B2bCustomers_ExternalId", "B2bCustomers", "ExternalId");
        await TryCreateIndexAsync(db, "IX_B2bCustomers_CompanyId", "B2bCustomers", "\"CompanyId\"");
        await TryCreateUniqueIndexAsync(db, "IX_PosCustomers_ExternalId", "PosCustomers", "ExternalId");
        await TryCreateIndexAsync(db, "IX_PosCustomers_CompanyId", "PosCustomers", "\"CompanyId\"");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "AccessControlSettings" (
                "Id" integer NOT NULL CONSTRAINT "PK_AccessControlSettings" PRIMARY KEY,
                "TypesJson" TEXT NOT NULL DEFAULT '[]',
                "MatrixJson" TEXT NOT NULL DEFAULT '{{}}'
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            INSERT INTO "AccessControlSettings" ("Id", "TypesJson", "MatrixJson")
            SELECT 1, '[]', '{{}}'
            WHERE NOT EXISTS (SELECT 1 FROM "AccessControlSettings" WHERE "Id" = 1);
            """);

        await CustomerSeeder.EnsureDemoCustomersAsync(db);

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Companies"
            SET "ModulesJson" = '["RMS","POS","HRM","Accounting"]'
            WHERE "ModulesJson" IS NULL OR TRIM("ModulesJson") = '' OR "ModulesJson" = '[]';
            """);

        await DatabaseSchemaHelper.ResyncProductIdentitySequencesAsync(db);
        await DatabaseSchemaHelper.ResyncCoreIdentitySequencesAsync(db);
    }

    static async Task TryCreateIndexAsync(BisyncDbContext db, string indexName, string table, string columns)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync(
                $"CREATE INDEX IF NOT EXISTS \"{indexName}\" ON \"{table}\" ({columns});");
        }
        catch
        {
            // Index may already exist.
        }
    }

    static async Task BackfillIngredientComponentIdsAsync(BisyncDbContext db)
    {
        var needsId = await db.Ingredients
            .Where(i => i.ComponentId == null || i.ComponentId == "")
            .OrderBy(i => i.Id)
            .ToListAsync();

        foreach (var ingredient in needsId)
        {
            ingredient.ComponentId = await ComponentIdGenerator.GenerateAsync(db, ingredient.Name, ingredient.Id);
        }

        if (needsId.Count > 0)
            await db.SaveChangesAsync();
    }

    static async Task TryCreateUniqueIndexAsync(BisyncDbContext db, string indexName, string table, string column)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync(
                $"CREATE UNIQUE INDEX IF NOT EXISTS \"{indexName}\" ON \"{table}\" (\"{column}\");");
        }
        catch
        {
            // Index may already exist with different definition
        }
    }
}
