using Bisync.Api.Models;
using Bisync.Api.Services;
using Microsoft.EntityFrameworkCore;

namespace Bisync.Api.Data;

public static class SchemaPatcher
{
    public static async Task ApplyAsync(BisyncDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Companies" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_Companies" PRIMARY KEY,
                "Name" TEXT NOT NULL,
                "Brn" TEXT NOT NULL,
                "GstTin" TEXT NOT NULL,
                "CountryCode" TEXT NOT NULL,
                "AddressLine1" TEXT NOT NULL,
                "AddressLine2" TEXT NOT NULL,
                "City" TEXT NOT NULL,
                "StateProvince" TEXT NOT NULL,
                "Postcode" TEXT NOT NULL,
                "Phone" TEXT NOT NULL,
                "Fax" TEXT NOT NULL,
                "Email" TEXT NOT NULL,
                "Active" INTEGER NOT NULL
            );
            """);

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "BusinessTypesJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "VendorPolicyTagsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "ModulesJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "RegisteredAt", "timestamp with time zone NULL");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "SmtpHost", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "SmtpPort", "INTEGER NOT NULL DEFAULT 587");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "SmtpUseSsl", "BOOLEAN NOT NULL DEFAULT TRUE");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "SmtpUsername", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "SmtpPassword", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "SmtpFromEmail", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Companies", "SmtpFromName", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "BusinessTypesJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "ModulesJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "VendorPolicyTagsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Vendors", "ProductPolicyTag", "TEXT NOT NULL DEFAULT 'non-halal'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "HalalCertNo", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ProductExpiryDate", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorDoNumber", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorInvoiceNumber", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ProductQualityRating", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ProductQualityComment", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "HygieneRating", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "HygieneComment", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "PurchaseOrderItems", "ReceivedTemperature", "numeric");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "PlatformLaunchSettings" (
                "Id" integer NOT NULL CONSTRAINT "PK_PlatformLaunchSettings" PRIMARY KEY,
                "DemoMode" boolean NOT NULL DEFAULT TRUE,
                "GoLive" boolean NOT NULL DEFAULT FALSE,
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "UpdatedByEmail" TEXT NOT NULL DEFAULT ''
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Vendors"
            SET "ProductPolicyTag" = 'non-halal'
            WHERE LOWER("Name" || ' ' || "Products") LIKE '%wine%'
               OR LOWER("Name" || ' ' || "Products") LIKE '%spirit%'
               OR LOWER("Name" || ' ' || "Products") LIKE '%beer%'
               OR LOWER("Name" || ' ' || "Products") LIKE '%pork%';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Vendors"
            SET "ProductPolicyTag" = 'halal'
            WHERE "ProductPolicyTag" IS NULL
               OR TRIM("ProductPolicyTag") = ''
               OR "ProductPolicyTag" = 'non-halal'
                  AND NOT (
                    LOWER("Name" || ' ' || "Products") LIKE '%wine%'
                    OR LOWER("Name" || ' ' || "Products") LIKE '%spirit%'
                    OR LOWER("Name" || ' ' || "Products") LIKE '%beer%'
                    OR LOWER("Name" || ' ' || "Products") LIKE '%pork%'
                  );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Locations" l
            SET "BusinessTypesJson" = c."BusinessTypesJson",
                "VendorPolicyTagsJson" = c."VendorPolicyTagsJson"
            FROM "Companies" c
            WHERE l."CompanyId" = c."Id"
              AND (l."BusinessTypesJson" IS NULL OR l."BusinessTypesJson" = '[]');
            """);

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Locations" l
            SET "BusinessTypesJson" = '[]',
                "VendorPolicyTagsJson" = '[]'
            FROM "Companies" c
            WHERE l."CompanyId" = c."Id"
              AND l."BusinessTypesJson" = c."BusinessTypesJson"
              AND l."VendorPolicyTagsJson" = c."VendorPolicyTagsJson"
              AND l."BusinessTypesJson" <> '[]';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "AppUsers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_AppUsers" PRIMARY KEY,
                "FullName" TEXT NOT NULL,
                "Email" TEXT NOT NULL,
                "Role" TEXT NOT NULL,
                "Phone" TEXT NOT NULL,
                "Active" INTEGER NOT NULL,
                "AccessJson" TEXT NOT NULL DEFAULT '',
                "CompanyId" INTEGER NULL,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]'
            );
            """);

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "CompanyId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "AddressLine1", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "AddressLine2", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "City", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "StateProvince", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "Postcode", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Locations", "PrincipalContactUserId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "AccessJson", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "CompanyId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "LocationIdsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "EmployeeId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "PasswordHash", "TEXT");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "ActivationToken", "TEXT");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "ActivationTokenExpiresAt", "TIMESTAMP");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "PreferredLanguage", "TEXT NOT NULL DEFAULT 'en'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "AppUsers", "PhoneCountryCode", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "ComponentId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "StorageNote", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "DetailConfigJson", "TEXT NOT NULL DEFAULT '{}'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "CreatedAt", "TIMESTAMP NOT NULL DEFAULT NOW()");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "UpdatedAt", "TIMESTAMP NOT NULL DEFAULT NOW()");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Ingredients", "CompanyId", "INTEGER");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "ContactPosition", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "ContactsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "CompanyId", "INTEGER");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "EngagementStatus", "TEXT NOT NULL DEFAULT 'none'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Vendors", "LinkedCompanyId", "INTEGER");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Vendors", "MinOrderAmount", "numeric");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Vendors", "DeliveryChargeBelowMin", "numeric");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "PaymentTerms", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Vendors", "EngageRequestedAt", "timestamp with time zone");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "EngageRequestedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "Vendors", "EngageApprovedAt", "timestamp with time zone");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Vendors", "EngageApprovedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorExternalId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "B2bSalesOrders", "SourcePurchaseOrderId", "INTEGER");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Companies", "Code", "TEXT NOT NULL DEFAULT ''");
        await BackfillIngredientComponentIdsAsync(db);
        await BackfillCatalogCompanyIdsAsync(db);
        await EnsureCompanyScopedCatalogIndexesAsync(db);
        await ComponentIdentityMigrator.ApplyAsync(db);
        await EnsureTenantConnectionsTableAsync(db);
        await BackfillTenantConnectionsAsync(db);
        await EnsureTenantRollupSnapshotsTableAsync(db);

        // Resync identity sequences before seeders — SQLite→PostgreSQL migrations often leave sequences behind MAX(Id).
        await DatabaseSchemaHelper.ResyncCoreIdentitySequencesAsync(db);

        await VendorCatalogSeeder.EnsureCatalogVendorsAsync(db);
        await IngredientCatalogSeeder.EnsureCatalogIngredientsAsync(db);

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "DocumentType", "TEXT NOT NULL DEFAULT 'PO'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "CompanyId", "INTEGER");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "LocationIdsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "InitiatedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ApprovedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ApprovedAt", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ReceivedAt", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "ReconciledAt", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorShareToken", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorAcceptedAt", "TEXT");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrders", "VendorAcceptedBy", "TEXT NOT NULL DEFAULT ''");

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "PurchaseOrders"
            SET "DocumentType" = 'PR'
            WHERE "Status" = 'Pending Approval' AND "DocumentType" = 'PO';
            """);

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ComponentId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ComponentName", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ComponentUom", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ReceivedQuantity", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ReceivedUnitPrice", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ReconciledQuantity", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "ReconciledUnitPrice", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "TaxAmount", "REAL NOT NULL DEFAULT 0");

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "VendorProductId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "PurchaseOrderItems", "IssuedUnitPrice", "REAL NOT NULL DEFAULT 0");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "InventoryPurchases" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_InventoryPurchases" PRIMARY KEY,
                "ComponentId" TEXT NOT NULL,
                "ComponentName" TEXT NOT NULL,
                "Quantity" REAL NOT NULL,
                "Uom" TEXT NOT NULL,
                "UnitPrice" REAL NOT NULL,
                "DateOrdered" TEXT NOT NULL,
                "DateCreatedInStock" TEXT NOT NULL,
                "PurchaseOrderId" INTEGER NOT NULL,
                "PurchaseOrderItemId" INTEGER NOT NULL,
                "CompanyId" INTEGER,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]'
            );
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "InventoryPurchases", "LocationExternalId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "InventoryPurchases", "SplitSourceType", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "InventoryPurchases", "SplitSourceId", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "InventoryPurchases", "SplitLineKey", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "InventoryPurchases", "SplitParentComponentId", "TEXT NOT NULL DEFAULT ''");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_InventoryPurchases_SplitSource"
            ON "InventoryPurchases" ("SplitSourceType", "SplitSourceId", "SplitLineKey", "LocationExternalId")
            WHERE "SplitSourceType" <> '';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "VendorProductPrices" (
                "ExternalId" TEXT NOT NULL CONSTRAINT "PK_VendorProductPrices" PRIMARY KEY,
                "DeliveryPrice" REAL NOT NULL,
                "UpdatedAt" TEXT NOT NULL,
                "LastPurchaseOrderId" INTEGER
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "UserNotifications" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_UserNotifications" PRIMARY KEY,
                "UserId" INTEGER,
                "RecipientName" TEXT NOT NULL DEFAULT '',
                "PurchaseOrderId" INTEGER,
                "Type" TEXT NOT NULL DEFAULT '',
                "Title" TEXT NOT NULL DEFAULT '',
                "Body" TEXT NOT NULL DEFAULT '',
                "CreatedAt" TEXT NOT NULL,
                "ReadAt" TEXT
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "CashPurchases" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_CashPurchases" PRIMARY KEY,
                "DatePurchased" TEXT NOT NULL,
                "StoreName" TEXT NOT NULL DEFAULT '',
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "StoreProductName" TEXT NOT NULL DEFAULT '',
                "DeliveryUnit" TEXT NOT NULL DEFAULT '',
                "DeliveryPrice" REAL NOT NULL,
                "Quantity" REAL NOT NULL,
                "ComponentUom" TEXT NOT NULL DEFAULT '',
                "ReceiptNumber" TEXT NOT NULL DEFAULT '',
                "ReceiptFileName" TEXT NOT NULL DEFAULT '',
                "ReceiptFileBase64" TEXT NOT NULL DEFAULT '',
                "InventoryPurchaseId" INTEGER NOT NULL DEFAULT 0,
                "CompanyId" INTEGER,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "CreatedAt" TEXT NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "WastageEntries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_WastageEntries" PRIMARY KEY,
                "CompanyId" INTEGER,
                "LocationExternalId" TEXT NOT NULL DEFAULT '',
                "Source" TEXT NOT NULL DEFAULT 'manual',
                "ItemType" TEXT NOT NULL DEFAULT 'component',
                "ItemKey" TEXT NOT NULL DEFAULT '',
                "ItemName" TEXT NOT NULL DEFAULT '',
                "Quantity" REAL NOT NULL DEFAULT 0,
                "Uom" TEXT NOT NULL DEFAULT '',
                "WastedDate" date NOT NULL,
                "Reason" TEXT NOT NULL DEFAULT '',
                "PosCheckNo" TEXT NOT NULL DEFAULT '',
                "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_WastageEntries_CompanyId_WastedDate"
            ON "WastageEntries" ("CompanyId", "WastedDate");
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "WastageEntries", "UnitPrice", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "WastageEntries", "TotalValue", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "WastageEntries", "SourceReferenceType", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "WastageEntries", "SourceReferenceId", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "WastageEntries", "SplitUseLineKey", "TEXT NOT NULL DEFAULT ''");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "UX_WastageEntries_SplitSource"
            ON "WastageEntries" ("SourceReferenceType", "SourceReferenceId", "SplitUseLineKey", "LocationExternalId")
            WHERE "SourceReferenceType" <> '' AND "SplitUseLineKey" <> '';
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "TransferEntries" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_TransferEntries" PRIMARY KEY,
                "CompanyId" INTEGER,
                "FromLocationExternalId" TEXT NOT NULL DEFAULT '',
                "ToLocationExternalId" TEXT NOT NULL DEFAULT '',
                "ItemType" TEXT NOT NULL DEFAULT 'component',
                "ItemKey" TEXT NOT NULL DEFAULT '',
                "ItemName" TEXT NOT NULL DEFAULT '',
                "Quantity" REAL NOT NULL DEFAULT 0,
                "Uom" TEXT NOT NULL DEFAULT '',
                "TransferDate" date NOT NULL,
                "Status" TEXT NOT NULL DEFAULT 'pending',
                "InitiatedBy" TEXT NOT NULL DEFAULT '',
                "ReceivedBy" TEXT NOT NULL DEFAULT '',
                "ReceivedAt" TIMESTAMP,
                "ReceivedQuantity" REAL,
                "UnitPrice" REAL NOT NULL DEFAULT 0,
                "RejectedBy" TEXT NOT NULL DEFAULT '',
                "RejectedAt" TIMESTAMP,
                "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_TransferEntries_CompanyId_TransferDate"
            ON "TransferEntries" ("CompanyId", "TransferDate");
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TransferEntries", "Status", "TEXT NOT NULL DEFAULT 'pending'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TransferEntries", "InitiatedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TransferEntries", "ReceivedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TransferEntries", "ReceivedAt", "TIMESTAMP");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TransferEntries", "ReceivedQuantity", "REAL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TransferEntries", "UnitPrice", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TransferEntries", "RejectedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TransferEntries", "RejectedAt", "TIMESTAMP");
        // Backfill unit cost from stock movements for received transfers that predate the column.
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "TransferEntries" t
            SET "UnitPrice" = m."UnitPrice"
            FROM "InventoryMovements" m
            WHERE COALESCE(t."UnitPrice", 0) = 0
              AND m."ReferenceType" = 'transfer_out'
              AND m."ReferenceId" = t."Id"
              AND m."UnitPrice" > 0;
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "TransferEntries" t
            SET "UnitPrice" = p."UnitPrice"
            FROM "ProductProductionLogs" p
            WHERE COALESCE(t."UnitPrice", 0) = 0
              AND p."EntryType" = 'transfer_out'
              AND p."BatchNumber" = ('XFR-' || t."Id"::text)
              AND p."UnitPrice" > 0;
            """);
        // Legacy rows were completed immediately; treat those with stock movements as received.
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "TransferEntries" t
            SET "Status" = 'received',
                "ReceivedQuantity" = COALESCE(t."ReceivedQuantity", t."Quantity"),
                "ReceivedAt" = COALESCE(t."ReceivedAt", t."CreatedAt")
            WHERE (t."Status" IS NULL OR TRIM(t."Status") = '' OR t."Status" = 'pending')
              AND (
                EXISTS (
                  SELECT 1 FROM "InventoryMovements" m
                  WHERE m."ReferenceType" IN ('transfer_out', 'transfer_in')
                    AND m."ReferenceId" = t."Id"
                )
                OR EXISTS (
                  SELECT 1 FROM "ProductProductionLogs" p
                  WHERE p."EntryType" IN ('transfer_out', 'transfer_in')
                    AND p."BatchNumber" = ('XFR-' || t."Id"::text)
                )
              );
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "UserNotifications", "TransferId", "INTEGER");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_TransferEntries_Status_ToLocation"
            ON "TransferEntries" ("Status", "ToLocationExternalId");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "OrderTemplates" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_OrderTemplates" PRIMARY KEY,
                "Name" TEXT NOT NULL DEFAULT '',
                "VendorExternalId" TEXT NOT NULL DEFAULT '',
                "VendorName" TEXT NOT NULL DEFAULT '',
                "ScheduleMode" TEXT NOT NULL DEFAULT '',
                "WeekdaysJson" TEXT NOT NULL DEFAULT '[]',
                "MonthDaysJson" TEXT NOT NULL DEFAULT '[]',
                "RepeatEnabled" INTEGER NOT NULL DEFAULT 0,
                "CompanyId" INTEGER,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "CreatedAt" TEXT NOT NULL,
                "UpdatedAt" TEXT NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "OrderTemplateItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_OrderTemplateItems" PRIMARY KEY,
                "OrderTemplateId" INTEGER NOT NULL,
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "VendorProductId" TEXT NOT NULL DEFAULT '',
                "VendorExternalId" TEXT NOT NULL DEFAULT '',
                "VendorName" TEXT NOT NULL DEFAULT '',
                "ProductName" TEXT NOT NULL DEFAULT '',
                "Quantity" REAL NOT NULL,
                "ComponentUom" TEXT NOT NULL DEFAULT '',
                "DeliveryUnit" TEXT NOT NULL DEFAULT '',
                "SortOrder" INTEGER NOT NULL DEFAULT 0,
                CONSTRAINT "FK_OrderTemplateItems_OrderTemplates_OrderTemplateId"
                    FOREIGN KEY ("OrderTemplateId") REFERENCES "OrderTemplates" ("Id") ON DELETE CASCADE
            );
            """);

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "OrderTemplateItems", "DeliveryUnit", "TEXT NOT NULL DEFAULT ''");

        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "Rrp", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PosEnabled", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PosDeliveryUnitsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "Active", "INTEGER NOT NULL DEFAULT 1");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "YieldQuantity", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "YieldUom", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "YieldAltUnitsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PackagingCost", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PreviousTotalCost", "REAL NULL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PreviousPackagingCost", "REAL NULL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "PreviousRrp", "REAL NULL");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "B2bPackageUnit", "TEXT NOT NULL DEFAULT 'pcs'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "B2bSalesConfigJson", "TEXT NOT NULL DEFAULT '{}'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "ExpiryPeriodDays", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "ActivationPeriodHours", "INTEGER NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "OrderLockPeriodDays", "INTEGER NOT NULL DEFAULT 7");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "ParStock", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "Products", "ParStockUom", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductAliases", "B2bSalesConfigJson", "TEXT NOT NULL DEFAULT '{}'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "B2bCustomers", "TaggedProductAliasIdsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "B2bCustomers", "TaggedB2bProductUnitsJson", "TEXT NOT NULL DEFAULT '[]'");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "B2bSalesOrderLines", "ProductAliasId", "INTEGER NULL");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductB2bLocationStocks" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductB2bLocationStocks" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "LocationExternalId" TEXT NOT NULL DEFAULT '',
                "InStock" REAL NOT NULL DEFAULT 0,
                "SalesPerDay" REAL NOT NULL DEFAULT 0,
                "ToProduceQty" REAL NOT NULL DEFAULT 0,
                "UpdatedAt" TEXT NOT NULL,
                CONSTRAINT "FK_ProductB2bLocationStocks_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductB2bLocationStocks", "ProducedQty", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductB2bLocationStocks", "ExpiryDate", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductB2bLocationStocks", "OnOrderQty", "NUMERIC NOT NULL DEFAULT 0");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "B2bSalesOrders" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_B2bSalesOrders" PRIMARY KEY,
                "CompanyId" INTEGER NOT NULL,
                "OrderNumber" TEXT NOT NULL DEFAULT '',
                "CustomerExternalId" TEXT NOT NULL DEFAULT '',
                "CustomerName" TEXT NOT NULL DEFAULT '',
                "Source" TEXT NOT NULL DEFAULT 'sales_order',
                "Status" TEXT NOT NULL DEFAULT 'draft',
                "LockPeriodDays" INTEGER NOT NULL DEFAULT 0,
                "IssuedDate" TEXT NOT NULL DEFAULT '',
                "LockExpiryDate" TEXT NOT NULL DEFAULT '',
                "DeliveryOrderIssued" BOOLEAN NOT NULL DEFAULT FALSE,
                "InvoiceIssued" BOOLEAN NOT NULL DEFAULT FALSE,
                "FulfilledDate" TEXT NOT NULL DEFAULT '',
                "ShareToken" TEXT NOT NULL DEFAULT '',
                "CreatedAt" timestamp with time zone NOT NULL,
                "UpdatedAt" timestamp with time zone NOT NULL
            );
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "B2bSalesOrders", "ShareToken", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "B2bSalesOrders", "CustomerAcceptedBy", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "B2bSalesOrders", "CustomerAcceptedAt", "timestamp with time zone");
        await TryCreateIndexAsync(db, "IX_B2bSalesOrders_ShareToken", "B2bSalesOrders", "\"ShareToken\"");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "B2bSalesOrderLines" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_B2bSalesOrderLines" PRIMARY KEY,
                "SalesOrderId" INTEGER NOT NULL,
                "ProductId" INTEGER NOT NULL,
                "ProductName" TEXT NOT NULL DEFAULT '',
                "LocationExternalId" TEXT NOT NULL DEFAULT '',
                "QuantityOrdered" NUMERIC NOT NULL DEFAULT 0,
                "QuantityLocked" NUMERIC NOT NULL DEFAULT 0,
                "Uom" TEXT NOT NULL DEFAULT '',
                "Rrp" NUMERIC NOT NULL DEFAULT 0,
                "Status" TEXT NOT NULL DEFAULT 'open',
                CONSTRAINT "FK_B2bSalesOrderLines_B2bSalesOrders_SalesOrderId"
                    FOREIGN KEY ("SalesOrderId") REFERENCES "B2bSalesOrders" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_B2bSalesOrderLines_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_B2bSalesOrders_CompanyId_Status"
            ON "B2bSalesOrders" ("CompanyId", "Status");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductProductionLogs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductProductionLogs" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "EntryType" TEXT NOT NULL DEFAULT '',
                "Quantity" REAL NOT NULL DEFAULT 0,
                "ProductionDate" TEXT NOT NULL DEFAULT '',
                "ExpiryDate" TEXT NOT NULL DEFAULT '',
                "BatchNumber" TEXT NOT NULL DEFAULT '',
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "CompanyId" INTEGER,
                "CreatedAt" TEXT NOT NULL,
                CONSTRAINT "FK_ProductProductionLogs_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductProductionLogs", "ExpiryDate", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductProductionLogs", "BatchNumber", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductProductionLogs", "UnitPrice", "REAL NOT NULL DEFAULT 0");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "ProductProductionLogs", "LocationExternalId", "TEXT NOT NULL DEFAULT ''");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_ProductB2bLocationStocks_ProductId_LocationExternalId"
            ON "ProductB2bLocationStocks" ("ProductId", "LocationExternalId");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "InventoryMovements" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_InventoryMovements" PRIMARY KEY,
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "LocationExternalId" TEXT NOT NULL DEFAULT '',
                "QtyDelta" REAL NOT NULL DEFAULT 0,
                "Uom" TEXT NOT NULL DEFAULT '',
                "Reason" TEXT NOT NULL DEFAULT '',
                "ReferenceType" TEXT NOT NULL DEFAULT '',
                "ReferenceId" INTEGER NOT NULL DEFAULT 0,
                "CompanyId" INTEGER,
                "CreatedAt" TEXT NOT NULL
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_InventoryMovements_ComponentId_LocationExternalId"
            ON "InventoryMovements" ("ComponentId", "LocationExternalId");
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "InventoryMovements", "UnitPrice", "REAL NOT NULL DEFAULT 0");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductPackagingItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductPackagingItems" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "ComponentUom" TEXT NOT NULL DEFAULT '',
                "ComponentUomPrice" REAL NOT NULL DEFAULT 0,
                "Quantity" REAL NOT NULL,
                "Subtotal" REAL NOT NULL DEFAULT 0,
                "SortOrder" INTEGER NOT NULL DEFAULT 0,
                CONSTRAINT "FK_ProductPackagingItems_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductAliases" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductAliases" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "Name" TEXT NOT NULL DEFAULT '',
                "Rrp" REAL NOT NULL DEFAULT 0,
                "SortOrder" INTEGER NOT NULL DEFAULT 0,
                CONSTRAINT "FK_ProductAliases_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Products" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_Products" PRIMARY KEY,
                "ProductId" TEXT NOT NULL DEFAULT '',
                "Name" TEXT NOT NULL DEFAULT '',
                "Category" TEXT NOT NULL DEFAULT '',
                "Group" TEXT NOT NULL DEFAULT '',
                "IsSubProduct" INTEGER NOT NULL DEFAULT 0,
                "B2cEnabled" INTEGER NOT NULL DEFAULT 0,
                "B2bEnabled" INTEGER NOT NULL DEFAULT 0,
                "TotalCost" REAL NOT NULL DEFAULT 0,
                "CompanyId" INTEGER,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "CreatedAt" TEXT NOT NULL,
                "UpdatedAt" TEXT NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "ProductComponentItems" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_ProductComponentItems" PRIMARY KEY,
                "ProductId" INTEGER NOT NULL,
                "ComponentId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "ComponentUom" TEXT NOT NULL DEFAULT '',
                "ComponentUomPrice" REAL NOT NULL DEFAULT 0,
                "Quantity" REAL NOT NULL,
                "Subtotal" REAL NOT NULL DEFAULT 0,
                "SortOrder" INTEGER NOT NULL DEFAULT 0,
                CONSTRAINT "FK_ProductComponentItems_Products_ProductId"
                    FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "InventoryCountSessions" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_InventoryCountSessions" PRIMARY KEY,
                "SessionType" TEXT NOT NULL DEFAULT '',
                "Status" TEXT NOT NULL DEFAULT '',
                "CompanyId" INTEGER NULL,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "PeriodMonth" TEXT NOT NULL DEFAULT '',
                "UomMode" TEXT NOT NULL DEFAULT 'inventory',
                "ItemTypeFilter" TEXT NOT NULL DEFAULT 'all',
                "GroupFilter" TEXT NOT NULL DEFAULT 'All',
                "CountDate" TEXT NOT NULL DEFAULT '',
                "SavedAt" TEXT NOT NULL,
                "SavedBy" TEXT NOT NULL DEFAULT '',
                "ConfirmDeadlineAt" TEXT NULL,
                "ConfirmedAt" TEXT NULL,
                "ConfirmedBy" TEXT NOT NULL DEFAULT '',
                "IsAutoConfirmed" INTEGER NOT NULL DEFAULT 0,
                "CreatedAt" TEXT NOT NULL,
                "UpdatedAt" TEXT NOT NULL
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "InventoryCountSessionLines" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_InventoryCountSessionLines" PRIMARY KEY,
                "SessionId" INTEGER NOT NULL,
                "ItemType" TEXT NOT NULL DEFAULT '',
                "ItemKey" TEXT NOT NULL DEFAULT '',
                "ItemName" TEXT NOT NULL DEFAULT '',
                "GroupName" TEXT NOT NULL DEFAULT '',
                "Uom" TEXT NOT NULL DEFAULT '',
                "SystemQty" REAL NOT NULL DEFAULT 0,
                "CountedQty" REAL NULL,
                "VarianceQty" REAL NULL,
                CONSTRAINT "FK_InventoryCountSessionLines_InventoryCountSessions_SessionId"
                    FOREIGN KEY ("SessionId") REFERENCES "InventoryCountSessions" ("Id") ON DELETE CASCADE
            );
            """);

        await TryCreateIndexAsync(db, "IX_InventoryCountSessions_Company_Type_Period", "InventoryCountSessions", "\"CompanyId\", \"SessionType\", \"PeriodMonth\"");
        await TryCreateIndexAsync(db, "IX_InventoryCountSessionLines_SessionId", "InventoryCountSessionLines", "\"SessionId\"");

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "InventoryCountSessions", "EffectiveDate", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "InventoryCountSessions", "AdjustmentsAppliedAt", "TEXT NULL");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "InventoryCountSessionLines", "SystemUnitPrice", "REAL NULL");

        await InventoryCountHistorySeeder.EnsureAsync(db);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "B2bCustomers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_B2bCustomers" PRIMARY KEY,
                "CompanyId" integer NOT NULL,
                "ExternalId" TEXT NOT NULL,
                "CompanyName" TEXT NOT NULL,
                "Brn" TEXT NOT NULL,
                "Address" TEXT NOT NULL,
                "City" TEXT NOT NULL,
                "State" TEXT NOT NULL,
                "Postcode" TEXT NOT NULL,
                "Phone" TEXT NOT NULL,
                "Fax" TEXT NOT NULL,
                "Email" TEXT NOT NULL,
                "ContactsJson" TEXT NOT NULL DEFAULT '[]',
                "TaggedProductIdsJson" TEXT NOT NULL DEFAULT '[]',
                "PurchaseHistoryJson" TEXT NOT NULL DEFAULT '[]',
                "Active" INTEGER NOT NULL DEFAULT 1
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "PosCustomers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_PosCustomers" PRIMARY KEY,
                "CompanyId" integer NOT NULL,
                "ExternalId" TEXT NOT NULL,
                "Name" TEXT NOT NULL,
                "Address" TEXT NOT NULL,
                "City" TEXT NOT NULL,
                "State" TEXT NOT NULL,
                "Postcode" TEXT NOT NULL,
                "Phone" TEXT NOT NULL,
                "Fax" TEXT NOT NULL,
                "Email" TEXT NOT NULL,
                "LoyaltySummaryJson" TEXT NOT NULL DEFAULT '[]',
                "CouponSummaryJson" TEXT NOT NULL DEFAULT '[]',
                "ActivityHistoryJson" TEXT NOT NULL DEFAULT '[]',
                "Active" INTEGER NOT NULL DEFAULT 1
            );
            """);

        await TryCreateUniqueIndexAsync(db, "IX_B2bCustomers_ExternalId", "B2bCustomers", "ExternalId");
        await TryCreateIndexAsync(db, "IX_B2bCustomers_CompanyId", "B2bCustomers", "\"CompanyId\"");
        await TryCreateUniqueIndexAsync(db, "IX_PosCustomers_ExternalId", "PosCustomers", "ExternalId");
        await TryCreateIndexAsync(db, "IX_PosCustomers_CompanyId", "PosCustomers", "\"CompanyId\"");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "AccessControlSettings" (
                "Id" integer NOT NULL CONSTRAINT "PK_AccessControlSettings" PRIMARY KEY,
                "TypesJson" TEXT NOT NULL DEFAULT '[]',
                "MatrixJson" TEXT NOT NULL DEFAULT '{{}}'
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            INSERT INTO "AccessControlSettings" ("Id", "TypesJson", "MatrixJson")
            SELECT 1, '[]', '{{}}'
            WHERE NOT EXISTS (SELECT 1 FROM "AccessControlSettings" WHERE "Id" = 1);
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "RevMgmtCompanyConfigs" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_RevMgmtCompanyConfigs" PRIMARY KEY,
                "CompanyId" integer NOT NULL,
                "ConfigKey" TEXT NOT NULL,
                "StateJson" TEXT NOT NULL DEFAULT '{{}}',
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_RevMgmtCompanyConfigs_CompanyId_ConfigKey"
            ON "RevMgmtCompanyConfigs" ("CompanyId", "ConfigKey");
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "VendorProducts" (
                "ExternalId" TEXT NOT NULL CONSTRAINT "PK_VendorProducts" PRIMARY KEY,
                "VendorExternalId" TEXT NOT NULL DEFAULT '',
                "VendorName" TEXT NOT NULL DEFAULT '',
                "ProductName" TEXT NOT NULL DEFAULT '',
                "Group" TEXT NOT NULL DEFAULT '',
                "Specification" TEXT NOT NULL DEFAULT '',
                "ImageUrl" TEXT NOT NULL DEFAULT '',
                "DeliveryPrice" numeric NOT NULL DEFAULT 0,
                "DeliveryJson" TEXT NOT NULL DEFAULT '{{}}',
                "ProductPolicyTag" TEXT NOT NULL DEFAULT '',
                "IsPrivate" boolean NOT NULL DEFAULT false,
                "PrivateLocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "Active" boolean NOT NULL DEFAULT true,
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """);

        await TryCreateIndexAsync(db, "IX_VendorProducts_VendorExternalId", "VendorProducts", "\"VendorExternalId\"");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "VendorRatings" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_VendorRatings" PRIMARY KEY,
                "CompanyId" integer,
                "VendorExternalId" TEXT NOT NULL DEFAULT '',
                "Delivery" TEXT NOT NULL DEFAULT '',
                "ProductAccuracy" TEXT NOT NULL DEFAULT '',
                "ProductQuality" TEXT NOT NULL DEFAULT '',
                "HygieneCleanliness" TEXT NOT NULL DEFAULT '',
                "Notes" TEXT NOT NULL DEFAULT '',
                "UpdatedBy" TEXT NOT NULL DEFAULT '',
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """);
        await TryCreateIndexAsync(db, "IX_VendorRatings_VendorExternalId", "VendorRatings", "\"VendorExternalId\"");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "QuoteRequests" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_QuoteRequests" PRIMARY KEY,
                "RfqNumber" TEXT NOT NULL DEFAULT '',
                "CompanyId" integer NOT NULL DEFAULT 0,
                "LocationIdsJson" TEXT NOT NULL DEFAULT '[]',
                "Status" TEXT NOT NULL DEFAULT 'open',
                "Notes" TEXT NOT NULL DEFAULT '',
                "CreatedBy" TEXT NOT NULL DEFAULT '',
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "QuoteRequestVendors" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_QuoteRequestVendors" PRIMARY KEY,
                "QuoteRequestId" integer NOT NULL,
                "VendorId" integer,
                "VendorExternalId" TEXT NOT NULL DEFAULT '',
                "VendorName" TEXT NOT NULL DEFAULT '',
                "ContactPerson" TEXT NOT NULL DEFAULT '',
                "Email" TEXT NOT NULL DEFAULT '',
                "Mobile" TEXT NOT NULL DEFAULT '',
                "IsNewVendor" boolean NOT NULL DEFAULT false,
                "ShareToken" TEXT NOT NULL DEFAULT '',
                "Status" TEXT NOT NULL DEFAULT 'pending',
                "SubmittedAt" timestamp with time zone,
                "SubmittedBy" TEXT NOT NULL DEFAULT '',
                CONSTRAINT "FK_QuoteRequestVendors_QuoteRequests_QuoteRequestId"
                    FOREIGN KEY ("QuoteRequestId") REFERENCES "QuoteRequests" ("Id") ON DELETE CASCADE
            );
            """);

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "QuoteRequestLines" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_QuoteRequestLines" PRIMARY KEY,
                "QuoteRequestId" integer NOT NULL,
                "Kind" TEXT NOT NULL DEFAULT 'principal',
                "SortOrder" integer NOT NULL DEFAULT 0,
                "ComponentId" integer,
                "ComponentExternalId" TEXT NOT NULL DEFAULT '',
                "ComponentName" TEXT NOT NULL DEFAULT '',
                "Specification" TEXT NOT NULL DEFAULT '',
                "PrincipalUom" TEXT NOT NULL DEFAULT '',
                "RequestedQty" numeric NOT NULL DEFAULT 0,
                "VendorResponsesJson" TEXT NOT NULL DEFAULT '{{}}',
                CONSTRAINT "FK_QuoteRequestLines_QuoteRequests_QuoteRequestId"
                    FOREIGN KEY ("QuoteRequestId") REFERENCES "QuoteRequests" ("Id") ON DELETE CASCADE
            );
            """);

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "QuoteRequestLines", "Specification", "TEXT NOT NULL DEFAULT ''");

        await TryCreateIndexAsync(db, "IX_QuoteRequestVendors_ShareToken", "QuoteRequestVendors", "\"ShareToken\"");
        await TryCreateIndexAsync(db, "IX_QuoteRequestVendors_QuoteRequestId", "QuoteRequestVendors", "\"QuoteRequestId\"");
        await TryCreateIndexAsync(db, "IX_QuoteRequestLines_QuoteRequestId", "QuoteRequestLines", "\"QuoteRequestId\"");
        await TryCreateIndexAsync(db, "IX_QuoteRequests_CompanyId", "QuoteRequests", "\"CompanyId\"");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "SampleRequests" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_SampleRequests" PRIMARY KEY,
                "RequestNumber" TEXT NOT NULL DEFAULT '',
                "CompanyId" integer NOT NULL DEFAULT 0,
                "DateRequested" date NOT NULL DEFAULT CURRENT_DATE,
                "ContactEmployeeId" integer,
                "ContactPersonName" TEXT NOT NULL DEFAULT '',
                "CompanyRequested" TEXT NOT NULL DEFAULT '',
                "CustomerExternalId" TEXT NOT NULL DEFAULT '',
                "CustomerName" TEXT NOT NULL DEFAULT '',
                "IsNewCustomer" boolean NOT NULL DEFAULT false,
                "ProjectScope" TEXT NOT NULL DEFAULT 'new',
                "RequestType" TEXT NOT NULL DEFAULT 'new_submission',
                "ModificationDetails" TEXT NOT NULL DEFAULT '',
                "ProjectName" TEXT NOT NULL DEFAULT '',
                "DeliveryUnit" TEXT NOT NULL DEFAULT '',
                "ExpectedQtyPerYear" numeric NOT NULL DEFAULT 0,
                "ExpectedPrice" numeric NOT NULL DEFAULT 0,
                "ExpectedSalesAmountPerYear" numeric NOT NULL DEFAULT 0,
                "ProductCategory" TEXT NOT NULL DEFAULT '',
                "ProductGroup" TEXT NOT NULL DEFAULT '',
                "ProductSamplesJson" TEXT NOT NULL DEFAULT '[]',
                "WaterSoluble" boolean NOT NULL DEFAULT false,
                "OilSoluble" boolean NOT NULL DEFAULT false,
                "FlavourNatural" boolean NOT NULL DEFAULT false,
                "FlavourNaturalIdentical" boolean NOT NULL DEFAULT false,
                "FlavourArtificial" boolean NOT NULL DEFAULT false,
                "QuantityRequested" numeric NOT NULL DEFAULT 0,
                "QuantityUom" TEXT NOT NULL DEFAULT '',
                "TargetProducts" TEXT NOT NULL DEFAULT '',
                "GmoStatus" TEXT NOT NULL DEFAULT 'na',
                "AllergenStatus" TEXT NOT NULL DEFAULT 'na',
                "AllergenFreeFromDetail" TEXT NOT NULL DEFAULT '',
                "McpdHvpFreeDetail" TEXT NOT NULL DEFAULT '',
                "HalalCertified" boolean NOT NULL DEFAULT false,
                "HalalCompliantAccepted" boolean NOT NULL DEFAULT false,
                "CountryRdSite" TEXT NOT NULL DEFAULT '',
                "CountryManufacturing" TEXT NOT NULL DEFAULT '',
                "CountryInUse" TEXT NOT NULL DEFAULT '',
                "RegulatoryRequirement" TEXT NOT NULL DEFAULT 'na',
                "RegulatoryRequirementDetail" TEXT NOT NULL DEFAULT '',
                "CustomerDeadline" date,
                "ShareToken" TEXT NOT NULL DEFAULT '',
                "Status" TEXT NOT NULL DEFAULT 'submitted',
                "CreatedBy" TEXT NOT NULL DEFAULT '',
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "UpdatedAt" timestamp with time zone NOT NULL DEFAULT NOW()
            );
            """);

        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "ShareToken", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "TemplateType", "TEXT NOT NULL DEFAULT 'sample-request-flavours'");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "VendorExternalId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "VendorAddress", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "VendorContactPerson", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "VendorContactMobile", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "VendorContactEmail", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "IngredientComponentId", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "ProductPolicyTag", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "VendorAcceptedAt", "timestamp with time zone");
        await DatabaseSchemaHelper.TryAddColumnAsync(db, "SampleRequests", "VendorAcceptedBy", "TEXT NOT NULL DEFAULT ''");
        await TryCreateUniqueIndexAsync(db, "IX_SampleRequests_RequestNumber", "SampleRequests", "RequestNumber");
        await TryCreateIndexAsync(db, "IX_SampleRequests_CompanyId", "SampleRequests", "\"CompanyId\"");
        await TryCreateIndexAsync(db, "IX_SampleRequests_ShareToken", "SampleRequests", "\"ShareToken\"");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "DevQaRuns" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_DevQaRuns" PRIMARY KEY,
                "StartedAt" timestamp with time zone NOT NULL,
                "FinishedAt" timestamp with time zone,
                "Status" TEXT NOT NULL DEFAULT 'running',
                "TriggeredBy" TEXT NOT NULL DEFAULT '',
                "Summary" TEXT NOT NULL DEFAULT '',
                "ResultsJson" TEXT NOT NULL DEFAULT '[]'
            );
            """);
        await TryCreateIndexAsync(db, "IX_DevQaRuns_StartedAt", "DevQaRuns", "\"StartedAt\"");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "DevTeamUsers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_DevTeamUsers" PRIMARY KEY,
                "Email" TEXT NOT NULL DEFAULT '',
                "FullName" TEXT NOT NULL DEFAULT '',
                "PasswordHash" TEXT NOT NULL DEFAULT '',
                "Active" boolean NOT NULL DEFAULT TRUE,
                "IsRoot" boolean NOT NULL DEFAULT FALSE,
                "GoogleSubject" TEXT,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "CreatedByEmail" TEXT NOT NULL DEFAULT '',
                "UpdatedAt" timestamp with time zone
            );
            """);
        await TryCreateUniqueIndexAsync(db, "IX_DevTeamUsers_Email", "DevTeamUsers", "Email");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "DevConsoleSessions" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_DevConsoleSessions" PRIMARY KEY,
                "Token" TEXT NOT NULL DEFAULT '',
                "DevTeamUserId" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "ExpiresAt" timestamp with time zone NOT NULL,
                "GoogleEmail" TEXT NOT NULL DEFAULT '',
                CONSTRAINT "FK_DevConsoleSessions_DevTeamUsers_DevTeamUserId"
                    FOREIGN KEY ("DevTeamUserId") REFERENCES "DevTeamUsers" ("Id") ON DELETE CASCADE
            );
            """);
        await TryCreateUniqueIndexAsync(db, "IX_DevConsoleSessions_Token", "DevConsoleSessions", "Token");
        await TryCreateIndexAsync(db, "IX_DevConsoleSessions_DevTeamUserId", "DevConsoleSessions", "\"DevTeamUserId\"");

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "DevConsolePasswordTickets" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL CONSTRAINT "PK_DevConsolePasswordTickets" PRIMARY KEY,
                "Ticket" TEXT NOT NULL DEFAULT '',
                "DevTeamUserId" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
                "ExpiresAt" timestamp with time zone NOT NULL,
                "Consumed" boolean NOT NULL DEFAULT FALSE,
                CONSTRAINT "FK_DevConsolePasswordTickets_DevTeamUsers_DevTeamUserId"
                    FOREIGN KEY ("DevTeamUserId") REFERENCES "DevTeamUsers" ("Id") ON DELETE CASCADE
            );
            """);
        await TryCreateUniqueIndexAsync(db, "IX_DevConsolePasswordTickets_Ticket", "DevConsolePasswordTickets", "Ticket");
        await TryCreateIndexAsync(db, "IX_DevConsolePasswordTickets_DevTeamUserId", "DevConsolePasswordTickets", "\"DevTeamUserId\"");

        await CustomerSeeder.EnsureDemoCustomersAsync(db);

        await DatabaseSchemaHelper.PromoteAllRealColumnsToNumericAsync(db);
        await DatabaseSchemaHelper.PromoteLegacyIntegerBooleansAsync(db);
        await DatabaseSchemaHelper.PromoteLegacyTextTimestampsAsync(db);

        await B2bSalesOrderSeeder.EnsureDemoSalesOrdersAsync(db, new B2bSalesOrderService(db));

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "Companies"
            SET "ModulesJson" = '["RMS","POS","HRM","Accounting"]'
            WHERE "ModulesJson" IS NULL OR TRIM("ModulesJson") = '' OR "ModulesJson" = '[]';
            """);

        await DatabaseSchemaHelper.ResyncProductIdentitySequencesAsync(db);
        await DatabaseSchemaHelper.ResyncCoreIdentitySequencesAsync(db);
    }

    static async Task TryCreateIndexAsync(BisyncDbContext db, string indexName, string table, string columns)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync(
                $"CREATE INDEX IF NOT EXISTS \"{indexName}\" ON \"{table}\" ({columns});");
        }
        catch
        {
            // Index may already exist.
        }
    }

    static async Task BackfillIngredientComponentIdsAsync(BisyncDbContext db)
    {
        var needsId = await db.Ingredients
            .Where(i => i.ComponentId == null || i.ComponentId == "")
            .OrderBy(i => i.Id)
            .ToListAsync();

        foreach (var ingredient in needsId)
            ingredient.ComponentId = $"TMP-{ingredient.Id:D8}";

        if (needsId.Count > 0)
            await db.SaveChangesAsync();
    }

    /// <summary>
    /// Phase 0: assign legacy global catalog rows to the first company, then tighten uniqueness.
    /// </summary>
    static async Task BackfillCatalogCompanyIdsAsync(BisyncDbContext db)
    {
        var defaultCompanyId = await db.Companies.AsNoTracking()
            .OrderBy(c => c.Id)
            .Select(c => (int?)c.Id)
            .FirstOrDefaultAsync();
        if (defaultCompanyId is null)
            return;

        await db.Database.ExecuteSqlInterpolatedAsync($"""
            UPDATE "Ingredients" SET "CompanyId" = {defaultCompanyId.Value} WHERE "CompanyId" IS NULL;
            """);
        await db.Database.ExecuteSqlInterpolatedAsync($"""
            UPDATE "Vendors" SET "CompanyId" = {defaultCompanyId.Value} WHERE "CompanyId" IS NULL;
            """);
        await db.Database.ExecuteSqlInterpolatedAsync($"""
            UPDATE "Products" SET "CompanyId" = {defaultCompanyId.Value} WHERE "CompanyId" IS NULL;
            """);
        await db.Database.ExecuteSqlInterpolatedAsync($"""
            UPDATE "PurchaseOrders" SET "CompanyId" = {defaultCompanyId.Value} WHERE "CompanyId" IS NULL;
            """);
        await db.Database.ExecuteSqlInterpolatedAsync($"""
            UPDATE "InventoryPurchases" SET "CompanyId" = {defaultCompanyId.Value} WHERE "CompanyId" IS NULL;
            """);
        await db.Database.ExecuteSqlInterpolatedAsync($"""
            UPDATE "InventoryMovements" SET "CompanyId" = {defaultCompanyId.Value} WHERE "CompanyId" IS NULL;
            """);
        await db.Database.ExecuteSqlInterpolatedAsync($"""
            UPDATE "ProductProductionLogs" SET "CompanyId" = {defaultCompanyId.Value} WHERE "CompanyId" IS NULL;
            """);
    }

    static async Task EnsureCompanyScopedCatalogIndexesAsync(BisyncDbContext db)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync("""DROP INDEX IF EXISTS "IX_Ingredients_ComponentId";""");
            await db.Database.ExecuteSqlRawAsync("""DROP INDEX IF EXISTS "IX_Ingredients_Name";""");
            await db.Database.ExecuteSqlRawAsync("""DROP INDEX IF EXISTS "IX_Vendors_ExternalId";""");
            await db.Database.ExecuteSqlRawAsync("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Ingredients_CompanyId_ComponentId"
                ON "Ingredients" ("CompanyId", "ComponentId");
                """);
            await db.Database.ExecuteSqlRawAsync("""DROP INDEX IF EXISTS "IX_Ingredients_CompanyId_Name";""");
            await db.Database.ExecuteSqlRawAsync("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Ingredients_CompanyId_LowerName"
                ON "Ingredients" ("CompanyId", LOWER("Name"));
                """);
            await db.Database.ExecuteSqlRawAsync("""
                CREATE UNIQUE INDEX IF NOT EXISTS "IX_Vendors_CompanyId_ExternalId"
                ON "Vendors" ("CompanyId", "ExternalId");
                """);
            await db.Database.ExecuteSqlRawAsync("""
                CREATE INDEX IF NOT EXISTS "IX_Ingredients_CompanyId" ON "Ingredients" ("CompanyId");
                """);
            await db.Database.ExecuteSqlRawAsync("""
                CREATE INDEX IF NOT EXISTS "IX_Vendors_CompanyId" ON "Vendors" ("CompanyId");
                """);
        }
        catch
        {
            // Index swap may race on first boot; next startup retries.
        }
    }

    static async Task EnsureTenantConnectionsTableAsync(BisyncDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "TenantConnections" (
                "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "CompanyId" INTEGER NOT NULL,
                "DatabaseName" TEXT NOT NULL DEFAULT '',
                "ConnectionString" TEXT NOT NULL DEFAULT '',
                "ArchiveDatabaseName" TEXT NOT NULL DEFAULT '',
                "ArchiveConnectionString" TEXT NOT NULL DEFAULT '',
                "IsActive" BOOLEAN NOT NULL DEFAULT TRUE,
                "CreatedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
                "UpdatedAt" TIMESTAMP NOT NULL DEFAULT NOW()
            );
            """);
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TenantConnections", "ArchiveDatabaseName", "TEXT NOT NULL DEFAULT ''");
        await DatabaseSchemaHelper.EnsureColumnAsync(db, "TenantConnections", "ArchiveConnectionString", "TEXT NOT NULL DEFAULT ''");
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_TenantConnections_CompanyId"
            ON "TenantConnections" ("CompanyId");
            """);
        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "TenantConnections"
            SET "ArchiveDatabaseName" = "DatabaseName" || '_archive'
            WHERE ("ArchiveDatabaseName" IS NULL OR BTRIM("ArchiveDatabaseName") = '')
              AND "DatabaseName" IS NOT NULL AND BTRIM("DatabaseName") <> '';
            """);
    }

    static async Task BackfillTenantConnectionsAsync(BisyncDbContext db)
    {
        var companies = await db.Companies.AsNoTracking().Select(c => c.Id).ToListAsync();
        var existing = await db.TenantConnections.AsNoTracking()
            .Select(t => t.CompanyId)
            .ToListAsync();
        var have = new HashSet<int>(existing);
        var added = false;
        foreach (var companyId in companies)
        {
            if (have.Contains(companyId))
                continue;
            db.TenantConnections.Add(new TenantConnection
            {
                CompanyId = companyId,
                DatabaseName = $"bisync_c_{companyId}",
                ArchiveDatabaseName = $"bisync_c_{companyId}_archive",
                ConnectionString = string.Empty, // empty = shared default connection
                ArchiveConnectionString = string.Empty,
                IsActive = true,
                CreatedAt = DateTime.UtcNow,
                UpdatedAt = DateTime.UtcNow,
            });
            added = true;
        }
        if (added)
            await db.SaveChangesAsync();
    }

    static async Task EnsureTenantRollupSnapshotsTableAsync(BisyncDbContext db)
    {
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "TenantRollupSnapshots" (
                "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "GeneratedAt" TIMESTAMP NOT NULL DEFAULT NOW(),
                "Status" TEXT NOT NULL DEFAULT 'ok',
                "TenantCount" INTEGER NOT NULL DEFAULT 0,
                "ProvisionedCount" INTEGER NOT NULL DEFAULT 0,
                "SharedCount" INTEGER NOT NULL DEFAULT 0,
                "PayloadJson" TEXT NOT NULL DEFAULT '{{}}',
                "ErrorsJson" TEXT NOT NULL DEFAULT '[]'
            );
            """);
    }

    /// <summary>Public hook so Program can refresh registry after companies are seeded.</summary>
    public static Task EnsureTenantRegistryAsync(BisyncDbContext db) =>
        BackfillTenantConnectionsAsync(db);

    static async Task TryCreateUniqueIndexAsync(BisyncDbContext db, string indexName, string table, string column)
    {
        try
        {
            await db.Database.ExecuteSqlRawAsync(
                $"CREATE UNIQUE INDEX IF NOT EXISTS \"{indexName}\" ON \"{table}\" (\"{column}\");");
        }
        catch
        {
            // Index may already exist with different definition
        }
    }
}
